### ISSUE TITLE
<getTransaction> memory leak

### ISSUE THREAD

**Issue by pefish** [ethereum/web3.js#1053]
process count will increase when I execute web3.eth.getTransaction, and never decrease.

finally, my computer's process count is full so that I cannot open other app.

ps ax | wc -l

**Comment by frozeman** [comment]
Could you give some more information? As in web3.js the `web3.eth.getTransaction()` simply calls a method on the geth RPC there is no extra logic in web3.js which i could think of could cause memory leaks.
Can you send a screenshot. Which processes are created?

**Comment by bohendo** [comment]
I found a memory leak that's probably related. My code looks something like:

```
const remember = (i, contract, name) => { 
  if (i < 4605167) { // block at which cryptokitties was deployed
    // console.log(`${new Date().toISOString()} ===== Finished syncing ${name} events from ${contract}`)
    return('done')
  } 

  // log a chunk of our progress?
  if (OLD >= 100) { 
    console.log(`${new Date().toISOString()} [E] Found ${OLD} old ${name} events from ${contract} at/before block ${i} (${Math.round(15*(fromBlock-i)/60/60)} hours ago)`)
    OLD = 0 
  } 

  contract.getPastEvents(name, { fromBlock: i-6, toBlock: i }, (err, pastEvents) => { 
    if (err) { console.error(err); process.exit(1) } 
    OLD += pastEvents.length
    pastEvents.forEach(event=>{
      saveEvent(contract, name, event).then(()=>{ event = null }) // get garbage collected!
    })

    // give node a sec to clear the call stack & give ethprovider a sec to stay synced
    setTimeout(()=>{
      pastEvents = null // get garbage collected!
      remember(i-5, contract, name)
    }, throttle)
  })
```

I tried to manually get the garbage collector to do it's thing but nothing I've tried helps.

I used [heapdump](https://github.com/bnoordhuis/node-heapdump) to check out my memory and see a bunch of stuff that looks like:

```
"{\"jsonrpc\":\"2.0\",\"result\":[{\"address\":\"0x06012c8cf97bead5deae237070f9587f8e7a266d\",\"blockHash\":\"0x064a0e3a06dd2ca49e779ff2e968d11bdfe4ece2f4f35e7247d279c3f89e1594\",\"blockNumber\":\"0x4876e0\",\"data\":\"0x000000000000000000000000bc1b89612b8c8e006929197569818e785e427bfb0000000000000000000000000000000000000000000000000000000000055f47000000000000000000000000000000000000000000000000000000000004a976000000000000000000000000000000000000000000000000000000000004dbe400004a528310c430dc100df728c63388c75398828e4619ce5084634b99763989\",\"logIndex\":\"0x23\",\"topics\":[\"0x0a5311bd2a6608f08a180df2ee7c5946819a649b204b554bb8e39825b2c50ad5\"],\"transactionHash\":\"0x0db74aeef42979ee7608b87bd9a163164b6972f335f9e3a50bd11f1c26433480\",\"transactionIndex\":\"0x42\",\"transactionLogIndex\":\"0x0\",\"type\":\"mined\"},
...
```

I noticed that the data my code sees is from the above `result` property (ie I never see a `jsonrpc` property). I suspect that these are sticking around longer than they should because of something internal to web3.js but I'm not really sure. I'm about to dig through the source code a little & see what I can find.

**Comment by bohendo** [comment]
Google's [Memory Analysis 101](https://developer.chrome.com/devtools/docs/memory-analysis-101) says "Usually, only arrays and strings can have significant shallow sizes. However, strings often have their main storage in renderer memory, exposing only a small wrapper object on the JavaScript heap."

Which is probably significant since the stuff that's clogging up my memory appears to be strings rather than objects

**Comment by bohendo** [comment]
I updated my code to nullify my event promise but my memory's still blowing up.. How strange.

```
let eventPromise = contract.getPastEvents(name, { fromBlock: i-6, toBlock: i })

eventPromise.then(pastEvents => { 
  OLD += pastEvents.length
  pastEvents.forEach(event=>{
    saveEvent(contract, name, event).then(()=>{ event = null }) // get garbage collected!
  })

  // give node a sec to clear the call stack & give ethprovider a sec to stay synced
  setTimeout(()=>{
    eventPromise = null // get garbage collected!
    remember(i-5, contract, name)
  }, throttle)
}).catch(err=>{
  console.error(err)
  process.exit(1)
})
```
