### ISSUE TITLE
web3.eth.getBalance no BN object returned

### ISSUE THREAD

**Issue by florianlenz** [ethereum/web3.js#1187]
Hi, 

the docs are incorrect web3.eth.getBalance returns a string. Not an instance of BN. I don't know if that is a mistake of expected/wanted behavior.

Code to reproduce: 
```js
const Web3 = require('web3');

const web3 = new Web3(new Web3.providers.HttpProvider('http://my_provider.com'));

web3
    .eth
    .getBalance('0x687422eEA2cB73B5d3e242bA5456b782919AFc85')
    .then(balance => {
        "use strict";
        console.log(typeof balance)
    });

```

**Comment by 26000** [comment]
Found out that in `develop` branch it returns a BigNumber:
https://github.com/ethereum/web3.js/blob/develop/lib/web3/methods/eth.js#L105
https://github.com/ethereum/web3.js/blob/develop/lib/web3/formatters.js#L38
https://github.com/ethereum/web3.js/blob/develop/lib/utils/utils.js#L369

While the documentation for `1.0` says that it should return a `string`, so it isn't a documentation problem imo.

**Comment by bf** [comment]
Weird issue, why is this popping up?

**Comment by nivida** [comment]
Yes this is the correct behaviour. If you would like to have a BN object then please use toBN https://web3js.readthedocs.io/en/1.0/web3-utils.html#tobn

**Comment by gilamran** [comment]
@nivida Can you explain why is this the correct behavior?
The `decodeParameter` "knows" the type, and should auto-convert to `BN`. not doing so will force everyone to do the manual conversion of each field in the return struct.

```
const result = await contractMethod.call();
web3.utils.toBN(result.field1);
web3.utils.toBN(result.field2);
web3.utils.toBN(result.field3);
web3.utils.toBN(result.innerField.field4);
.
.
.
```
BTW: In version `1.0.0-beta.55` any `uint256` was automatically converted to `BN`

**Comment by nivida** [comment]
> 1.0.0-beta.55

This codebase will be used for version 2.x see our release announcement [here](https://github.com/ethereum/web3.js/releases/tag/v1.2.0) for more. 

> The decodeParameter "knows" the type, and should auto-convert to BN

Yes, this is true but it would break a lot of existing code. That's why 1.0 (beta.37) is returning those numbers still as ``string`` instead of ``BN`` objects.

**Comment by gilamran** [comment]
Ok, so correct me if I'm wrong
Version `1.0.0-beta.37` = version 1 (Existing projects are using this one)
Version `1.0.0-beta.55` = Future version 2 and Also version `1.2.0` and `2.0.0-alpha`?
What about version 1.2.X?

I'm confused...

**Comment by nivida** [comment]
Version 1.0.0-beta.37 = is now 1.x 
Version 1.0.0-beta.55 = is now 2.0.0-alpha.x (It will have a complete new functional API in the end)

Because the former maintainer published 1.x versions of sub-packages of web3.js and because npm doesn't allow us to remove those wrongly published versions we were forced to release it as 1.2.0.
