### ISSUE TITLE
filter.watch not working

### ISSUE THREAD

**Issue by tomasvit6** [ethereum/web3.js#1280]
_Web3 version: 0.20.2_

Why the following code does not work? No errors produced but never console logs anything. For me it worked two months ago but now I can't seem to find what changed.

```
    let filter = web3.eth.filter('latest');

    filter.watch((error, result) => {
        console.log(result);
    });

```

**Comment by guillembenosa** [comment]
I am also finding the same issue. Maybe 1.0.0 is taking over too hard

**Comment by huang47** [comment]
I ran into this problem before and my take away is that it depends on the which geth RPC web3 talks to. I guess it's still in `syncing` mode. You could poke `eth.syncing` and see if it returns `false`. Otherwise `latest` only returns when geth is up-to-date. see https://github.com/ethereum/go-ethereum/issues/15209#issuecomment-332509391

ref:
geth filter API: https://github.com/ethereum/go-ethereum/blob/master/eth/filters/api.go#L20

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
