### ISSUE TITLE
web3.eth.filter not work 

### ISSUE THREAD

**Issue by chenyunecjtu** [ethereum/web3.js#1286]
version: 0.20.3 
let filter = web3.eth.filter('pending');

filter.watch((error, result) => {
    console.log(result);
});

no data return

**Comment by frozeman** [comment]
Which node are you using?

**Comment by Alex1100** [comment]
try web3.eth.subscribe("pendingTransactions").then(list => console.log(list)).catch(error => console.log(erro)).unsubscribe();

**Comment by nivida** [comment]
@chenyunecjtu can this issue be closed?

**Comment by felixwatts** [comment]
I get this problem using web3js 0.19.0 and ganache-cli 6.2.3

[EDIT] I was mistaken. I was confused because the filter callback is called when the block is mined which happens sometime after the transaction receipt is received for the causing transaction. When testing you need to ensure your test waits until the event is fired (or a timeout is reached)

**Comment by nivida** [comment]
I'm closing it due to inactivity and because it looks like this issue isn't a bug of web3.
