### ISSUE TITLE
Webpack minification causing BigNumber arguments to be filtered

### ISSUE THREAD

**Issue by generalpiston** [ethereum/web3.js#1356]
## Issue
Running into `Invalid number of arguments to Solidity function` when calling `zeroEx.token.setUnlimitedProxyAllowanceAsync(address, account)`.

## Environment
- Using Webpack to transpile/aggregate/minify
- Browser
- Using web3 version `1.0.0-beta.21` and 0x.js is using version `0.20.4`.

## Notes
- It seems like `isBigNumber` (https://github.com/ethereum/web3.js/blob/develop/lib/utils/utils.js#L489) doesn't recognize the amount 0x.js sends as a `BigNumber`.
- Not minifying fixes this issue.

**Comment by abec** [comment]
Here's a bash script to hack around this:
```
#!/bin/bash

utils=$( find ./node_modules -name utils.js | grep "web3/lib/utils" )
for f in ${utils}; do
  sed -i.bk -E "s|object.constructor.name === 'BigNumber'|object.s !== undefined \&\& object.e !== undefined \&\& object.c !== undefined|" ${f};
done;
```

**Comment by koirikivi** [comment]
I also ran into this issue.

I think it would be best to rewrite the way the `isBigNumber` check works. The constructor name check doesn't seem robust, and other libraries might use different versions of `BigNumber.js` which causes the `instanceof` check to fail as well.

The current version of BigNumber.js sets the field `_isBigNumber = true` for all `BigNumbers` it creates, and offers a `isBigNumber` function that can be used to check if an object is a `BigNumber`. However, this doesn't seem to be implemented in the forked version used by web3 (https://github.com/frozeman/bignumber.js-nolookahead).

I think it would be good to update that package so that it also offers a `isBigNumber` function, and then rewrite the `isBigNumber` used by web3 in terms of that.

**Comment by graemecode** [comment]
@beether The problem with the above solution, which is otherwise somewhat elegant, is that you can't configure the BigNumber class. For example:

```javascript
// By default BigNumber's `toString` method converts to exponential notation if the value has
// more then 20 digits. We want to avoid this behavior, so we set EXPONENTIAL_AT to a high number
BigNumber.config({
    EXPONENTIAL_AT: 1000,
});
```

Moreover, my codebase might not have access to web3 everywhere I might want to use BigNumber,  and solutions to that particular problem can also become messy.

**Comment by nivida** [comment]
This should be solved within the next release. (PR #2000)
