### ISSUE TITLE
Select wrong ABI

### ISSUE THREAD

**Issue by melnikaite** [ethereum/web3.js#1409]
I have 2 functions with same name but different number of arguments.
```
abi = [
    {
      "constant": false,
      "inputs": [
        {
          "name": "myid",
          "type": "bytes32"
        },
        {
          "name": "result",
          "type": "string"
        }
      ],
      "name": "__callback",
      "outputs": [],
      "payable": false,
      "type": "function"
    },
    {
      "constant": false,
      "inputs": [
        {
          "name": "_queryId",
          "type": "bytes32"
        },
        {
          "name": "_result",
          "type": "string"
        },
        {
          "name": "_proof",
          "type": "bytes"
        }
      ],
      "name": "__callback",
      "outputs": [],
      "payable": false,
      "type": "function"
    }
]
```
When I want to call second `__callback` (with 3 arguments) it says that just 2 arguments expected. So web3 doesn't use correct ABI in this case and always use first one.
```
contractInstance = new web3.eth.Contract(abi, address)
contractInstance.methods.__callback(arg1, arg2, arg3).send()
Error: Invalid number of parameters for "__callback". Got 3 expected 2!
```

web3 1.0.0-beta.26
node 9.2.1
os x

**Comment by congxinUSC** [comment]
Hi! I think it might be because the ABI have some problem supporting overload feature. To facts I know might be relevant to this problem but not saying the exact thing:
1. Constructor overloading isn't supported yet, see: [http://solidity.readthedocs.io/en/develop/contracts.html?highlight=overload](http://solidity.readthedocs.io/en/develop/contracts.html?highlight=overload).
2. Enum is not supported by ABI yet, see: [http://solidity.readthedocs.io/en/develop/frequently-asked-questions.html?highlight=enum%20abi#if-i-return-an-enum-i-only-get-integer-values-in-web3-js-how-to-get-the-named-values](http://solidity.readthedocs.io/en/develop/frequently-asked-questions.html?highlight=enum%20abi#if-i-return-an-enum-i-only-get-integer-values-in-web3-js-how-to-get-the-named-values)

**Comment by nemani** [comment]
You can access the 2 different functions in the following way 

```javascript
contractInstance.__callback["bytes32,string"](param1,param2)
contractInstance.__callback["bytes32,string,bytes"](param1, param2, param3)
```

@nivida This (function overloading in general) does not seem to be present in the documentation, and should be added to it.

**Comment by nivida** [comment]
Closed because of the ongoing clean up of the issue list. Feel free to ask this in our gitter channel or on stackoverflow.
