### ISSUE TITLE
Documentation Error: web3.eth.net.getId

### ISSUE THREAD

**Issue by adrianmcli** [ethereum/web3.js#1410]
From the docs: http://web3js.readthedocs.io/en/1.0/web3-eth-net.html#getid

```
web3.eth.net.getId()
.then(console.log);
> 1
```

But the callback actually returns with two items, and the network id comes in the second parameter. That means the example needs to be like this to work:

```
web3.eth.net.getId()
.then((_, x) => console.log(x));
> 1
```

**Comment by peculiarity** [comment]
Which version of web3 are you using?

![image](https://user-images.githubusercontent.com/23715025/37212334-11564000-23af-11e8-82f8-72392f8424d3.png)

![image](https://user-images.githubusercontent.com/23715025/37212384-414f4c0c-23af-11e8-9677-6f08d5aabdec.png)

Also have in mind that using callback provided to the function has nothing to do with the `Promise.resolve`. If you are using the Promise approach, the error will be passed to the `.catch` callback meaning you have the resolved value (actual id) passed to the `.then` callback and rejected value (the error) passed to the `.catch` callback. 

Since you don't have the posibility to provide this kind of distinction when providing single callback to the  `.getId` method call, you will get two arguments to your callback function.

**Comment by adrianmcli** [comment]
Oh I'm stupid, I mixed up the callback approach with the `.then()` Promise approach. Thanks.
