### ISSUE TITLE
unable to install web3js using npm

### ISSUE THREAD

**Issue by vieiralc** [ethereum/web3.js#1411]
I was trying to install web3js using npm install web3
but I got the following error:

![image](https://user-images.githubusercontent.com/19657718/36860019-fe8f2028-1d5e-11e8-9054-4fd799daaa97.png)

**Comment by slesolliec** [comment]
same for me  :-(

Did you find a work around?

**Comment by slesolliec** [comment]
Tried with yarn too: same issue: cannot reach git://github.com/frozeman/WebSocket-Node.js
Basically, @vieiralc I guess you are too behind a firewall that blocks git:// protocol.
The silly thing is that it's just a question of changing git:// into git+https:// in one of the numerous dependecies of that package and it will work. (cannot figure out which dep').

Or just open port 9418 in your firewall  :-]

This is silly: that package has 296 dependecies and you're blocked just because one has a reference to git:// instead of git-https:// or more simply http://github.com/blahblah...

Sorry I can only explain what is going wrong, and not fix it  :-(

**Comment by Febin56** [comment]
Same error here, Appreciate the solution

**Comment by vieiralc** [comment]
Here at work I can't open port 9418 on the firewall, I don't have the necessary permissions

**Comment by vieiralc** [comment]
on windows for some reason you must install web3@0.20.0 otherwise it wont work

**Comment by nivida** [comment]
Please have a look at https://github.com/ethereum/web3.js/issues/1783 and be sure your firewall and GIT are configured correctly.
