### ISSUE TITLE
question: moving web3 type definition to be a @types package

### ISSUE THREAD

**Issue by AhnpGit** [ethereum/web3.js#1445]
Hi,
I have a question regarding to web3 TypeScript definition that does the team intend to move web3 type definition to @types package or prefer to keep it here ?

**Comment by Levino** [comment]
Why did you close this? The types should indeed be maintained with the @types package and not here. There are multiple reasons for it.
a. Looks like most of the maintainers for this package to not speak typescript very well, because otherwise this package would be written in typescript.
b. It is impossible to install the package as of now (version 1.0-beta.3x) without the types. But it is essential to be able to. Because when the types of the package are broken, it is very difficult to fix the errors when the types are shipped with the package. As opposed with the @types package, one can simply remove the dep to @types/web3 and add patched types locally.

Also see [best practices](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) for publishing typings:
>Now that you have authored a declaration file following the steps of this guide, it is time to publish it to npm. There are two main ways you can publish your declaration files to npm:
>
> 1. bundling with your npm package, or
> 1. publishing to the @types organization on npm.
>If your package is written in TypeScript then the first approach is favored. Use the --declaration flag to >generate declaration files. This way, your declarations and JavaScript always be in sync.
>
>**If your package is not written in TypeScript then the second is the preferred approach.**
