### ISSUE TITLE
HttpProvider#sendAsync removed in 1.0.0-beta.30

### ISSUE THREAD

**Issue by Freyert** [ethereum/web3.js#1451]
The `HttpProvider's` prototype is being overwritten by: `web3-providers-http@1.0.0-beta.30`. This removes the `sendAsync` method from the provider.

`truffle` has a dependency on `sendAsync`.

trufflesuite/truffle-provider#12

**Comment by vongohren** [comment]
So do etherjs rpc, that some libraries depend on.
https://github.com/ethjs/ethjs-rpc/blob/master/src/index.js#L46

So if I use these libraries, send in my provider from web3, then it crashes down the stack, because sendAsync cannot be called.

Im using ethr-did-resolver now, and they use ethjs in the background.

**Comment by nivida** [comment]
sendAsync will no longer exist and also the provider's methods are not a part of public API that's why they are not documented. I think it would be good to just use the send method. Because of this I will close this issue.
