### ISSUE TITLE
PromiEvents can't be safely composed with promises nor returned in async functions

### ISSUE THREAD

**Issue by alcuadrado** [ethereum/web3.js#1547]
`PromiEvent`s are automatically converted to `Promise`s when used in combination with `Promise`s or async functions:

1. In the first case, whenever a `PromiEvent` is returned by a callback passed to `then()` a `Promise` is returned. This may be fixed by using `Symbol.species`, but the semantics of a `PromiEvent` after a `then()` may not be clear.

2. Async functions always return a built-in `Promise`. If the returned value is a `Thenable` it is awaited and a promise with its value/error is returned.

My understanding is that async functions [are designed to only work with native promises](https://github.com/tc39/ecmascript-asyncawait/issues/40#issuecomment-94590953), which makes  safe `Promise` extensions pretty much impossible, as the not-so-versed-in-ES programmer will naturally try to use them in conjunction with async functions.

Here is a script with examples of both issues. I tested it with web3@1.0.0-beta.33.

```js
// This is just an example of something that the user may want to do/get
// asynchronously.
function getValue() {
  // Note: This could also be implemented with an async function, but the result
  // would be the same.
  return Promise.resolve(0);
}

function sendTxSync(web3, account) {
  // Here we do nothing async, so we hardcode the value
  return web3.eth.sendTransaction({from: account, to: account, value: 0});
}

// Case 1
function sendTxPromise(web3, account) {
  return getValue()
    // The callback returns a PromiEvent, but it's transformed to a Promise.
    .then(value => web3.eth.sendTransaction({from: account, to: account, value}));
}

// Case 2
async function sendTxAsync(web3, account) {
  // This function is async because we want to use await here
  const value = await getValue();

  // Most users would expect that this returns a PromiEvent, but it doesn't
  return web3.eth.sendTransaction({from: account, to: account, value});
}

function isPromiEvent(object) {
  return object.on !== undefined && object.then !== undefined;
}

async function main() {
  const web3 = new Web3(Web3.givenProvider);
  const accounts = await web3.eth.getAccounts();

  const promiEvent = sendTxSync(web3, accounts[0])
  console.log("Is return value of sendTxSync a promiEvent?", isPromiEvent(promiEvent)); // true

  const withAsync = sendTxAsync(web3, accounts[0])
  console.log("Is return value of sendTxASync a promiEvent?", isPromiEvent(withAsync)); // false

  const withPromise = sendTxPromise(web3, accounts[0])
  console.log("Is return value of sendTxPromise a promiEvent?", isPromiEvent(withPromise)); // false
}

main().catch(console.error);
```

**Comment by archangel-irk** [comment]
In addition, `.getValue()` may represent async `.getAccounts()` which result needed in `.sendTransaction()` or `methods.myMethod.send()` as `from` parameter.

**Comment by alcuadrado** [comment]
Hey @nivida, I read [your article](https://medium.com/@samuel_91690/my-first-months-as-the-maintainer-of-web3-js-7715470b7ef7) and immediately remembered this issue. I'm glad it's included in the 1.0 milestone project.

Do you have anything in mind to solve this problem?

**Comment by nivida** [comment]
@alcuadrado Until now not because I'm currently writing tests and have the focus to merge the PR #2000. But I'll definitely explain the solution, when I started to implement this enhancement.

**Comment by alcuadrado** [comment]
Got it! You are doing a great job as a new maintainer, thank you. 

I'm happy to help with this issue when you have time to get back to it.

**Comment by luzzif** [comment]
News on this? I would love to use `PromiEvent` with an `async`/`await` syntax

**Comment by alcuadrado** [comment]
@luzzif there's no way to return them from an `async` function. Those are intended to always return native promises.

You can `await` them now. Using them as promises (e.g. calling `.then()`) would require some very nasty hacks with `Symbol.species`.

**Comment by elanpang** [comment]
is there any best practice or example to write the right code ？

**Comment by alcuadrado** [comment]
You can treat them as `Promise`s @elanpang. Just don't expect to have any event-based functionality after you:

1. Return a `PromiEvent` from an `async` function.
2. Use `PromiEvent`'s `.then`, `.catch` or `.finally`.

Those return native `Promise`s.

**Comment by elanpang** [comment]
@alcuadrado  Thanks for your reply！
 I want to get 3 times confirmation so I have to write code like below：

```
  sendTx(serializedTx) {
    return new Promise((resolve, reject) => {
     this.web3.eth.sendSignedTransaction(`0x${serializedTx.toString('hex')}`)
        .on('transactionHash', (hash) => {
          console.log('myContract transactionHash:', hash);
        }).on('receipt', (receipt) => {
          console.log('myContract receipt:', receipt);
        }).on('confirmation', (confirmationNumber) => { // (confirmationNumber, receipt) 
          console.log('myContract confirmationNumber:', confirmationNumber);
          if (confirmationNumber >= 3) {
            resolve();
          }
        })
        .on('error', (err) => { // If a out of gas error, the second parameter is the receipt.
          console.log('myContract err:', err);
          reject();
        })
        .catch((err2) => {
          console.log('myContract err2:', err2);
          reject();
        });
    });
}
```

But after resolve, the on('confirmation'... subscribe callback is still running, is there a grace way to end  all the subscription after I got 3 times confirmation safely ?

**Comment by alcuadrado** [comment]
Sorry, I'm not familiar with that part of the codebase. I think I'd ignore the `PromiEvent` and do something like:

```js
async function sendTx(signedTx) {
  const hash = await web3.eth.sendSignedTransaction(`0x${serializedTx.toString('hex')}`);

  do {

    await sleep(5000);

    const receipt = await web3.eth.getTransactionReceipt(hash);

    if (receipt === null) {
      continue;
    }

    if (txFailed(receipt)) {
      // Note that this may be complicated if a tx can fail, and later be 
      // successful because of a chain reorganization
      throw Error('The transaction failed')
    }

  } while (notEnoughConfirmations(receipt))
}

function sleep(millis) {
  return new Promise(resolve => setTimeout(resolve, millis))
}
```

Don't expect that to work, it's just pseudocode to illustrate the idea. You probably also want a max waiting time.

**Comment by elanpang** [comment]
Good idea! Thanks for your help @alcuadrado
But I found that await the result(it is a receipt) of sendSignedTransaction need very very long time.....
And if I called sendSignedTransaction multi times in a short time, it is easy to be failed (like timeout or or no response) , I'm feeling very confuse about this function,  sad T.T

**Comment by alcuadrado** [comment]
> But I found that await the result(it is a receipt) of sendSignedTransaction need very very long time.....

Oh, I see! That's such a bad design decision 😖 Have you tried  using `.once('transactionHash', () => {...}` to get the hash and then poll for the receipt as I showed?  You'd also need a `.once('error'` I guess.

**Comment by CryptoKiddies** [comment]
Don't really on events for long term or critical logic. Just do long polling from the client or backend routine with state of txn stored to a DB!

**Comment by HyperCharlie** [comment]
Just ran into this issue today, working with Typescript. Basically, you can't use a PromiEvent anywhere inside a promise chain, because even if it mechanically works with await(), Typescript will not let you return it as a type. I resorted to just wrapping PromiEvents into a non-promise extension class: 

```typescript
import PromiEvent from 'web3/promiEvent';
export class PromiEventWrapper<T> {
    constructor(public promiEvent: PromiEvent<T>) {}
}
```

I use it like this:
```typescript
public async create(proof: OpenChannelProof, options?: any): Promise<PromiEventWrapper<null>> {
        const instance = await this.contractProvider.getHypernetInstance();
        const promiEvent = instance.openChannel(...proof);
        
        return new PromiEventWrapper(promiEvent);
    }

```

Where instance.openChannel() returns a PromiEvent<null>, and getHypernetInstance() is your run of the mill async function. Just posting in the vague hope I can save folks a few hours of experimentation if they need a quick fix.

**Comment by lautarodragan** [comment]
Facing this same issue... trying to access the PromiEvent returned by `sendSignedTransaction` but couldn't so far. Since the whole application uses promises everywhere, and particularly to `estimateGas` and `getTransactionCount` while creating the transaction, it's practically impossible to access the PromiEvent returned by `sendSignedTransaction` in a clean, intuitive way.

Options I've thought of or read here so far boil down to
- Wrapping the PromiEvent in something that isn't Promise-compatible. Really dislike this approach as it's introducing a wrapper with no real purpose.
- Passing callbacks for `onTransactionHash`, `onReceipt`, `onConfirmation` and `onError` to my `sendSignedTransaction` function... I think I dislike this one even more.

I totally understand the value of being able to `await myPromiEvent` as a sort of default, easy to implement behaviour... but I also feel the downsides are very big. Would it be too bad for some functions to not return a PromiEvent but rather just a normal Event (or, in the case of the [Observable](https://github.com/ethereum/web3.js/issues/2742), not make it then-able)?

So, a couple of questions:
- Are there any other, better approaches to retrieving the PromiEvent inside a Promise?
- @nivida would you consider a different approach for 2.x, where some functions just return a Promise and others just an Observable / Event?

**Comment by nivida** [comment]
@lautarodragan 
> it's practically impossible to access the PromiEvent returned by sendSignedTransaction in a clean, intuitive way.

This is sadly the truth. There is also no way to fix this in a non-breaking or clean manner. 

> Are there any other, better approaches to retrieving the PromiEvent inside a Promise?

All possible ways are already documented in this issue. There is a possibility to fix this with the [Symbol.species](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/species). But I wouldn’t recommend such hacky fixes because there are potential un-known cases where such a fix doesn't work as expected. In other words: Yes, it is fixable but not in a stable and future proof manner. 

> @nivida would you consider a different approach for 2.x, where some functions just return a Promise and others just an Observable / Event?

Yes, the idea for 2.x would be to remove all callbacks and the PromiEvent object. The 2.0 API should only return native Promises, an RxJs compatible Observable object, or an EventEmitter.
I currently listed the EventEmitter object as well because there are potential cases where a normal Observable with the next, complete, and error callback doesn't fitt in our requirements. The definitive public asynchronous API is currently in the planning phase and open about any feedback.

**Comment by lautarodragan** [comment]
> Yes, the idea for 2.x would be to remove all callbacks and the PromiEvent object. The 2.0 API should only return native Promises, an RxJs compatible Observable object, or an EventEmitter.
I currently listed the EventEmitter object as well because there are potential cases where a normal Observable with the next, complete, and error callback doesn't fitt in our requirements. The definitive public asynchronous API is currently in the planning phase and open about any feedback.

Than's great news :smile: I'll stick with the wrapper approach then until 2.0.0 is released.

Thanks @nivida!

**Comment by alcuadrado** [comment]
Not sale

**Comment by cxk280** [comment]
This issue should still be open.

**Comment by alcuadrado** [comment]
As this is not something fixable without a huge breaking change, maybe it'd be good to document the limitations discussed here.
