### ISSUE TITLE
npm install web3 broken

### ISSUE THREAD

**Issue by NoahHydro** [ethereum/web3.js#1588]
Installing web3 1.0 with npm fails with node10/npm6 because of an error in sha3. See [this issue](https://github.com/phusion/node-sha3/issues/32) for details.

**Comment by BKDaugherty** [comment]
Doesn't work with yarn either ^^^

**Comment by NoahHydro** [comment]
I submitted a [PR in the sha3 repo](https://github.com/phusion/node-sha3/pull/33) fixing this issue.

**Comment by BKDaugherty** [comment]
Working now! Thank you @NoahHydro!!!

**Comment by bladexxv** [comment]
Having exact same issue here.  Hope it can get fixed ASAP. Thank you.  see also [https://github.com/phusion/node-sha3/issues/32]

**Comment by gitpusha** [comment]
Hi everyone, 
Suddenly since yesterday I cannot npm install web3 any more.  I am using MacOs and hombrew node. The only change that might have caused this is that I think I ran a brew update and brew upgrade recently. 
npm -v 6.9.0
node -v v12.1.0

The problem seems to have something to do with sha3 and node-gyp. I saw this issue which seems to be related. Can anyone please help me out or point me to a solution for macOS with my node and npm versions?

error message:
10 warnings and 12 errors generated.
make: *** [Release/obj.target/sha3/src/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/Cellar/node/12.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xyz/Desktop/udemy/udemy-eth-sol/projects/kickstart/node_modules/sha3
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN kickstart@1.0.0 No description
npm WARN kickstart@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: scrypt@6.0.3 (node_modules/scrypt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: scrypt@6.0.3 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by canterberry** [comment]
Have a look at [phusion/node-sha3 #32](https://github.com/phusion/node-sha3/issues/32#issuecomment-490157571) -- the root cause is that `node-gyp` is incompatible with Node.js 12.x, and older versions of the **sha3** package (which web3 currently depends on) use this for native compilation steps.
