### ISSUE TITLE
web3.eth.subscribe(“logs”) not working when using array with multiple addresses (Web3 1.0)

### ISSUE THREAD

**Issue by elie222** [ethereum/web3.js#1600]
I'm trying to use `web3.eth.subscribe(“logs”)` to listen to multiple addresses:
https://web3js.readthedocs.io/en/1.0/web3-eth-subscribe.html#subscribe-logs

The docs say:

> address - String|Array: An address or a list of addresses to only get logs from particular account(s).

When I put one address in it works. It also works when I put an array containing a single address. However when I put an array with multiple addresses, it doesn't listen to either of the addresses. Is this a bug or am I doing something wrong?

So for example, this gets logs as expected:

```
  const options = {
    fromBlock: 0, 
    toBlock: 'latest',
    address: '0x56719fDa968D45042E6761DE23c4139127315EBE'
  }

  web3.eth.subscribe('logs', options, callback)
```

This does too:

```
  const options = {
    fromBlock: 0, 
    toBlock: 'latest',
    address: ['0x56719fDa968D45042E6761DE23c4139127315EBE']
  }

  web3.eth.subscribe('logs', options, callback)
```

But this doesn't work:

```
  const options = {
    fromBlock: 0, 
    toBlock: 'latest',
    address: ['0x56719fDa968D45042E6761DE23c4139127315EBE', '0xC21012955092E09158648A36C3010Bf70130CCC4']
  }

  web3.eth.subscribe('logs', options, callback)
```

I'm testing this against Ganache UI if that makes a difference here.

**Comment by Revinand** [comment]
Same here. But in my case the subscription only works when address is a string.

Any updates?

**Comment by Revinand** [comment]
The problem is in the `web3-provider-engine` module which is used by Ganache.

https://github.com/MetaMask/provider-engine/pull/280

**Comment by nivida** [comment]
Closed because it was an issue of ganache/web3-provider-engine. @Revinand thanks!

**Comment by hexcreator** [comment]
I know this is 3 years later, but I experienced an odd problem that is very relevant to this one. Subscribing to multiple topics like the OP described works now, but the problem I ran into was with creating multiple subscriptions with different topics. Example:
```typescript
let options_1 = { topics: [ sig_1 ] };
let options_2 = { topics: [ sig_2 ] };
let sub_1 = provider.eth.subscribe('logs', options_1 );
let sub_2 = provider.eth.subscribe('logs', options_2 );
sub_1.on('data', handler_1);
sub_2.on('data', handler_2);
```
Nearly identical behavior mentioned in the OP happens here:

1. The subscriptions do not function, therefore never invoking the handlers.
2. If I remove one subscription, the other one works. E.g., I disable sub2 and sub1 works, I disable sub1 and sub2 works

The fix was to create one subscription with both filters and merging the separate handlers together. Am I not understanding something correctly or is this a genuine issue? I can make a new ticket if necessary, just unsure if that's the right thing to do here. Apologies if I am in the wrong place.
