### ISSUE TITLE
web3.utils.fromWei failed when passing BigNumber instance as parameter

### ISSUE THREAD

**Issue by nosuchip** [ethereum/web3.js#1666]
Versions:
- node: v8.11.1.
- npm: 6.1.0.
- bignumber.js: "^7.2.1".
- web3: "^1.0.0-beta.34".

```
> var BigNumber = require('bignumber.js');
undefined
> var Web3 = require('web3')
undefined
> var web3 = new Web3();
undefined
> var a = new BigNumber(10000000000000000000)
undefined
> a.toString()
'10000000000000000000'
> web3.utils.fromWei(a)
Error: Please pass numbers as strings or BigNumber objects to avoid precision errors.
    at Object.fromWei (/home/alp/proj/coinbet/backend/node_modules/web3-utils/src/index.js:192:15)
> 
```

**Comment by oliversd** [comment]
Hi @nosuchip the utils library of web3 is using bn.js and not bignumber.js as you can see in node_modules/web3-utils/src/utils.js

If you use bn.js works fine.

I think this is confusing because:

1. bignumber.js it's more popular
2. bn.js it's BigNum and not BigNumber

I see that @frozeman it's the author of utils so maybe he can give us more information of why he choose this library,  and perhaps change the error message to be more clear about the library that are using.

**Comment by nosuchip** [comment]
@oliversd @frozeman  I see  inconsistency here, while `web3` itself operates with BigNumber.js (see `package.json`) web3-utils that even hasn't its own repository uses another bignumber implementation? Looks very strange.

**Comment by nosuchip** [comment]
@frozeman could you comment why BN.js used here?

**Comment by wtzb** [comment]
I'm also rather curious as to why BN.js was chosen, as bignumber.js has support for handy features such as decimals, while BN.js does not. The inconsistent error message stating that a BigNumber objects needs to be passed has made me spend more time than I'm willing to admit on debugging.

**Comment by adityataday** [comment]
I agree with @wtzb  when I try values like web3.utils.toBN(0.01) it fails. There is a work around though, one can use bignumber.js do all the arithematic and then for web3 methods convert bignumber to string. What would indeed be better is if web3 directly supported bignumber.js.

**Comment by nivida** [comment]
Duplication of https://github.com/ethereum/web3.js/issues/2468
