### ISSUE TITLE
Installing web3 on CentOS produces errors

### ISSUE THREAD

**Issue by ftppro** [ethereum/web3.js#1976]
Installing web3 using "npm install web3" produces the errors shown at the bottom of this post, and then web3 does not appear in package.json.

My server is CentOS v. 6.9, 64 bit.

I am able to use NPM to install other packages without errors, and they appear in package.json.

I use Infura, so I do not have a local Ethereum node installed.

Here are the errors:
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 2.6.32-042stab112.15
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/zmidipro/public_html/test/node_modules/scrypt
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-27T18_33_22_975Z-debug.log

**Comment by oliversd** [comment]
Hi @ftppro the problem is with the node-gyp package, normally this is a problem with the python version that node-gyp uses for build. Currently it doesn't support python 3. 

A work around is to use this line to install using python 2.7:

npm install --python=python2.7 web3

Or you can create and activate a environment with python2.7 with conda https://conda.io/docs/user-guide/tasks/manage-environments.html

Hope this helps.

**Comment by ftppro** [comment]
If the problem can be so easily solved by using "npm install --python=python2.7 web3", then why doesn't web3 have that command built into their default npm installation? And why isn't this workaround documented anywhere? 

I am very hesitant to install something where an undocumented solution could cause additional problems. I attempted to install web3 on a "vanilla" CentOS machine. This is a new dedicated server provided by GoDaddy. If "npm install web3" does not work in that environment, then I have doubts about the stability of the web3 project. Didn't anyone test it on a new CentOS machine, before releasing it??

**Comment by oliversd** [comment]
This is not a problem of web3 is a problem of your environment (you have python 3 instead of 2) and of the support of the dependency of [node-gyp](https://github.com/nodejs/node-gyp), that is not maintained by web3. There is no way that you can make a library ready for each OS and for each configuration.

If you look for this error on Google you will find hundreds of libraries that depend on node-gyp that have the same problem. It's no easy to please everybody and part of the day to day of a developer is find solutions to this kind of problems.

On the other hand if you want to be part of the solution you can make a pull request for the README or the web3 documentation to specify what to do if someone find this problem, this is a open source project so you can contribute as well.

**Comment by ftppro** [comment]
Why did version 0.20.7 install with no problems, yet the default "npm install web3" fail? What features did they add to web3 version 1.x that requires that this problem occurs? 

I also tried to install it on a CentOS machine that is 2 years old, and the same problem happened. Why would they require a version of Python that is more than 2 years old?

**Comment by ftppro** [comment]
Did they choose to use node-gyp for version 1.xx (and not version 0.20.7)? Perhaps they shouldn't have used node-gyp, if node-gyp requires a version of Python that is more than 2 years old. Otherwise, they have to modify the program that installs the current version of web3. Linux is the most popular OS for servers, they really should test it on the current Linux version.

**Comment by munrocket** [comment]
@oliversd maybe cmake-js is better?
