### ISSUE TITLE
When will web3 1.0 no longer be in beta? 

### ISSUE THREAD

**Issue by elie222** [ethereum/web3.js#1995]
Seems like it's been in its current beta state for a very long time.

**Comment by nivida** [comment]
Yes, it is because we have to do some improvements before we can call it a stable version. I've done a bigger refactoring of the codebase in the PR https://github.com/ethereum/web3.js/pull/2000 and this will solve many issues we currently have with web3. Unfortunately, I can't say when exactly it will be out of the beta state but it will be as soon as possible.
