### ISSUE TITLE
npm install web3js error on windows10

### ISSUE THREAD

**Issue by shwetaudacious** [ethereum/web3.js#2002]
I am trying to install web3 using command

`npm install --save web3@1.0.0-beta.26`  However I am getting error-
`verbose node v8.9.1
verbose npm  v4.6.1
 error code 128
 error Command failed: git -c core.longpaths=true rev-list -n1 browserifyCompatible
 error fatal: ambiguous argument 'browserifyCompatible': unknown revision or path not in the working tree.
 error Use '--' to separate paths from revisions, like this:
 error 'git <command> [<revision>...] -- [<file>...]' `

I have tried starting cmd with admin privileges and executing from git bash. Any inputs will be highly appreciated.

**Comment by chmelva4** [comment]
Does the problem still persists? I tried it now and it worked for me. I have node v8.12.0 and npm v6.4.1.

**Comment by Huanzhang89** [comment]
Hi @shwetaudacious, do you need to be node v8.9.1? If not, try updating your Nodejs and try installing again.

@nivida wrote a good step by step guide in the following comment for a clean install in windows which could be of help to you aswell.
https://github.com/ethereum/web3.js/issues/1783#issuecomment-405650471

Some others have had issues with node-gyp due to either not having python installed or having python v3.x.x. Make sure your machine has python v2.7.0 as that version has been confirm to work with node-gyp.

**Comment by nivida** [comment]
Closed because of the ongoing clean up of the issue list. Feel free to ask this in our gitter channel or on stackoverflow.
