### ISSUE TITLE
web3.eth.accounts.privateKeyToAccount generates different accounts from the same privatekey

### ISSUE THREAD

**Issue by Keith-CY** [ethereum/web3.js#2005]
`web3.eth.accounts.privateKeyToAccount` treats '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee' and 'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee' as different private keys.

It's a bug in [eth-lib](https://github.com/MaiaVictor/eth-lib/), would you please add a patch to Account Module until the [pr](https://github.com/MaiaVictor/eth-lib/pull/9) is merged?

**Comment by Jason-Soo** [comment]
Hi there, hopefully this helps
https://dev.to/yukkurisinai/big-trap-of-web3js-ffi

**Comment by Keith-CY** [comment]
@Jason-Soo Thanks, that's almost what I PRed in eth-lib.

**Comment by Jason-Soo** [comment]
@Keith-CY  I recently tried using ethers.js not as big community but its quite simple as well do check them out and I used this very simple amateur code to solve it haha

    if (key.substring(0, 2) !== '0x') {
        key = '0x' + key;  //checking
    }

**Comment by lebed2045** [comment]
+1, spent some time to figure out why my public address isn't valid. When you create account from the private key without 0x - everything will be executed without error. But later on will crash, for exmaple
because: 
```
  var sig = secp256k1.sign(msgHash, privateKey);
                      ^

RangeError: private key length is invalid
```
Also, according to documentation https://web3js.readthedocs.io/en/1.0/web3-eth-accounts.html#privatekeytoaccount input should always start from `0x` therefore private key correct format checking is necessary.

**Comment by nivida** [comment]
Closed because of the answer from @lebed2045
