### ISSUE TITLE
web3.eth.getAccounts() returns empty array

### ISSUE THREAD

**Issue by niklops** [ethereum/web3.js#2091]
Hi,
I'm using MetaMask and Ropsten provider.
 
Trying to get list of accounts by this code:
```js
var accounts = web3.eth.getAccounts((error,result) => {
        if (error) {
            console.log(error);
        } else {
            console.log(result);
        }       
    });
```

, but always result is empty array.

My metamask is enable and logged in.
Web3 version: 1.0.0.

code before getting accounts:
```js
var Web3 = require('web3');

if (typeof web3 !== 'undefined') {
    web3 = new Web3(web3.currentProvider);
} else {
    web3 = new Web3(new Web3.providers.HttpProvider('https://ropsten.infura.io/<token>'));
}
```

Please tell me, what I'm doing wrong ?

**Comment by joshstevens19** [comment]
Hey thanks for the issue, MM have released a breaking change on November the 6th which means people had to approve that web3 should be injected into the browser 

https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8

Looks like you are doing it the old way, if you do not do it the new way `web3.eth.getAccounts` will always return a empty array as its not been authenticated. 

Hope the article helps, let me know 👍

**Comment by niklops** [comment]
Thanks @joshstevens19 ! It helped me.
Also, I found out that MM doesn't work with local html file. I mean, if I'm trying testing in browser with local path, such as "file:///D:/project/index.html", MetaMask doesn't inject the variable "window.ethereum" and I can't set MetaMask provider and get current accounts.
After installing the Chrome application "Web Server for Chrome" and setting localhost path, like a "http://127.0.0.1:8887/project/index.html", everything works great!

**Comment by joshstevens19** [comment]
great glad to help! Thanks

**Comment by sumeetkhillare** [comment]
Add your site in metamask >settings>Connections>add site

**Comment by icervot** [comment]
Added localhost and 127.0.0.1 in metamask but still returns empty array.
Unless https is required, I don't know what it is.

**Comment by AanshSavla** [comment]
This problem is because the dapps and metamask have stopped exposing user accounts by default on web page.
Just use 'ethereum.enable()' as first line of your javascript code.
It worked for me.

**Comment by mrpriyansh** [comment]
**Alternate Solution**
Step1: Visit the website from which you want to access MetaMask .
Step2: Click on the account option button(vertical ellipsis icon) of MetaMask extension.
Step3: Click on the Connected sites menu.
Step4: Click on "**_Manually connect to current site_**" and then grant all the permission that it asks for.

You will get a _connected status_ at the top left corner.

**Comment by Alfred-Onuada** [comment]
> This problem is because the dapps and metamask have stopped exposing user accounts by default on web page.
> Just use 'ethereum.enable()' as first line of your javascript code.
> It worked for me.

This works perfectly. Thanks

**Comment by ahmad1091** [comment]
Later versions of **metamask** request permission to return the account, so after requesting the accounts **metamask** extension will popup to ask you for permission in the browser.
Another thing I notice that you are using `getAccounts()`, but in later versions of **metamask** you can use `requestAccount()` instead.

**The shortest way to solve this:**

***instead of:***
` web3.eth.getAccounts().then(console.log);`

***Use:***
`web3.eth.requestAccounts().then(console.log);`

After that **metamask** extention will ask you to confirm permissions then everything should go as expected :D 

After confirming access permission with **metamask**, then go to **metamask** extension setting click on Connected sites, you can find your development domain.

If you find your development domain then everything is ok, and `getAccounts()` can work now, although you can keep `requestAccounts()` and everything still the same.

**Comment by deepaksinghvi** [comment]
If you enable ethereum in browser it would work. On execute of the next line MetaMask window will open and you need to click on next.
 await window.ethereum.enable();
 

```
const web3 = new Web3(window.ethereum)
const netId = await web3.eth.net.getId()
console.log(netId)
await window.ethereum.enable();
const accounts = await web3.eth.getAccounts()
console.log(accounts)
```
