### ISSUE TITLE
{"_40":0,"_65":0,"_55":null,"_72":null} Error

### ISSUE THREAD

**Issue by yongloon** [ethereum/web3.js#2167]
I am getting object {"_40":0,"_65":0,"_55":null,"_72":null} from the balanceOf function. How to solve it?
```
var tokenContract = new web3.eth.Contract(contractABI, contractAddress);
	var balance = tokenContract.methods
		.balanceOf('0x845135e86c51d2970D8df4C28de2B600bDACBfF4')
		.call(function(err, balance) {
			
		});
console.tron.log('myTokenBalance: ' + JSON.stringify(balance));
```

**Comment by dev1644** [comment]
I am unable to reproduce this output, I am using the same snippet with another Contract ABI and its returning 
balance in the string.
More elaborative description of your issue is needed, also share the Contract address and the network on which its deployed.

**Comment by yongloon** [comment]
I think it is a problem when I integrate web3 in the react native.

Where can I get proper steps to install on react native?

**Comment by dev1644** [comment]
Using Web3 on React Native is a little bit tricky, web3 depends upon the crypto-js, it isn't available in Native Bundler so that's why the problem arises when importing web3 into React Native.

Below link is a step by step guide for importing web3 into React Native, it worked for some people.
https://gist.github.com/dougbacelar/29e60920d8fa1982535247563eb63766

**Comment by nivida** [comment]
Closed because of the ongoing clean up of the issue list. Feel free to ask this in our gitter channel or on stackoverflow.
