### ISSUE TITLE
Is there Inetrnal transaction function

### ISSUE THREAD

**Issue by shweta037** [ethereum/web3.js#2175]
Is there any function for internal transaction .How to do internal transaction using function...

**Comment by dev1644** [comment]
Internal transactions are the transaction that happened between contracts due to an external transaction.
Contracts are sometimes programmed to call another contract function if a called function changes the state of the callee contract then it is known as `Internal transaction`.

So Answering your question for doing internal transaction there should be an External Transaction.

I hope this helps you.

**Comment by dev1644** [comment]
@nivida I think we can close this issue now due to inactivity and I think answer has been provided.
