### ISSUE TITLE
web3 -- web worker environment isn't supported

### ISSUE THREAD

**Issue by 7-of-9** [ethereum/web3.js#2211]
Hi all,

Beta 34 (and/or its dependencies, e.g. any-promise) seems to have dependencies on "window" instead of "self" which prevents it working in a web worker context. I've not yet tested on later betas, but suspect they suffer from the same.

Related:  https://github.com/ethereum/web3.js/issues/1774
Related: https://ethereum.stackexchange.com/questions/56405/integrating-web3-from-metamask-in-react

**Comment by nivida** [comment]
This issue got solved in the version 1.0.0-beta.38 which I will release within the next days.

**Comment by 7-of-9** [comment]
@nivida fyi -- re. beta41: I'm seeing "window is not defined" when creating a  new Web3.providers.WebsocketProvider(...) inside A web worker context.

(< beta38 threw much earlier: at "import Web3...", so it's closer to working!)

UPDATE: `self.window = self`
In web worker before new WebsockProvider() seems to fix this.

Fix at source would be line 1162 of web3-provider-umd.js (beta41) - just remove "Window."

**Comment by naturalfreak** [comment]
same problem with version 1.2.4

**Comment by timothywangdev** [comment]
still broken

**Comment by keirongulrajani** [comment]
When I've tried `importScripts` in a Web Worker using `web3.js` instead of `web3.min.js` from the node module i can see the `window is not defined` error being thrown when `register-shim` is being loaded; this is a file inside `any-promise`, and the `any-promise` library is used by `web3-core-promievent` in the current version.

The `loadImplementation()` inside `register-shim.js` is attempting to grab `window.Promise` when there is no `window`:
```
/**
 * Browser specific loadImplementation.  Always uses `window.Promise`
 *
 * To register a custom implementation, must register with `Promise` option.
 */
function loadImplementation(){
  if(typeof window.Promise === 'undefined'){
    throw new Error("any-promise browser requires a polyfill or explicit registration"+
      " e.g: require('any-promise/register/bluebird')")
  }
  return {
    Promise: window.Promise,
    implementation: 'window.Promise'
  }
}
```

perhaps doing as it says to register a custom implementation with a `Promise` option is the solution?

EDIT: for those experiencing this issue with the window being undefined, I found a solution [here](https://stackoverflow.com/a/22160937/755370) about setting `window` as `self` first before the `importScripts` statements so that it has the correct environment (effectively tricking `any-promise` under the hood while loading to treat the worker as `window`:

```
var window = self;
importScripts(/*path to web 3 goes here*/);
```
