### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by levino** [ethereum/web3.js#2226]
From https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b

> The version 0.20.x is in maintenance mode since 19.04.2018 and just got security updates and smaller bug fixes. Because of the coming stable release of the library, I’ve deprecated version 0.20.x and recommend switching to version 1.0.0-x of the library if you have not already. Further details of the roadmap of the library are explained below.

So `1.0.0-beta.38` is prod ready then it should be released as `1.0.0`.

**Comment by nivida** [comment]
I never said the version 1.0.0-beta.38 is the stable release. 

The 0.20.x versions are deprecated and I recommend to change to version 1.0 because of the coming stable release in the next five months. I've deprecated the  0.20.x versions just to have more developers which are using the 1.0 version of this library. The higher usage of version 1.0 of this library will probably lead to a higher rate of daily created issues and this will help me to stabilize the 1.0 version until the final stable release of it.
