### ISSUE TITLE
web3-utils types not compatible with current @types/bn.js

### ISSUE THREAD

**Issue by sebastianst** [ethereum/web3.js#2290]
With `web3-utils 1.0.0-beta.41` and the current `@types/bn.js 4.11.4` `tsc` cannot transpile because the bn.js declaration doesn't have a default export. The following error is thrown
```
node_modules/web3-utils/types/index.d.ts:23:8 - error TS1192: Module '"/home/.../node_modules/@types/bn.js/index"' has no default export.

23 import BigNumber from 'bn.js';
          ~~~~~~~~~


Found 1 error.
```

**Comment by sebastianst** [comment]
It may be worth a try to use
```
/// <reference types="bn.js" />
```
instead, where `BN` is used in the web.js type declarations, and remove the definition of the `BN` class from web3-utils.

**Comment by joshstevens19** [comment]
Hey thanks for your issue!

This has been fixed in PR https://github.com/ethereum/web3.js/pull/2280/files

We have to require it else it doesn't work with strict mode (due to the `bn.js` typing's) so this was the best solution. 

This will be released in the next release (should be early next week). A temp fix is to run a `post-install` script which replaces this line: 

```import BigNumber from 'bn.js';``` > ```import BigNumber = require('bn.js');```

and install `@types/bn` locally which you can remove once the release comes out.

Thanks
