### ISSUE TITLE
web3.utils undefined

### ISSUE THREAD

**Issue by valkyriaivan** [ethereum/web3.js#2419]
#### Expected behavior
web.utils should be defined.

#### Actual behavior
When used any web3.utils function, it fails because web3.utils is undefined

#### Steps to reproduce the behavior

1. Download web3 1.0.0-beta.X
2. Try to use any function from utils.

#### Error Logs
`Cannot read property 'fromWei' of undefined.`
`Cannot read property 'hexToNumberString' of undefined.`
I saw some issues already here about specific functions, but in my case all the utils are undefined. I didn't upgrade the web3, just deleted and reinstalled.

#### Versions
Web3: I had 1.0.0-beta.36 installed and had to reinstall, then it stopped working, tested beta.34 and beta.35 with the same results
NPM: 6.7.0
Node: 8.15.0

**Comment by Freydal** [comment]
I found this or a similar issue has come up.  The outer Web3 object no longer has utils bound to it.  A web3 instance does.  I'm not sure if this change was an oversight.  In my newer code where a web3 instance wasn't needed I started using web3-utils, but I have old code that was relying on this.

**Comment by nivida** [comment]
This is true the static property got removed because if someone is just using the utils then you should probably use the ``web3-utils`` module directly instead of bundling the complete library. Will add this to the documentation. 
Btw.: The long term goal will be to remove the Web3 class and to create the [Web3 Namespace](https://gist.github.com/nivida/c7c24723353c243e295dbff954d06b50) but this will be done after the stable release.

**Comment by ayushnau** [comment]
@nivida then how do we get the balance of particular address because the web-eth is not containing the balance function.
it only contains two function that is 1. Eth2. TransactionSigner. when I try to use the function of balance it is giving not defined
