### ISSUE TITLE
Run in the browser without a bundler

### ISSUE THREAD

**Issue by lastmjs** [ethereum/web3.js#2475]
### Description 

I would like to run web3.js in the browser without using a bundler like rollup, webpack, or parcel. This used to be possible, but it looks like the `.min.js` distribution has been removed. That's fine I suppose, since there is an `esm` and a `umd` build...except that they don't work in the browser. I've been at this for a while, and I'm not inexperienced with modules and build processes. I'm trying to avoid bundlers, and I'm sure there are others like me. I don't think forcing webpack is a good idea, it's useful and a better DX to be able to load the library straight into the browser at times. The `esm` build has issues with Node.js dependencies that aren't easily ported to the browser. The `umd` build has issues with some of its dependencies as well...just load it in the browser from a static file server and you'll see what's happening.

#### Expected behavior

Load a current version of web3.js in the browser without a bundler or complicated build process.

#### Actual behavior

Can't load a current version of web3.js in the browser without a bundler, it just doesn't work using any of the distribution files.

#### Steps to reproduce the behavior

Restrict yourself to not using webpack, rollup, parcel, or similar tools, and try to load web3.js into the browser.

### Versions 
* web3.js: latest beta version
* nodejs: shouldn't matter
* browser: latest Chromium, shouldn't matter, latest browsers
* ethereum node: NA

**Comment by nivida** [comment]
>  That's fine I suppose, since there is an esm and a umd build...except that they don't work in the browser 

I'm always using webpack and I'm bundling the UMD files for the browser and it works without any problems.

> The esm build has issues with Node.js dependencies that aren't easily ported to the browser. The umd build has issues with some of its dependencies as well...

Yes, because I'm handling all external dependencies as external which is the correct way to build a library like Web3.
This allows Webpack and other bundlers to do better tree shaking and the user has also the possibility to overwrite specific dependencies Web3.js is using. The ESM build is for ES6 ready environments and NodeJS is currently not ES6 ready. The CJS bundles are for node environments, UMD for browsers, and ESM will be used from tools which are supporting ES6. If you want to test web3 without a bundler then use the CJS bundles in the Node environment and it will work.

**Comment by lastmjs** [comment]
The point of the issue was not addressed. Web3.js is forcing the developer
to use a bundler. I'm saying that Web3.js should not force the developer to
use a bundler. For example, I should be able to use a UMD build anywhere,
including the browser, without bundling it. But the UMD build does not work
in the browser as is.

Am I misunderstanding, or is it true that Web3.js cannot be used in the
browser without further processing by a bundler? If that's true, why take
that ability away? Not everyone wants to or should use something like
webpack.

**Comment by carsonwah** [comment]
So, ...Is `web3.min.js` permanantly gone?
