### ISSUE TITLE
filter.get() errors out with "invalid type on field : not a number or string"

### ISSUE THREAD

**Issue by caktux** [ethereum/web3.js#250]
```
Error: could not decode, invalid type on field : not a number or string
    at Object.module.exports.InvalidResponse (webpack:///./~/web3/lib/web3/errors.js?:35:16)
    at RequestManager.send (webpack:///./~/web3/lib/web3/requestmanager.js?:76:22)
    at Method.send (webpack:///./~/web3/lib/web3/method.js?:168:59)
    at Filter.get (webpack:///./~/web3/lib/web3/filter.js?:197:40)
```

since 0.6.0, same in 0.7.0 and develop, was working fine in 0.5.0

**Comment by frozeman** [comment]
Thats happen when you create a filter and chain `.get()` on the end.

As the filter id has not yet arrived at this time.
We should fix it or give a warning, but calling `.watch`, basically also gives you the past logs, so it maybe not necessary to chain it.

**Comment by caktux** [comment]
Makes sense, although I've got the filter in a `var` and calling `.get()` right after. I'll switch to `.watch` as it's a much better approach anyway.

**Comment by frozeman** [comment]
Yeah thats a problem, as creating filters is now async.

**Comment by debris** [comment]
@frozeman will you fix it?

**Comment by frozeman** [comment]
Thats not really possible as `.get()` would return immediately, while the filter id is not yet there.
So i would suggest throwing an error.

**Comment by itsnotlupus** [comment]
I'd vote for checking if a filter id is defined when .get is called and throwing a better error code at the user, something like ".get() called too early, filter id isn't set yet. Use watch() to process events asynchronously instead."

Baring that, users will google the obtuse error message they get now, and end up here, where they'll potentially leave more comments asking for a fix..

**Comment by frozeman** [comment]
Sounds like a good idea. Our error reporting have to improve a lot.

**Comment by bethnull** [comment]
Hi! I'm experiencing the same issue with contract events which I think in the end rely in filters for their functionality.

As you say .get() will return immediately, however I'm using a callback with .get and I'm having the same problem. Sometimes the callback has the issue error, other times has data, other no error and empty data, honestly quite weird. The worst is that in a nodejs session it usually works, but if executed within a script it rarely works.

Maybe I'm not understanding .get at all. It's supposed that when using .get with a callback it will return the full array of data/events, won't it?

Anyway, regarding the comments for fixing this issue, I think that throwing an error means that you'll later need to check it again, introducing in some way an active wait (due to the checking loop) and using watch for some applications is not an option. 

I say that watching maybe is not an option because I'm facing this situation, I need the full set of events related with a contract, and work with them as a whole, sending them to db, or to a client (all of them in one packet). With watch I don't know when I've received all of them and I thought that this what .get was for.

Regards, beth.

**Comment by frozeman** [comment]
internally we could make `.get()` callback get called after the filter id is present, even if you chain it. But there would still be a problem with using `var result = web3.eth.filter(..).get()`

**Comment by bethnull** [comment]
Hi frozeman, 

At least is a partial solution. If you want to use the sync version you must take into consideration the option of having an error back and in the other case use the async version and work asynchronously.

I think that for now is the best solution to the issue, I'll be glad to test it ;)

**Comment by frozeman** [comment]
sounds good.

**Comment by bethnull** [comment]
Hi again,

I've done some changes to the filter.js file that seems to work for the async case, leaving the synchronous one untouched.

Fabian, may I send a pull request of a fork? In that case in which branch I have to make the changes before summiting the commit? Otherwise I can send to you the modified file for reviewing.

Regards, beth.

**Comment by frozeman** [comment]
make a PR into develop please.
