### ISSUE TITLE
Web3() constructor no longer available

### ISSUE THREAD

**Issue by fireblockdev** [ethereum/web3.js#2573]
I'm looking for web3.js (1.0.0.beta50) & ganache-core. I see in many tests the use of Web3() to create an instance with a setProvider after. Is this syntax deprecated ?

**Comment by nivida** [comment]
The constructor is still available. We talked about this topic already in another issue and there is no use case to initiate the Web3 object without a provider. To be honest I think this was more a bug than a feature especially since the utils methods are a standalone npm package.

**Comment by fireblockdev** [comment]
When i use the Web3() empty constructor, there is an error:
```
/home/ellis/Documents/Others/fb-ganache-core/node_modules/web3-providers/dist/web3-providers.cjs.js:49
      if (provider.sendPayload && provider.subscribe) {
                   ^
TypeError: Cannot read property 'sendPayload' of undefined
    at ProviderResolver.resolve (/home/ellis/Documents/Others/fb-ganache-core/node_modules/web3-providers/dist/web3-providers.cjs.js:49:20)
    at Web3.AbstractWeb3Module (/home/ellis/Documents/Others/fb-ganache-core/node_modules/web3-core/dist/web3-core.cjs.js:24:51)
    at new Web3 (/home/ellis/Documents/Others/fb-ganache-core/node_modules/web3/dist/web3.cjs.js:30:68)

```
I can reproduce the error in browser and in node.

**Comment by PaulRBerg** [comment]
At AZTEC, we've been using the standalone `web3-eth-accounts` package to verify our custom secp256k1 module against web3 signatures: https://github.com/AztecProtocol/AZTEC/blob/master/packages/aztec.js/src/secp256k1/index.js#L240

Since I upgraded to web3@1.0.0-beta.50 on a local branch, I also get the `sendPayload` error, just like @fireblockdev. I understand that web3.js is designed to be connected to a provider, but I argue that standalone modules should be testable without an active Ethereum node.

## Update
Nevermind, it seems that I can run `web3EthAccounts.create()` even without a running provider. However, I do have to specify a dummy string:

```javascript
const web3EthAccounts = new Accounts('http://localhost:8545');
```
