### ISSUE TITLE
beta51 return broken BigNumber from contract methods

### ISSUE THREAD

**Issue by vshab** [ethereum/web3.js#2603]
### Description 

It is said that
>Instead of transforming numbers to string values do we return now the BigNumber object we get from the AbiCoder.

Seems like these BigNumber come from ethers.js which [enwraps BN's](https://github.com/ethers-io/ethers.js/blob/master/utils/bignumber.js) making it impossible to operate them in conjuncture with pure BN.

```js
import BN from 'bn.js';

// ...

const value = await myContract.methods.method.call();
const half = value.div(new BN(2)); //  <-- Throws here 
```

#### Expected behavior

Code above works

#### Actual behavior

The error is `Error: invalid BigNumber value (arg="value", value="2", version=4.0.27)`

### Versions 
* web3.js: 1.0.0-beta.51
* browser: Chrome 71
* ethereum node: Rinkeby

**Comment by nivida** [comment]
This is because the AbiCoder of ethers.js is returning his own BigNumber implementation.
The real solution would be if ethers.js and web3.js are moving to BigInt which is already implemented in chrome and as an experimental feature in Firefox. There is also a polyfill from google called JSBI.

I would really like to switch to BigInt and the JSBI polyfill.

I will talk to Richard from ethers.js if we can find a solution for both libraries which is also future proof.

Edit: 
I've also proposed the idea of using JSBI/BigInt here: https://github.com/ethereumjs/fixed-bn.js/issues/9

**Comment by vshab** [comment]
>The solution would be to move to the same BigNumber package ethers.js using.

In my opinion it's not the best solution - exporting some internal types. Then there should be some kind of typing for them, documentation and the way to instantiate in user code.

>But I would personally like to switch to BigInt and the JSBI polyfill. 

That's a good idea i think 👍
