### ISSUE TITLE
beta 51 doesn't work with vue-devtools

### ISSUE THREAD

**Issue by rstormsf** [ethereum/web3.js#2646]
![2019-04-04 00 25 34](https://user-images.githubusercontent.com/9360827/55537124-5a21c800-5670-11e9-9b62-cc7014fa59df.gif)

It's self explanatory in the gif

How to reproduce:
1. Initialize `nuxt.js` project
2. Install `vue-devtool` for chrome
3. Try to load vuex state in vue.js devtool extension

Works fine with beta-36 web3.js version

**Comment by nivida** [comment]
This isn't working because vue is adding properties to Web3.js related objects and Web3.js does detect this and throws an error. I will check if there is a possibility to fix this. 

In the near future will Web3.js restrict any addition or modification of a Web3 object. This because Web3.js will then have [SES](https://github.com/Agoric/SES) fully implemented.

Edit: [This](http://exploringjs.com/es6/ch_proxies.html#_revocable-references) could be interesting for you.

**Comment by rstormsf** [comment]
@nivida 
All I do is the following:

store.js
```js
import Web3 from 'web3'


const getters = {
  web3: (state, getters) => () => {
    const { rpcUrl } = getters.networkConfig
    return Object.freeze(new Web3(rpcUrl))
  },
}
```

I don't understand how I can fix it so the vue devtool don't attach anything to it

**Comment by rstormsf** [comment]
@nivida 
even with your recommendation it is still doesn't work

```js
import Web3 from 'web3'

function createRevocableReference(target) {
  const handler = {}
  const { proxy, revoke } = Proxy.revocable(target, handler)
  return { reference: proxy, revoke }
}

const getters = {

  web3: (state, getters) => () => {
    const { rpcUrl } = getters.networkConfig
    return createRevocableReference(new Web3(rpcUrl)).reference
  }
}

```

no issues with ethers.js ;-)

**Comment by nivida** [comment]
Yes, it doesn't work because Web3.js is restricting such stuff. We do here security sensitive stuff and ethers.js should probably also implement such strict restrictions. 

Edit: 
The revocable references are already partially implemented with Web3 you do not have to wrap them again. Exactly because of these revocable references does the vue devtool have problems.

**Comment by rstormsf** [comment]
so, what is the solution? How can I make it work with dev tools? Can I have a config option for dev-use to disable those restrictions, so I can develop with vue-devtools on localhost? 
@nivida 

I think a flag or extra option for those like me will help a lot.
