### ISSUE TITLE
Web3 Custom Provider

### ISSUE THREAD

**Issue by eduardonunesp** [ethereum/web3.js#2653]
I would like to know more about the `CustomProvider` I have created a provider that is considered as CustomProvider for the provider resolver (`return this.providersModuleFactory.createCustomProvider(provider);`), however the function signature for `send` doesn't make too much sense, because it expects `method: string`and `parameters: any[]`, but in my tests its acting like the old signature `payload: any` and `callback: Function`

#### Expected behavior
The function `send` for `CustomProvider` to work as the signature says

#### Actual behavior
Behaves different from the signatute, doing `payload: any` and `callback: Function`

### Versions 
* web3.js: `1.0-beta.52`
* nodejs: `11`
* ethereum node: `ganache`

**Comment by nivida** [comment]
Thanks for asking this question! 

The CustomProvider got implemented because of the backward compatibility with truffle and ganache products. Both of these products used an in-official API for customizing the behavior of Web3.js. 
The CustomProvider class is an internal class and shouldn't be used because it will get removed on the EIP-1193 roll-out day. 

If you would like to customize the transaction signing process then feel free to provide the ``transactionSigner`` option over the module options as described in the [documentation](https://web3js.readthedocs.io/en/1.0/web3.html#transactionsigner). If you would like to customize a specific method then you could create a custom Web3 Module. Unfortunately, I didn't have the time until now to finish the documentation for the Web3 Module API but I think the Eth module of Web3.js is a good example to show the possibilities of the Web3 Module API.

**Comment by eduardonunesp** [comment]
Thanks for your time @nivida another thing that I would like to ask is about [this line](https://github.com/ethereum/web3.js/blob/839283a6260cf96aec38bf76f0bbe8912e185b5f/packages/web3-providers/src/resolvers/ProviderResolver.js#L69), I think it kind of forces my provider to have the WebSocket connection, but if my provider is a HTTP only and I want to use the modern interface with the Promises ? any suggestion ?

**Comment by OFRBG** [comment]
@eduardonunesp if you are making an HTTP provider, `provider.subscribe` should be undefined. AFAIK you can't really implement a subscription over HTTP. Your provider would be created here: https://github.com/ethereum/web3.js/blob/839283a6260cf96aec38bf76f0bbe8912e185b5f/packages/web3-providers/src/resolvers/ProviderResolver.js#L85.

**Comment by levino** [comment]
It will be possible to "subscribe" with http2, right? https://developers.google.com/web/fundamentals/performance/http2/
