### ISSUE TITLE
Implementing of EIP-681

### ISSUE THREAD

**Issue by nivida** [ethereum/web3.js#2698]
### Description 

It should be possible to get a transaction in the described URL format of the [EIP-681](https://eips.ethereum.org/EIPS/eip-681).

#### Expected behavior

Possible implementation: 
``web3.eth.transactionUrl(...)``

### Versions 
* web3.js: latest

**Comment by sshelton76** [comment]
There is a significant flaw in EIP681 that could result in lost funds.  This flaw is that it assumes the transfer method which makes sense for person to person, but no business in their right mind is going to use that.  They will use a smart contract of some sort because they will want to track the incoming payment.

Therefore if the destination is a contract address instead of a user address (highly likely), funds could easily be lost since the transfer function doesn't notify the destination.  It would be far better to use approveAndCall semantics however it's a subject of debate.

Id advise against implementing anything like EIP681 directly in web3js at all.  This should be up to the individual wallet implementer to address.
