### ISSUE TITLE
contract.methods.myMethod().subscribe(txHash)

### ISSUE THREAD

**Issue by leonprou** [ethereum/web3.js#2716]
### Description

The idea is to subscribe to a sent transaction using the known `web3.eth.Contract` module. This will help to developers when they want to subscribe to a contract method that wasn't called from their Dapp. 

#### Expected behavior
Calling `contract.methods.myMethod().subscribe(txHash)` should return a `promiEvent`. Not signing is needed cause the transaction already sent.

#### Expected behavior
- [ ] Start with extending the [MethodsProxy](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-eth-contract/src/proxies/MethodsProxy.js)

### Versions 
* web3.js: latest

**Comment by sshelton76** [comment]
How the heck would they know the txhash if it didn't come from their DAPP?
I guess I can see a potential use case for an oracle, but someone needs to get that txhash to the oracle first.

Honestly we already have 
```
web3.eth.subscribe('pendingTransactions' [, callback]);
```

So if you're just waiting for an externally generated tx to complete you could just subscribe to that and filter by the txhash.

**Comment by leonprou** [comment]
@sshelton76 There can be multiple ways to receive the txhash.. In my case I want to gracefully handle user refreshing the screen. I save the transaction hash in the application storage, and on user refresh I want to proceed with the existing flow of handling transactions. So, what I suggested seems to be an elegant solution to my problem.

If you see the sending transactions as two parts: sending it and then watching until it completes. Here I want just a second part.

There's other solutions, but they got an issue not receiving the `events` from the receipt. Wrote about that here: https://github.com/ethereum/web3.js/issues/2634

**Comment by nivida** [comment]
The [TransactionObserver](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-core-method/src/observers/TransactionObserver.js) does watch the transaction and counts the confirmations. 
We would have to extend the ``TransactionObserver`` with the functionality to check past blocks because it could be that a new block got mined during the reload. Additionally, would we have to extend the ``observe`` method to pass the number of confirmations which already happened. The fun part will be to handle a chain re-organization also when the page got reloaded. 

Edit: 

I wouldn't add this to the contract methods proxy. I think it would be better to have this as a method on the eth module e.g.: 
``web3.eth.watchTransaction(hash,  fromBlock?, confirmations?, timeout?).subscribe(...);``
 or
``web3.eth.transaction.watch(...).subscribe(...)``

**Comment by sshelton76** [comment]
This feels to me like something that would be handled better using existing functionality.  I'm not seeing the need to extend web3js to handle it because it's implementation specific.

Perhaps cache pending transaction hashes into local storage and then on refresh check the status of the tx in a polling timer?

**Comment by tomasNajun** [comment]
@nivida I would like to use the TransactionObserver to solve the next use case: I sign and broadcast a transaction using Metamask, which just returns the txHash. Then, I send that txHash to a backend process. There I want to observe when the transaction is confirmed and handle the logs or the error. Similarly to what this function does [execute in AbstractObservedTransactionMethod.js](https://github.com/ethereum/web3.js/blob/6fb8c14721dee746b4d329cf21606630f05da170/packages/web3-core-method/lib/methods/transaction/AbstractObservedTransactionMethod.js#L62)
How can I do it with actual web3js exposed functions?
