### ISSUE TITLE
transaction receipt of sendSignedTransaction does not include events 

### ISSUE THREAD

**Issue by jtlacci** [ethereum/web3.js#2728]
### Description 

In the transaction receipt of `web3.eth.sendSignedTransaction()` the receipt do not include events

#### Expected behavior

On a transaction that emits events 
Calling `web3.eth.sendSignedTransaction()` should return:
```js
events:
  { ProposalCreated:
    { logIndex: 0,
      transactionIndex: 0,
      transactionHash:'0x655e63b7324ba8cbd07a8a8b242a69f0c0c2bd94fac671890e182e59457946b5',
      blockHash:'0x1544919d9c3f3f1e6aee0358b638cbb7bce36a383d53c8482fe49b86492b50f2,
      blockNumber: 343,
      address: '0x87Bd32cF6E7e4CeE8c44852F3e9a5BF27f11aB8D',
      type: 'mined',
      id:'log_0xfc180d3daaa4f34acb78d7366dae4b3b0327212980d0d329d45acb6f10b669fc',
      returnValues: [Object],
      event: 'ProposalCreated',
      signature: '0x488fccde177d9377f35d8d9a4f0b3462fcc7cdb926a00d3d99630ef1d672a2cd',
      raw: [Object] 
    } 
  } 
```

#### Actual behavior

On a transaction that emits events 
Calling `web3.eth.sendSignedTransaction()` returns:

```js
logs:
  [
    {
      logIndex: 0,
      transactionIndex: 0,
      transactionHash:
      '0x9da85b840c356fa28a80cfd097e3db5bff50eec2c4057e5aaf0d7adc91a80634',
      blockHash:
      '0x31f663edaaca6060133dbdf64bfab0630971c6a7c5a180ee347671b982b9cfd2',
      blockNumber: 339,
      address: '0x87Bd32cF6E7e4CeE8c44852F3e9a5BF27f11aB8D',
      data:
      '0x0000000000000000000000009010f57306ce63789789458278a431f2a38cb65d',
      topics: [Array],
      type: 'mined',
      id:
      'log_0xea2269340858264006651a26e41bc81efbf7d897ab5b9e2856fd95ef429115eb'
    }
  ]
```

#### Steps to reproduce the behavior

Send a event emitting transaction using `web3.eth.sendSignedTransaction()`

### Versions 
* web3.js: "1.0.0-beta.48"
* nodejs: "v8.11.13"
* browser: n/a
* ethereum node: ganache-cli v6.4.3

**Comment by nivida** [comment]
The method ``eth.sendSignedTransaction`` can't return named events because the method doesn't know about the contract ABI. With the unlocking of an account in the local Web3.js wallet will every transaction signed locally when you send a transaction.

I would recommend you to use the eth-contract module as described [here](https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html) and to add an unlocked account to the Web3.js wallet. 

If you would like to customize the transaction signing process then feel free to create your own custom [``TransactionSigner``](https://web3js.readthedocs.io/en/1.0/web3-eth.html#transactionsigner).

**Comment by nivida** [comment]
Closed because of the given answer.
