### ISSUE TITLE
PromiEvent improvement

### ISSUE THREAD

**Issue by nivida** [ethereum/web3.js#2742]
### Description 

The idea is to implement the possibility to use Observables for subscribing to the transaction confirmation workflow. 

The goal would be to rename the ``PromiEvent`` to ``Output`` and to implement the [Observable](https://github.com/tc39/proposal-observable) proposal. 

``` javascript
interface Output {
  subscribe({next: Function, error: Function, complete: Function}): Observable;
  unsubscribe();
  then(): Promise;
  catch(): Promise;
  on(): EventEmitter;
  once(): EventEmitter;
}
```

#### Expected behavior

``` javascript 
contract.methods.method().send().subscribe() 
contract.methods.method().send().on()
contract.methods.method().send().then() 
```

#### Actual behavior

``` javascript 
contract.methods.method().send().on()
contract.methods.method().send().then()
```

**Comment by sshelton76** [comment]
I like the concept of being able to subscribe and unsubscribe to emitted events.
However this proposal is a bad idea because it makes web3 dependent on reactjs, unless there is something I'm missing.

*update*
I see you linked in the TC39 recommendation.  However the Observable proposal was rejected, so if we went with Observables we'd either have to roll our own, or effectively marry ourselves to react.

**Comment by nivida** [comment]
> I see you linked in the TC39 recommendation. However the Observable proposal was rejected, so if we went with Observables we'd either have to roll our own, or effectively marry ourselves to react.

We can use the [RxJs Observable](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html) class or we implement our own Observable object but React isn't required for this.

**Comment by sshelton76** [comment]
I'd recommend we roll our own if you're serious about it.

**Comment by nivida** [comment]
Closed because it is a bad idea to handle all possible types of return interfaces over one object.
