### ISSUE TITLE
Is web3 always in beta?

### ISSUE THREAD

**Issue by YoonjaeYoo** [ethereum/web3.js#2830]
### Description
1.0.0 has been in beta stage for more than 2 years. Is it normal?

#### Expected behavior
There even are breaking changes while in beta and its version goes up to 55.
I've never seen any project like this before.

#### Actual behavior
"Beta" had to be removed long before now, I guess..?

#### Steps to reproduce the behavior
1. Click 'Releases' tab on https://github.com/ethereum/web3.js
2. Click 'Tags' tab
3. Count how many v1.0.0-beta.XX was and how old the first beta was
4. Endless betas...
5. First one was v1.0.0-beta.8 on 24 Jul 2017

#### Conclusion
In my opinion, the official js library for ethereum, web3, needs to get rid of beta and get improved now.
Otherwise, people will look for other options such as ethers.js, ..

**Comment by nivida** [comment]
Thanks for opening this issue. I‘ve overtook the project some months ago and improved the internal architecture. You will see the difference of the architecture if you switch from beta.37 to the beta.55 tag. I‘m currently in contact with truffle, OpenZeppelin, Buidler, Embark, and many more to define the 1.0 stable release they require. Because these projects were using unofficial APIs do we have the problem currently that they can’t update to the latest version. We will probably define beta.37 as 1.0 and the latest version of Web3 as 2.0-beta.1.
