### ISSUE TITLE
Transaction to sidechain without a chainId fails with unclear error 

### ISSUE THREAD

**Issue by leonprou** [ethereum/web3.js#2873]
### Description 
Sending transactions to our sidechain without the chainId should work or return a correct error message.

#### Expected behavior
`contract.method.myMethod().send({from, gas})` when the defined provider is http://rpc.fuse.io/ returns:
```
Error: Node error: {"code":-32601,"message":"Method not found"}
```

#### Actual behavior
Should return an error message like: "chainId isn't defined".

### Versions 
* web3.js: 1.0.0-beta.55
* nodejs: v8.9.4
* browser: backend
* ethereum node: parity

**Comment by nivida** [comment]
If the transaction doesn't get signed locally will we send the ``eth_sendTransaction`` method with the correct data property defined. If this is the case then the ``eth_sendTransaction`` method isn't enabled on your node. Does the transaction get signed locally and you don't pass the chain ID then we will use the ``eth_chainId`` JSON-RPC method for detecting the correct chain ID. The ``eth_chainId`` JSON-RPC method got implemented in Geth and Parity as you can see in [EIP-695](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-695.md). I've informed the Ganache team about the new ``eth_chainId`` method some months ago and I think they have implemented it.

But yes I could improve the returned errors for giving some more details of what exactly is failing. We have already some issues about the improvement of the error handling. (https://github.com/ethereum/web3.js/issues/1543)

I'm closing this issue because there are already similar issues.

**Comment by leonprou** [comment]
Yeah I see you're right. You do call `eth_chainId` method but the Parity node responses with `Method not found`.

Hope that error messages will clearer some day)
