### ISSUE TITLE
Transaction speed decrease between beta34 and ^beta38 

### ISSUE THREAD

**Issue by agomezlyte** [ethereum/web3.js#2896]
Hi!

Recently, my partner and me updated web3 from beta34, we've being using this version for a long time, to the latest version, beta55 at that moment. 
We decided to try the newer version available since we didn't updated for a long time. After this update we experienced a big transaction speed drop. Almost 40% slower than version beta34 when calling get functions, and around 50%-60% when calling set functions.

We decided to try an older version, beta38 in this case, and the speed issues where still there. Finally we downgraded again to beta35 and speed went back to normal. We did some testing and we realized that speed drop started with version 1.0.0-beta38, all the way up to beta55.

No code changed between updates or downgrades but imports because of the new typescript types coming from beta38.

Is this a known issue? Why does the transaction speed have dropped so much?

**Comment by nivida** [comment]
Version beta.36 implemented the new ABI coder from ethers.js and we refactored the internal architecture with the release of beta.38 to maintainable and extendable code. The usage of the ES6 Proxy is also slightly slowing down the method calls. These performance decreasons will get improved in version 2.0 of Web3.js. 

Because many tools where relying on the internal architecture of Web3.js did we decide to define beta.37 as 1.0 and to use the new architecture (beta.38<) for 2.0. Splitting the old and new architecture in two versions will give us some new freedom to improve the Web3.js library. 

I've closed this issue because it's a open point of the 2.0 planning phase.
