### ISSUE TITLE
Default branch is 2.x now... Is it as expected?

### ISSUE THREAD

**Issue by marsrobertson** [ethereum/web3.js#2899]
https://github.com/ethereum/web3.js/releases 

![image](https://user-images.githubusercontent.com/44369284/59668063-bf854f80-91af-11e9-9d40-b0b76bc83059.png)

**Comment by nivida** [comment]
Yes, this is as expected :) 

I will publish a Medium blog post this week to explain the new branching and the next steps of the project.

**Comment by marsrobertson** [comment]
Okay... I found it really confusing. Not a single stable `1.x` release and already moving to `2.x`... A lot of projects using `0.20.x` due to various instabilities.

Tricky business all the way.

**Comment by nivida** [comment]
Yes, I see your point. In short: beta.37 gets released as 1.0 because many projects were relying on the internal architecture of Web3. beta.55 < will be used for version 2.x which gives us some additional freedom to improve the Web3 project. Any further details are already written down and will be published this week.

**Comment by marsrobertson** [comment]
Great stuff, looking forward to it!

I remember some recent discussions about various beta versions: https://github.com/ethereum/web3.js/issues/2077#issuecomment-490027735

You are the chief cat herder of a pretty giant mess :)
