### ISSUE TITLE
sendSignedTransaction never close websocket connection [1.2]

### ISSUE THREAD

**Issue by stefdelec** [ethereum/web3.js#3094]
### Description 

When i call on sendSignedTransaction on nodejs, node process never ends because it seems that websocket connection is actually never closed. 
It may lead to memory leak on server side.

#### Expected behavior

```
web3.eth.sendSignedTransaction(result.rawTransaction)
                    .on("confirmation", (confirmationNumber, receipt) => {
                        //do something
                    })
```

Expected behavior : To close websocketConnection, if I need only 'confirmation' event.

#### Steps to reproduce the behavior
 

Launch nodejs process and see it never ends.

 ```js

      web3.eth.sendSignedTransaction(result.rawTransaction)
                    .on("confirmation", (confirmationNumber, receipt) => {
                    // do something
                    })

    
```

### Versions 
* web3.js: 1.2.1
* nodejs: 10

**Comment by cgewecke** [comment]
@stefdelec Hi. You might be looking for `once` instead of `on`. This will fire a single time on the first confirmation. 
```javascript
web3.eth.sendSignedTransaction(result.rawTransaction)
  .once("confirmation", (confirmationNumber, receipt) => {
     // do something
  })
```


In 1.2x, when you attach the confirmations handler using `on`, it will fire for 24 confirmations. To stop listening you have to remove the listener following the [Node EventEmitter API](https://nodejs.org/api/events.html#events_emitter_removelistener_eventname_listener).

Closing - the web3 docs are reasonably clear about [how PromiEvents work & what they are](https://web3js.readthedocs.io/en/v1.2.1/callbacks-promises-events.html#callbacks-promises-events).

**Comment by stefdelec** [comment]
Same behavior with `once`. It does not close the websocket.

**Comment by cgewecke** [comment]
@stefdelec 
Are you sure that the transaction is being mined? When you attach the `receipt` listener do you get a receipt?

If you're connecting to Ropsten could you look at #3104 and [this comment](https://github.com/ethereum/web3.js/issues/3104#issuecomment-539257013) to make sure that you're signing the transaction correctly for the Istanbul fork?

**Comment by nivida** [comment]
The websocket connection stays established for the whole time. Otherwise we would have to connect and disconnect on each request. The wished behavior would also force us to re-establish subscriptions all the time.
