### ISSUE TITLE
web3.eth.getStorageAt location can be BN?

### ISSUE THREAD

**Issue by taobun** [ethereum/web3.js#3100]
#### Description
I tried to get value from mapping in smart contract, so by convention I tried to hash key and slot together to get location for call `getStorageAt` function. However signature of `getStorageAt` receive number as location, but hash value is too big to cast to number, so I cannot get storage in mapping by using web3.js. 

#### Expected behavior
```
const mapBase = new BN(
   web3.utils.soliditySha3(
      { type: 'address', value: dataSource },
      { type: 'uint256', value: '1' },
   ),
)
web3.eth.getStorageAt(this.tcdAddress, newLocation)
```

#### Actual behavior
This code can't compile and if I casted it to number, It doesn't work.

### Versions 
* web3.js: 1.0.0-beta.52

**Comment by cgewecke** [comment]
Some notes for a fix on 1.x (2.x is similar):  

Believe underlying problem is that the BN value is passed to [utils.hexToNumber](https://github.com/ethereum/web3.js/blob/1.x/packages/web3-utils/src/utils.js#L234) for [input formatting](https://github.com/ethereum/web3.js/blob/1.x/packages/web3-eth/src/index.js#L244-L248). 

See [utils.toHex](https://github.com/ethereum/web3.js/blob/2.x/packages/web3-utils/src/Utils.js#L396-L420) for a possible alternative format.

**Comment by nivida** [comment]
You are able to bass the BN or BigNumber object to the second parameter of the ``getStorageAt`` location as documented [here](https://web3js.readthedocs.io/en/v1.2.4/web3-eth.html#getstorageat).

@cgewecke The position parameter will be passed to the ``utils.numberToHex`` method which does accept the following types: numbers, string numbers, hex strings, BN, and BigNumber.
