### ISSUE TITLE
getPastEvents on localhost is not a function 

### ISSUE THREAD

**Issue by bayanhd** [ethereum/web3.js#3149]
Now, I'm working on an Ethereum Blockchain project to transfer the ownership of stored devices by using local web3 provider HTTP://127.0.0.1:7545 at the truffle environment.
Truffle v5.0.27 (core: 5.0.27)
Solidity v0.5.0 (solc-js)
Node v10.15.3
Web3.js v1.0.0-beta.37
and lastest version of metamask

**Browser details

    OS: [Windows 10]
    Browser tried both [firefox, chrome]
    MetaMask Version [7.0.1]

Hence, I'm attempting to query all past events that a contract has ever emitted by using the following code

```
 App.contracts.DeviceManager.deployed().then(function(instance) {
    DeviceManagerContractInstance= instance;
    DeviceManagerContractInstance.getPastEvents('allEvents',
    { fromBlock: 0, toBlock: 'latest' })
  
    .then(events => console.log("events:",events))
    .catch((err) => console.error("err",err));
     })

```

but I was getting this error

> TypeError: DeviceManagerContractInstance.getPastEvents is not a function

Also, I tried to use allEvents()
```
    DeviceManagerContractInstance.events.allEvents()
.on('data', (event) => {
	console.log(event);
})
.on('error', console.error);
```
However, it's throwing the same error.
 
I don't know what is missing,  and if the problem belongs to localhost or, code syntax.

Any Idea,

**Comment by cgewecke** [comment]
Hi @bayanhd 

The problem you're having looks Truffle related. They wrap web3 with their own API. You can find a working example of Truffle's `getPastEvents` [in their unit tests, here](https://github.com/trufflesuite/truffle/blob/develop/packages/contract/test/events.js#L134-L159).

An example of `getPastEvents` at web3 1.x can be seen [in web3's unit tests, here](https://github.com/trufflesuite/truffle/blob/develop/packages/contract/test/events.js#L134-L159).

The only known issue with that method is that it's a little flaky using geth --dev insta-mining over websockets. It should work fine with ganache, geth over http, or any public network over ws/http.

Closing because n/a. Please ping if you discover this *is* web3 related.
