### ISSUE TITLE
Would like to execute only sendSignedTransaction without getTransactionReceipt

### ISSUE THREAD

**Issue by usd-yamazaki** [ethereum/web3.js#3204]
I am running a lot of sendSignedTransaction to measure the performance of private ethereum.
However, because sendSignedTransaction automatically calls getTransactionReceipt, it puts extra load on the node.
For the tests I want to do, getTransactionReceipt need only be executed once at the end.
So, could you give sendSignedTransaction an option not to execute getTransactionReceipt?

Thank you.

**Comment by lautarodragan** [comment]
Another (small & very low priority) case in favour of this feature:

The application I'm working tries to avoid storing state in RAM as much as possible, relying on an external DB instead. The way it's built allows it to be restarted anytime, it just picks up where it left off, without any complicated code and without risk of being left in a "weird state", so to speak.

`Method._confirmTransaction` (or the `SocketTransactionObserver` and `HttpTransactionObserver` `observe` method in 2.x) seems to subscribe to `newHeads` and calculate the confirmations whenever a new head arrives.

In my case the issue with this is that if the application is restarted, this subscription is closed and it'll no longer receive confirmations.

To achieve this restart-just-works I'll probably write a similar system to the one web3 uses internally, periodically requesting transaction receipts for every transaction in the database that still doesn't have one, and just ignore the PromiEvent returned by `sendSignedTransaction`. So there's a tiny bit of wasted resources in those unused subscriptions.

Just thinking out loud, but maybe `AbstractObservedTransactionMethod` could be renamed to `Observable` (instead of `Observed`) and have `execute` only condicionally call `const transactionConfirmationSubscription = this.transactionObserver.observe(transactionHash).subscribe(...)`? No idea how to wire that everywhere else though.

**Comment by lautarodragan** [comment]
Not stale

**Comment by ishanjain28** [comment]
not stale
