### ISSUE TITLE
web3.min.js is broken in 1.2.3 and 1.2.4

### ISSUE THREAD

**Issue by PaterSantyago** [ethereum/web3.js#3222]
web3.min.js from dist folder are broken in versions 1.2.3 and 1.2.4.

Google Chrome (78.0.3904.108) on Mac OS produces "require is not defined at web3.min.js:1" error.

Everything work fine with 1.2.2

Also, I'm getting same error for 1.2.3 and 1.2.4 if I build web3.min.js with `npm run-script build`

**Comment by nivida** [comment]
Thanks for opening this issue! The minified file was only existing for version 1.2.2 because we had defined the browser property to point on the minified dist files. This browser property got removed because it blocked some projects from bundling their apps in an optimized way.
I'm currently improving the whole build pipeline of web3.js with PR https://github.com/ethereum/web3.js/pull/3160 this PR will define the unpkg and jsdelivr property in the package.json file of each package of web3.

**Comment by nivida** [comment]
> Also, I'm getting same error for 1.2.3 and 1.2.4 if I build web3.min.js with npm run-script build

Sorry I've forgotten to answer this. You would have to run ``npm run build-all`` but the minified file is existing in the web3 package dist folder.

**Comment by DurandA** [comment]
@nivida I have the same issue with [_dist/web3.min.js_ from 1.2.4](https://github.com/ethereum/web3.js/blob/1.x/dist/web3.min.js) or built from 1.x branch. Is there any place I can get a clean version working in the browser until this is fixed?

**Comment by munawarb** [comment]
Hi @DurandA,
You can just grab web3.min.js from web3 1.2.2. So in my project I'm using 1.2.4 on the Node side and 1.2.2 on the browser side. This works. I'm glad I found your issue, I wondering for the longest time why web3.min.js was throwing the error and thought I was going crazy when no one else seemed to be having this problem :).

**Comment by jerryji** [comment]
But why are the web3.min.js in 1.2.3 and 1.2.4 release still not fixed?

**Comment by munawarb** [comment]
Hi @DurandA,
Not sure, but downgrading to 1.2.2 on the browser side will work fine. You'll just need to include the polyfill.min.js file mentioned in #3155.

**Comment by simassimonas** [comment]
@munawarb @nivida  for some reason I can't install any earlier version than the 1.2.4 
am I the only one having this issue?
