### ISSUE TITLE
No error messages are currently displayed for improper use of .call() and .send() 

### ISSUE THREAD

**Issue by edsonayllon** [ethereum/web3.js#3258]
#### Expected behavior

For a contract method writing a transaction, such as a payable function, using `call()` instead of `send()` should display an error or warning.

For a contract method only reading the state of smart contract information, using `send()` instead of `call()` should display an error or warning.

#### Actual behavior

No warnings or errors are displayed in these situations.

#### Steps to reproduce the behavior

1. Initiate a contract instance
2. Perform `.call()` on a method requiring `.send()` or `.send()` on a method requiring `.call()`

#### Versions
[NPM, Node, Web3.js, OS, device...]

Latest stable Web3. LTS Node, NPM. MacOS, latest stable Chrome with latest stable Metamask.

**Comment by nivida** [comment]
Thanks for opening this issue!
You should be able to call a payable contract function with ``call()`` because you probably would like to have a dry run first and to handle the revert instruction if existing. The next release of web3.js will include the revert instruction handling and it can get activated with defining of ``handleRevert`` to ``true``.
