### ISSUE TITLE
A possible strategy to reduce bundle sizes

### ISSUE THREAD

**Issue by alcuadrado** [ethereum/web3.js#3267]
Web3.js' bundle sizes are incredibly big, and we constantly receive complaints about this. This needs to be addressed. I'm creating this issue to discuss how.

I believe the bundles get this big for these reasons, which were already present when the current contributors joined.

1. The library isn't designed in a bundler-friendly way. More concretely, the library exposes its functionality in a way that forces you to include most of its code just to use parts of it. For example, the `web3` object is mostly used to access `web3.eth`, and it always imports `bzz` stuff.

2. The library isn't coded with modern bundlers in mind, preventing many optimizations. For example, it imports entire dependencies (e.g. `const _ = require("underscore")`) just to use a few of its functions.

3. The project uses outdated and poorly configured tools.

4. This project uses lots of unnecessary and low-quality dependencies. Installing `web3` in an empty npm project installs 341 dependencies, including completely unrelated things like `express`. There are even dependencies that are installed and not used, like `got` in `web3-bzz`. Luckily, not all of them end up in production bundles, but this shows how little care was given to dependencies management in this project.

I think this is a possible way of improving on all of these fronts:

* Only focus on (2) and (4) for now. I'd do these:

   * Every dependency that isn't actually needed should be removed. For example, `underscore` is not needed and berly used, but we are bundling it anyway.

   * If multiple dependencies provide the same functionality only use one of them, and remove the others. There's a lot of duplication between things like `ethereumjs-*`, `ethers` and `eth-lib`.

   * Low-quality dependencies should be removed. Even if this implies taking ownership or reimplementing parts of it. @cgewecke already did some of this in #3262 

   * Detect inefficient imports, like `const _ = require("underscore")` and change them to tree-shakable equivalents.

   * Detect libraries that can't be deduped and solve that. Again, Chris started this in #3262 

* Once the project dependencies are in a better state, update the tooling.

* Improving (1) means breaking changes. Each possible improvement should be documented with an issue, and its tradeoffs should be discussed individually, including community feedback. 

What do you think @nivida and @cgewecke ?

**Comment by nivida** [comment]
@alcuadrado Thanks for listing all the points we have to improve! 

> The library isn't designed in a bundler-friendly way. More concretely, the library exposes its functionality in a way that forces you to include most of its code just to use parts of it. For example, the web3 object is mostly used to access web3.eth, and it always imports bzz stuff.

This will get improved with version 2.0 of web3.js and exposing of a purely functional API.

> The library isn't coded with modern bundlers in mind, preventing many optimizations. For example, it imports entire dependencies (e.g. const _ = require("underscore")) just to use a few of its functions.

This could get improved by introducing the ES module structure. (a PR with the ES module structure applied is existing)

> The project uses outdated and poorly configured tools.

This is something we and especially @cgewecke started to improve and we focus currently on extending the test suite.

> There are even dependencies that are installed and not used, like got in web3-bzz.

The web3-bzz would require to get refactored at all and we should remove the un-maintained swarm-js dependency with an alternative listed by the swarm team. (Because this would definitely introduce some breaking changes should we do this in version 2.0)

> Once the project dependencies are in a better state, update the tooling.

What exactly do you mean by this point? 

> Improving (1) means breaking changes.

I think it will be possible to do it in a non-breaking manner but probably we are forced to accept some points we can't improve.

> This project uses lots of unnecessary and low-quality dependencies.

Those old and in the meantime un-maintained dependencies should be replaced if possible with functions provided from ethers to lower the duplications between those two projects as well.

> What do you think @nivida and @cgewecke ?

It will slow down the process on 1.0 but will improve the bundle size and the dependency situation at all. 👌

**Comment by nivida** [comment]
> I believe the bundles get this big for these reasons, which were already present when the current contributors joined.

The issue we have are non-dynamic versions defined in dependencies of our sub-packages. This is the reason for those duplicated dependencies when bundling with any known bundler.

**Comment by cgewecke** [comment]
Not stale

**Comment by Tedko** [comment]
hi - any update on this one>?

**Comment by GregTheGreek** [comment]
Update:

After discussions with the Swarm team we are removing bzz support #3746
