### ISSUE TITLE
update scrypt shim using maxmem fix from node >= 12.8

### ISSUE THREAD

**Issue by sidhujag** [ethereum/web3.js#3284]
referencing https://github.com/web3-js/scrypt-shim/issues/3 can we update scrypt-shim so that it uses maxmem fallback (built-in scrypt) starting from node >= 12.8?

**Comment by michaelsbradleyjr** [comment]
The situation is a little weirder than that.

For Node `<= 12.0.0` it could still be valid to install the old scrypt package. Note also that the maxmem change was backported into Node 10.x as of 10.17.0 (see the [release notes](https://github.com/nodejs/node/releases/tag/v10.17.0)).

It turns out that the maxmem thing won't prevent a blow-up with some scrypt parameters that are found e.g. in go-ethereum's (geth) and web3's test suites. That's because golang's scrypt isn't compliant with the RFC for scrypt whlie Node's is:

https://github.com/golang/go/issues/33703
https://github.com/ethereum/wiki/issues/674
https://github.com/ethereum/go-ethereum/issues/19977
https://github.com/nodejs/node/pull/28799#issuecomment-522218172

So, if someone using Node wanted to be able to process the exact same set of scrypt parameters that's possible with golang (e.g. with geth) then they'd either need to use a non-compliant pure JS implementation or the old scrypt package (and in the latter case they'd need to be using Node `<= 12.0.0`).

One thing that web3 should probably do is remove its wallet test cases that have the non-compliant parameters.

**Comment by sidhujag** [comment]
@michaelsbradleyjr for path of least resistance there already is code that is around when maxmem is fixed (12.8), so I suggested to use that just uncomment and set the variable to 12.8. I didn't know tests still broke, so is 53 bits not enough for all cases or is it a bad test?

**Comment by michaelsbradleyjr** [comment]
You've misunderstood. Please follow the trail of links I included in my last comment, they're ordered with respect to the dates I posted those issues, newest at the top. While the maxmem bump is a nice feature, it's ultimately a [red herring](https://en.wikipedia.org/wiki/Red_herring).

**Comment by michaelsbradleyjr** [comment]
For tests to pass on this project's `1.x` branch with Node's built-in scrypt, the wallet test cases that replicate geth's non-RFC-compliant scrypt test cases will need to be removed.

**Comment by sidhujag** [comment]
> For tests to pass on this project's `1.x` branch [with Node's built-in scrypt], the wallet test cases that replicate geth's non-RFC-compliant scrypt test cases will need to be removed from this repo.

thx what a mess. Hopefully we can get it back on track and remove the dependency, ultimately that is my goal.

**Comment by cgewecke** [comment]
Believe this was resolved by #3536. Please ping if that's not the case.
