### ISSUE TITLE
aes-(192|256)-* are not supported when encrypting wallet to keyStore or decrypting keyStore back to wallet

### ISSUE THREAD

**Issue by atom-yang** [ethereum/web3.js#3324]
#### Expected behavior

wallet can be encrypted to keyStore with `aes-256-ctr` algorithm

#### Actual behavior

`browserify-cipher` throw an error:

```bash
Error: Invalid key length
    at Cipheriv.createCipherBase (internal/crypto/cipher.js:79:18)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:115:20)
    at new Cipheriv (internal/crypto/cipher.js:217:22)
    at Object.createCipheriv (crypto.js:109:10)
    at Accounts.encrypt (/Users/young/Documents/eth/web3.js/node_modules/web3-eth-accounts/src/index.js:406:23)
    at Object.encrypt (/Users/young/Documents/eth/web3.js/node_modules/web3-eth-accounts/src/index.js:112:22)
```

#### Steps to reproduce the behavior

with the code 

```javascript
const Web3 = require('web3');
const web3 = new Web3(Web3.givenProvider || "ws://localhost:8545");
const wallet = web3.eth.accounts.create();
wallet.encrypt('12345678', {cipher: 'aes-256-ctr'})
```

#### Versions
Node: 10.16.0
System: macos
![image](https://user-images.githubusercontent.com/52150262/72801091-c31c1000-3c83-11ea-8f29-b8642043df17.png)

#### Reasons
1. in this [file](https://github.com/ethereum/web3.js/blob/1.x/packages/web3-eth-accounts/src/index.js#L414), the cipher key length has been limited in 16, it should be 32 if cipher is `aes-256-ctr`

**Comment by cgewecke** [comment]
Hi @atom-yang.

Leaving some initial triage notes here:
+ Web3 and Ethers appear to only have test cases for aes-128.
+ [browserify-aes][1] has fixtures / data for a wider range. 
+  ethereum/js-ethereum-cryptography has an [AES module][2] and there's a proposal to migrate there from crypto-browserify, once the package's stability warning is removed.

Seems like at the moment web3 might only support:
+ aes-128-ecb
+ aes-128-cbc
+ aes-128-ctr
+ aes-128-cfb8

e.g the option makes sense but the higher number variants are not being handled correctly. (Non-ctr variants need to be checked).

@atom-yang Out of curiosity, could you discuss why you would prefer to encrypt with aes-256 instead of aes-128?

**Other resources**
[Simple AES overview][3]

[1]: https://github.com/crypto-browserify/browserify-aes
[2]: https://github.com/ethereum/js-ethereum-cryptography#aes-submodule
[3]: https://proprivacy.com/guides/aes-encryption

**Comment by nivida** [comment]
@cgewecke 
> @atom-yang Out of curiosity, could you discuss why you would prefer to encrypt with aes-256 instead of aes-128?

I think we should definitely give our consumers the possibility to use the highest possible AES key length.  I would also prefer to use the longer key (14 instead of 12 or 10 iterations is quite a difference) if possible.

> the option makes sense but the higher number variants are not being handled correctly. (Non-ctr variants need to be checked).

Let us extend those test cases with all possible block/stream ciphers variants. 👌 

> ethereum/js-ethereum-cryptography has an AES module and there's a proposal to migrate there from crypto-browserify, once the package's stability warning is removed.

I've asked @alcuadrado about the current state of the on-going security audit and will drop a comment here as soon as I know more.

**Comment by nivida** [comment]
> I've asked alcuadrado about the current state of the on-going security audit and will drop a comment here as soon as I know more.

@cgewecke Because [Trail of Bits](https://www.trailofbits.com/) is fully booked will the audit start in three weeks.

**Comment by atom-yang** [comment]
Thanks for supporting and sorry for no responding for about two weeks. Actually like @nivida said above, what I mean is that wider encrypt options should be supported, including `cipher` and `scrypt` options.

Thanks.
