### ISSUE TITLE
Analyse Deno compatibility

### ISSUE THREAD

**Issue by nivida** [ethereum/web3.js#3339]
[Deno](https://deno.land/) from @ry (Ryan Dahl) is already known as the more secure alternative to nodejs. Because the web3.js library and the created products with it are security-sensitive is an analysis of the compatibility problems required to possibly allow our consumers to use Deno in the future.

1. What isn't working as expected with Deno?
2. What are the possibilities to be compatible with nodejs and Deno?
3. Where would we publish the package for Deno? (it doesn't have a package registry like npm)

**Comment by cokia** [comment]
As for number 1, I'll take a little test and post a comment below.

2. I think there is no problem that web3.js are incompatible because deno is not much different from nodejs.

3. deno calls the package like a CDN import, so users can just enter web3.js' GitHub address.
(ex: import 'web3' from 'https://github.com/ethereum/web3.js')

**Comment by rymnc** [comment]
> As for number 1, I'll take a little test and post a comment below.
> 
> 1. I think there is no problem that web3.js are incompatible because deno is not much different from nodejs.
> 2. deno calls the package like a CDN import, so users can just enter web3.js' GitHub address.
>    (ex: import 'web3' from 'https://github.com/ethereum/web3.js')

number 2 doesn't work

**Comment by aaryamannchallani** [comment]
web3 doesn't have default exports
