### ISSUE TITLE
Extend transaction revert handling for eth.sendSignedTransaction

### ISSUE THREAD

**Issue by nivida** [ethereum/web3.js#3345]
#### Expected behavior

``eth.sendSignedTransaction`` should return the revert reason string as expected.

#### Actual behavior

``eth.sendSignedTransaction`` does get executed but the signed transaction doesn't get decoded to get the revert reason string as expected.

#### Steps to reproduce the behavior

1.  call ``eth.sendSignedTransaction`` and the revert instruction opcode does get called.

#### Versions
web3.js: latest

**Comment by nivida** [comment]
@gorgos As mentioned in the answer I gave you ([comment](https://github.com/ethereum/web3.js/issues/1707#issuecomment-579124737)) is this the issue to track the process of this enhancement. Feel free to propose the related PR.

**Comment by AnthonyAkentiev** [comment]
@nivida Hi Samuel. Please help... Lost 12 hours debugging this...
I've tried everything, but still can't get the revert reason.

I've tried web3@1.2.8's way to get it:
1) i've set `web3.eth.handleRevert = true;`
2) but the revert reason is still 'false' - in this line https://github.com/ethereum/web3.js/blob/1.x/packages/web3-core-method/src/index.js#L465

My code is here - https://gist.github.com/AnthonyAkentiev/e8cd38328769284c110626b9e4a1379b

i've also tried this script -> https://gist.github.com/gluk64/fdea559472d957f1138ed93bcbc6f78a
i've also tried this script -> https://gist.github.com/KentonPrescott/e5e38da3b9c3c94ef7f233076e1ea64b#file-debuggingrevert-js

but nothing helped :-(((( 
We are using geth@1.9.12 node, maybe the reason is GETH not providing us with revert reason? 

Thank you very much!

**Comment by ryanio** [comment]
@AnthonyAkentiev ah sorry to hear that! our ci is working with geth 1.9.13 so it should be working for you with 1.9.12. see here:
https://github.com/ethereum/web3.js/blob/1.x/test/e2e.method.signing.js#L316

[Edited link for sendSignedTransaction test -cg]

can you confirm you are on 1.9.12 and not `stable`? there is a tracking issue for 1.9.14 with #3520

**Comment by AnthonyAkentiev** [comment]
@ryanio Thx for quick answer! Really appreciate it.
Oh, i double checked and our current version is '1.9.14-stable-6d74d1e5', should we use 1.9.12 to get 'reason' working?

**Comment by cgewecke** [comment]
@AnthonyAkentiev Yes, revert with reason only works up with geth up until 1.9.13. 

1.9.14 introduced a bug which they just fixed today at [go-ethereum 21083][1].  When that's published we'll be able to restore reason fetching in the next patch release here. 

[1]: https://github.com/ethereum/go-ethereum/pull/21083

**Comment by AnthonyAkentiev** [comment]
@cgewecke thx. checked current stable 1.9.15 and it worked!

**Comment by cgewecke** [comment]
Side-note for anyone else running into this... it looks like there *will* need to be code changes here to get the revert reason working again per the existing API for geth 1.9.15. 

PR #3571 should resolve.
