### ISSUE TITLE
sha3 compatibility with nodejs >13.5.0

### ISSUE THREAD

**Issue by cokia** [ethereum/web3.js#3360]
#### Expected behavior
Successful Build

#### Actual behavior
Error while run build script with glup

#### Steps to reproduce the behavior

1. git clone web3 repository 
2. npm install
3. npm run-script build or npm run-script build-all

(same result)

#### Logs

![image](https://user-images.githubusercontent.com/24792377/73611189-9c19f280-4622-11ea-915c-7e81755c4be2.png)

#### Versions
Npm version : 6.13.4
Node version : v13.5.0
osx version : 10.15.1(19B2106)

#### how to solve
> npm install web3-bzz
 command did a good job of installing a separate 'web3-bzz' 
(I anticipate we can solve this problem with install web3-bzz via package.json).

**Comment by cokia** [comment]
Oops, this was an error in my judgment. There was an error installing web3-bzz during npm install.

The installation process of the sha3 library fails. If you perform npm install sha3, it will install well. (If "npm install" is performed after "npm install sha3", the same process will fail.)

Also, there was no problem at all when I run "npm install web3-bzz"

**Comment by nivida** [comment]
@cokia The ``web3-bzz`` module with his dependency should get installed/linked as expected if you call ``npm install``. The post-install hook does execute ``lerna bootstrap``. The possibility is here that this issue only occurs on nodejs >13.0.0. I will investigate further. Thanks! :)

Edit:
As I can see is your local git clone behind the head of 1.x which could be the problem as well.

**Comment by nivida** [comment]
After a short try with ``13.5.0`` was it clearly visible that the sha3 dependency doesn't work as expected. I will check if this already got patched in the sha3 package itself and will go down the dependency tree after. 👍

**Comment by cokia** [comment]
Thank you for your efforts.

**Comment by nivida** [comment]
@cokia I've checked that closer now and the related dependency from @axic [keccakjs](https://www.npmjs.com/package/keccakjs) is using a quite old version of the [sha3](https://npmjs.com/package/sha3) package. I will contact the right persons internally and will try to trigger an update of it.

**Comment by michaelsbradleyjr** [comment]
web3's `package-lock.json` has sha3 [resolved to `1.2.3`](https://github.com/ethereum/web3.js/blob/1.x/package-lock.json#L15241-L15257).

However, the [caret range in keccakjs](https://github.com/axic/keccakjs/blob/master/package.json#L23) should allow it to be resolved to `1.2.6`, which would have the [fix from `1.2.4`](https://github.com/phusion/node-sha3/releases/tag/v1.2.4) for Node 13.x compatibility.

Embark had this problem too, though we use `yarn.lock` instead of `package-lock.json`. I simply snipped out the part with the resolution info for `sha3`, reran `yarn install`, and our lockfile was updated with `sha3@^1.2.2`  resolved to `1.2.6`.

I think that if you delete L15241-L15257 in `package-lock.json` and rerun `npm install` you'll get an equivalent effect.

**Comment by nivida** [comment]
@michaelsbradleyjr  Oh great! Thanks for your input.

**Comment by cokia** [comment]
https://github.com/axic/keccakjs/pull/12

The same issue in Keccakjs was PR in March/2019, but has yet to be confirmed. (Recent Commitment at DEC/2018)

I think Web3.js should clone the kecakjs that solved this problem.

**Comment by michaelsbradleyjr** [comment]
@cokia that's true but see this line in the most recent published version:

https://github.com/axic/keccakjs/blob/v0.2.3/package.json#L23

Owing to the caret range it can resolve sha3 to `>=1.2.2 <2.0.0`. Because sha3 `>=1.2.4` has the fix, then in projects with `package-lock.json` or `yarn.lock` that have the transitive dependency of keccakjs (sha3) locked to some version `<1.2.4` the thing to do is to force a bump in the lockfile.

In a fresh install of keccakjs in a new project or a project that doesn't use lockfiles, keccakjs will automatically pick up `sha3@1.2.6`. If you're using Linux or macOS, try this in a bash shell: 

```shell
$ mkdir -p ~/temp/tryme && cd ~/temp/tryme
$ npm init -y && npm i keccakjs
$ npx json -f node_modules/sha3/package.json version
```

Will print `1.2.6`.

I tried the above using Node.js v13.7.0 and the version of npm it ships with (6.13.6) and it installed without error.

**Comment by cokia** [comment]
Oh, your solution worked for me, too! Thank you :)
Can I close this issue?
