### ISSUE TITLE
web3/shh: non ASCII payload fails

### ISSUE THREAD

**Issue by obscuren** [ethereum/web3.js#346]
When payload with non-ASCII is delivered over a watched filter it will fail because `web3` attempts to convert the original `payload` received to ASCII.

If you'd like to keep the original functionality I suggest you add a `try {} catch {}` around this bit of code https://github.com/ethereum/web3.js/blob/master/dist/web3-light.js#L3784

Unfortunately I've no idea where I can find this in the original files but I'm sure that either @debris or @frozeman know the exact locations.

**Comment by obscuren** [comment]
This is also the reason why the whisper dapp no longer works

**Comment by frozeman** [comment]
I know i wanted to adept the whisper dapp at some point. These changes where made long ago.

It was a different function before, which detected what the out and input to  payload was and converted it accordingly. Marek removed this functionality and replaced it with simple toAscii. As i never had the time to look at it i didn't fix it.

When do we receive something we don't want to convert to string?

We should actually look into all the possible use cases for sending and receiving payloads and should make a smart converting tool for that.

But concerning your PR, when would it fail?

**Comment by obscuren** [comment]
It shouldn't be converted at all. I don't understand why this functionality was added at all. 

And it fails, as the title of the PR says, when sending non ASCII. Try sending `0xaa` instead of `"hello world"`. 

Please note that when I say ASCII ik not talking about the hex not bein ACII, I'm talkin about the encoded value not being ACII.

**Comment by frozeman** [comment]
The idea was that it tries to decode the content and try to JSON parse it, so that you can easily simply pass an object as payload and get one back. I think this will be the main use case in web3.js for shh transfers.

We can simple make it this way, that it tries to decode and son parse, if not possible it returns the plain HEX.
We should also prevent all decoding errors as in your PR.

I will revisited this when i go back to looking at whisper.

(Until now shh was left out at all refactrors)

**Comment by frozeman** [comment]
Please re-open if thats still and issue with web3 1.0.0
