### ISSUE TITLE
A type of web3-eth is incorrect

### ISSUE THREAD

**Issue by odanado** [ethereum/web3.js#3483]
When using web3-eth in TypeScript, the type does not match the actual value. This is a problem that also occurs in packages such as web3-eth-contract.

#### Expected behavior
```typescript
import { Eth } from "web3-eth"
console.log(Eth) // => show object of something
```

#### Actual behavior
show `undefined`

#### Steps to reproduce the behavior
reproduce repository
https://github.com/odan-sandbox/web3.js-eth-incorrect-type/blob/master/src/app.spec.ts

Run
- git clone https://github.com/odan-sandbox/web3.js-eth-incorrect-type
- yarn install
- yarn jest

#### Versions
node: v12.11.1
web3.js: 1.2.6
typescript: 3.8.3

**Comment by odanado** [comment]
On this line, `export class Eth` must be changed to `export default class Eth`.
https://github.com/ethereum/web3.js/blob/fab4ce738cf24af0e1b2928025d4683ce5f19553/packages/web3-eth/types/index.d.ts#L64

**Comment by cgewecke** [comment]
@odanado This problem affects most of the sub-modules and has been reported in #3215 and #3292. If you're using TS, the best option at the moment is to import Web3 and access everything through that.

I'm going to close this as duplicate unless you have a strong objection because this is something that has broader scope than `web3-eth` and is already under discussion.

**Comment by odanado** [comment]
OK, Thank you.
In my use case, I was trying to mock Eth on `web3-eth` using `jest`. The way to mock `web3` is cumbersome because the objects are nested.

**Comment by cgewecke** [comment]
@odanado Ah I see - thanks for raising that use-case. Good to know.
