### ISSUE TITLE
Removing ethers from the dependencies

### ISSUE THREAD

**Issue by alcuadrado** [ethereum/web3.js#3484]
As we discussed yesterday, having ethers as a dependency in web3.js makes npm stats worthless, and we should remove it asap.

I'm inclined to vendor the part of ethers that web3 uses for now, as it's a low effort way of solving it, release a patch version, and then analyze if an ethers v5 package can be used.

As I already mentioned, keep in mind that a change like this one takes some time to manifest itself in the stats, so releasing soon is pretty important.

**Comment by ricmoo** [comment]
The package you will be interested in is `@ethersproject/abi`. There may be some issues revolving around invalid UTF-8 strings though. I can add a function similar to the coerceFunc to handle errors, so that errors can be recovered from, since I think web3 lets invalid data through. I'll tinker with ideas for this API.

**Comment by cgewecke** [comment]
cf: #3461 / #3441 / #1610

**Comment by ricmoo** [comment]
For discussion on the ABI Coder and possible solutions: https://github.com/ethers-io/ethers.js/issues/800
