### ISSUE TITLE
getPastEvents works or not works depending on the event's location at the smart contract

### ISSUE THREAD

**Issue by ouoabcde** [ethereum/web3.js#3738]
#### Expected behavior

`getPastEvents` should work correctly regardless of the event's location at the smart contract.

#### Actual behavior

Throws an error like this when the event which is producing this bug is right below the another event.

`Error: data out-of-bounds (length=0, offset=32, code=BUFFER_OVERRUN, version=abi/5.0.0-beta.153)`

#### Steps to reproduce the behavior

1. [This produces the error]

Here's my full code. `LogRequest` event which is the first located event works fine on `getPastEvents`. But, `LogResponse` event which is located below the `LogRequest` event produces this error.

```
pragma solidity ^0.5.0;

contract Logger {
    event LogRequest(bytes32 indexed requester, bytes source, bytes indexed target, bytes indexed command, uint256 requestedTime); // this works fine
    event LogResponse(bytes32 indexed requester, bytes source, bytes indexed target, bytes indexed command, bytes result); // this produces the error

    function request(bytes32 requester, bytes memory source, bytes memory target, bytes memory command, uint256 requestedTime) public {
        emit LogRequest(requester, source, target, command, requestedTime);
    }

    function response(bytes32 requester, bytes memory source, bytes memory target, bytes memory command, bytes memory result) public {
        emit LogResponse(requester, source, target, command, result);
    }
}
```

2. [This works fine]

When I put the `LogResponse` event between two functions, this works fine. Weird... It's structure looks like this below.

```
event LogRequest(...);
function request() {...}
event LogResponse(...);
function response() {...}
```

#### Logs

The error log is at the `Actual behavior` corner.

#### Environment

npm: 6.14.6
Node: 12.18.3
Truffle: 5.1.37
solc: 0.5.0
web3.js: 1.3.0
OS: macOS Catalina 10.15.6

**Comment by Spacesai1or** [comment]
Hi there, I've tested your example code via [my test repo](https://github.com/spacesailor24/web3-3738) and it seems to be working in the [latest release candidate](https://github.com/ethereum/web3.js/pull/3757). Can you confirm that your original issue is resolved using the release candidate?

FYI, I removed the `indexed` tags from your events `LogRequest` and `LogResponse` because Solidity returns the hash of an array in an event instead of the actual value. If you'd like the actual value to be emitted, you must remove the `indexed` tag

Here is the above found in the [Solidity docs](https://solidity.readthedocs.io/en/v0.5.13/contracts.html#events):

> If you use arrays (including string and bytes) as indexed arguments, its Keccak-256 hash is stored as a topic instead, this is because a topic can only hold a single word (32 bytes).
