### ISSUE TITLE
Error while decode transaction gas: "Number can only safely store up to 53 bits"

### ISSUE THREAD

**Issue by fonov** [ethereum/web3.js#3745]
I tried decode transaction from block but got a error 

```
Number can only safely store up to 53 bits
	at assert ./node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:6
	at BN.toNumber ./node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:506
	at Object.hexToNumber ./node_modules/web3-core-helpers/node_modules/web3-utils/lib/utils.js:208
	at Method.outputTransactionFormatter [as outputFormatter] ./node_modules/web3-core-helpers/lib/formatters.js:204
	at Method.formatOutput ./node_modules/web3-core-method/lib/index.js:147
	at sendTxCallback ./node_modules/web3-core-method/lib/index.js:523
	at ./node_modules/web3-core-requestmanager/lib/index.js:293
	at XMLHttpRequest.request.onreadystatechange ./node_modules/web3-providers-http/lib/index.js:98
	at XMLHttpRequestEventTarget.dispatchEvent ./node_modules/xhr2-cookies/xml-http-request-event-target.ts:44
	at XMLHttpRequest._setReadyState ./node_modules/xhr2-cookies/xml-http-request.ts:219
	at XMLHttpRequest._onHttpResponseEnd ./node_modules/xhr2-cookies/xml-http-request.ts:345
	at IncomingMessage.<anonymous> ./node_modules/xhr2-cookies/xml-http-request.ts:311
	at IncomingMessage.emit events.js:326
	at endReadableNT _stream_readable.js:1252
	at processTicksAndRejections internal/process/task_queues.js:80
```

error occur with tx id `0xe0db32759810271eec05326a4c96fbb42a185139134e16b4581f77456df226a9`

if look closely on https://bscscan.com/tx/0xe0db32759810271eec05326a4c96fbb42a185139134e16b4581f77456df226a9

we can see that gas equal `9,223,372,036,854,775,807`, so web3 js can't convert this string to number 

Anyone has idea how resolve this problem? 

```
import Web3 from 'web3';

async function main() {
  const web3 = new Web3('https://bsc-dataseed1.binance.org:443');

  const res = await web3.eth.getBlock(1365710);

  await Promise.all(
    res.transactions.map(async (txId) => {
      try {
        const tx = await web3.eth.getTransaction(txId);

        console.log(`decode ${txId}`);
      } catch (error) {
        console.error(`error decode ${txId}`);
      }
    }),
  );
}

main();
```

**Comment by Spacesai1or** [comment]
Thank you for reporting this, it seems to be a long standing issue as mentioned in #3751, hopefully we can take a look at this and finally fix the underlying issue!

**Comment by fonov** [comment]
issue still active

**Comment by GregTheGreek** [comment]
Was looking into this because of #3936.

It looks like the [tx formatter](https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-core-helpers/src/formatters.js#L241) is overflowing on the gasLimit from calling [hexToNumber](https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-utils/src/utils.js#L230). This could be solved by one of the following:
1. Use [hexNumberToString](https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-utils/src/utils.js#L249)
2. Return a BN for everything and drop auto formatting (let the user decide how they wish to represent their numbers)

In both cases this breaks semver. I cannot think of a solution that allows us to introduce a fix in the current `v1.x` release cycle...

**Comment by Spacesai1or** [comment]
@GregTheGreek I would think returning numbers as strings offers the user the most flexibility. Assuming most will default to BN or BigNumber.js, they can both be instantiated by strings

**Comment by lucaspiressimao** [comment]
this can help https://github.com/ChainSafe/web3.js/issues/3936#issuecomment-797342613
