### ISSUE TITLE
Contract deployment doesn't support libraries

### ISSUE THREAD

**Issue by boukestam** [ethereum/web3.js#3805]
While trying to deploy a smart contract we got the following error ```The data field must be HEX encoded data.```
After a lot of debugging I found out that this is caused because the isHex function in [utils.js](https://github.com/ethereum/web3.js/blob/1.x/packages/web3-utils/src/utils.js) only supports characters 0-9 and a-f.

But when using a linked library solidity includes this in the outputted JSON
```
"linkReferences": {
	"AllianceBlock/PercentageCalculator.sol": {
		"PercentageCalculator": [
			{
				"length": 20,
				"start": 13575
			}
		]
	}
}
```

And adds dollar signs and underscores in the bytecode to indicate the location of the library
![image](https://user-images.githubusercontent.com/8492132/101172894-0edc6b80-3642-11eb-8d1a-c38925496a2b.png)

This is according to the solidity github found here https://github.com/ethereum/solidity/issues/635

How can we deploy this contract? We couldn't find any way to change the compiler settings to not include these characters

**Comment by sensati0n** [comment]
I've came accross a similar issue.

My steps:

1) Compiling the Library.
2) Deploying the Library.
3) Compiling the Contract.
4) Linking the Library with the Contract.
5) Deploying the Contract. *ERROR: `The data field must be HEX encoded data.`

As @boukestam mentioned, this is because of 'foreign' characters in the bytecode.

Currently, I am unable to deploy my contract containing a link to my library...

Is there any update to this issue?

UPDATE:

Reading [this issue](https://github.com/tomusdrw/rust-web3/issues/186) it seems like this is still part of the hashed Library-Name, indicating that the linking did not work as expected.

**Comment by Spacesai1or** [comment]
Hi there, wanting to know if this is still an issue for you?

If so, could provide a test repository for this?

**Comment by visopsys** [comment]
I also have this issue when using with a library. If I move a function from library to inner contract, then it compiles successfully.
