### ISSUE TITLE
Unsubscribing on an event does not work

### ISSUE THREAD

**Issue by outdoteth** [ethereum/web3.js#3822]
#### Expected behavior

Calling .unsubscibe() on an event listener unsubscribes from an event

#### Actual behavior

Does not unsubscribe from the event - The handler still gets called whenever an event is triggered.

#### Steps to reproduce the behavior

```
const listener = myContract.events.SomeEvent()
            .on("data", (event: any) => {
                console.log(event) // Keeps logging on new events even after event listener is unsubscribed.
            });

listener.unsubscribe(); // Does not unsubscribe
```

#### Environment

Using the latest web3.

**Comment by yanikitat** [comment]
Hello everyone! I have still issue, @outdoteth did you find the solution?

**Comment by Muhammad-Altabba** [comment]
@yanikitat Thanks for telling about this issue again. 
Could you please confirm that you still face it at the latest version of 1.x? (version 1.8.0?)

**Comment by WilliamWelsh** [comment]
Can confirm that unsubscribing from an event on 1.8 does not work. On 1.7.4, unsubscribe would return true but would still be subscribed, after upgrading to 1.8, `error` is `null` and `success` is `undefined`, and is still subscribed.

**Comment by yanikitat** [comment]
@Muhammad-Altabba I have tested this case again and this is what I have got:
I have a such simple code snippet:
```
  const web3 = new Web3("wss://goerli.infura.io/ws/v3/token");

  const subscription = web3.eth.subscribe("newBlockHeaders", () => {
    console.log("New block was arrived");
  }).on("connected", (subID) => {
    console.log(`was started successfully. subID=${subID}`);
  });
  console.log("subscription was getting");

  setTimeout(() => subscription.unsubscribe(), 20000);
```

And this is my console output:
```
subscription was getting
was started successfully. subID=0x410010025a332c64e44f7b51d7d423bfdee56deb9ae1
New block was arrived
New block was arrived
```
So as I understand, `web3.eth.subscribe` returns Subscription object immediately, event if connect is not established yet. Because of this I'm using setTimeout for `subscription.unsubscribe()`. And I really don't get new blocks anymore, but my process is not complited and still working:
![image](https://user-images.githubusercontent.com/58594559/202138296-14d844a5-1778-4b96-9c7c-11b62b3347a5.png)
I think that is not expected behavior and I see two problems here:
1. `web3.eth.subscribe` must be an async function and returns subscribption object only when connect is establish.
2. the process must be complited after the `subscription.unsubscribe()` call

**Comment by yanikitat** [comment]
It seems like I got why my process in not complited. When we are creating Web3 instance with WebSocketProvider, the connection is established right in conscturctor:
```
const web3 = new Web3("wss://goerli.infura.io/ws/v3/token");
```
```
      at WebSocketClient.Object.<anonymous>.WebSocketClient.connect (node_modules/websocket/lib/WebSocketClient.js:254:56)
      at new W3CWebSocket (node_modules/websocket/lib/W3CWebSocket.js:62:18)
      at WebsocketProvider.Object.<anonymous>.WebsocketProvider.connect (node_modules/web3-providers-ws/lib/index.js:90:23)
      at new WebsocketProvider (node_modules/web3-providers-ws/lib/index.js:77:10)
      at RequestManager.Object.<anonymous>.RequestManager.setProvider (node_modules/web3-core-requestmanager/lib/index.js:68:24)
      at new RequestManager (node_modules/web3-core-requestmanager/lib/index.js:39:10)
      at Object.packageInit (node_modules/web3-core/lib/index.js:45:31)
      at new Web3 (node_modules/web3/lib/index.js:39:10)
      at Object.<anonymous> (test/unit/EventsHandler.test.ts:44:22)
```
So because of this the process is not complited and still working. I didn't find anything in the doc about this. Maybe you need to add any info about this behavior in the doc.

If I make this:
```
  const provider = web3.currentProvider as WebsocketProvider;
  provider.disconnect();
```
My proccess is finished as expected

**Comment by mconnelly8** [comment]
6/12 - keep
