### ISSUE TITLE
vite2 can't use this

### ISSUE THREAD

**Issue by jinmao88** [ethereum/web3.js#3951]
![image](https://user-images.githubusercontent.com/50581550/111103978-94997c80-858a-11eb-8e8c-9522a071b5a6.png)
![image](https://user-images.githubusercontent.com/50581550/111104085-cdd1ec80-858a-11eb-9c4d-9c86a1c35ae3.png)

**Comment by koraykoska** [comment]
Do you have any details? An example would be great so I can investigate.

**Comment by jinmao88** [comment]
https://github.com/anncwb/vue-vben-admin   this project
yarn add web3   
Component 
import web3 from 'web3'
console.log(web3)

vue3+vite2+ts

**Comment by okevinok** [comment]
my problem is Buffer from node library not define 

![image](https://user-images.githubusercontent.com/19623957/122164225-098d9280-cea9-11eb-8d1c-ad9c8590e594.png)

util.js:33 Uncaught ReferenceError: Buffer is not defined,

**Comment by okevinok** [comment]
> Do you have any details? An example would be great so I can investigate.
The simple demo is like this, use vite2+vue3+ts , 

https://github.com/1329778364/vite_vue3_web3/tree/main

**Comment by SirSavio** [comment]
Reopening this because even with the code provided by @EvinqWang , the buffer error is not defined persists when you build the application and put it to run in production. Locally works, but after build it doesn't.

Configs:
Portainer, nginx proxy, docker

Code: https://github.com/1329778364/vite_vue3_web3/tree/main

Error after build: 
![image](https://user-images.githubusercontent.com/50343835/135304267-8bf5cfd3-5f28-4380-b39d-0086ecc1f374.png)

**Comment by Pandazaur** [comment]
I experienced the same issue.

1. create a project with Vite-cli (`npm init vite@latest`) with "react-ts" but I think the problem is also on the other templates
2. Added web3.js `npm i web3`
3. Use `import web3 from 'web3'` cause the error with `process is not defined`

A workaround is to use `import Web3 from 'web3/dist/web3.min.js'` but not every confortable. I think the typescript types are broken with this workaround

**Comment by PippoApps** [comment]
Same problem here, no matter how I start the project.
Just a clean install (same error with vite or webpack).
With web3 installed form npm:
![image](https://user-images.githubusercontent.com/29799572/147885218-a95c0e4a-9cc9-4df2-890e-0c13439e75b4.png)

**Comment by MatthiasRossbach** [comment]
I run into the same problem, and after some investigation I got an idea: I found this one: https://medium.com/@ftaioli/using-node-js-builtin-modules-with-vite-6194737c2cd2

Problem seems to be that web3 expect a node-like environment in the browser with browserify. Unfortunately vite does not bundle in that way, but using pure browser modules without a node bundling in between. With the link provided it work for me in dev, but unfortunatly not in production (at least not eth.accounts.sign). While being unclear it seems that buffer works differently in development and in production, but no idea why.
