### ISSUE TITLE
Server firewall is blocking the Web3.js connection in NODE

### ISSUE THREAD

**Issue by JTorresConsulta** [ethereum/web3.js#4056]
My Centos server has running the "ConfigServer Security & Firewall" and its blocking the Web3.js connection with Ethereum node. The functions calls returns: "Error: Invalid JSON RPC response:"

Any idea how could I avoid it?

**Comment by Spacesai1or** [comment]
Hi there, are you sure that your firewall is the issue? In my experience, `Error: Invalid JSON RPC response` usually comes from an invalid sent request/interaction with the blockchain. You could try sending a basic `web3.eth.getProtocolVersion()` to debug whether it's your firewall or not though

Anyways, I don't know enough to help you with your specific issue. My only recommendation would be to allow the port you're attempting to connect to on the Ethereum node for your firewall. I'm going to close this issue though, since it's not related to an issue of the library
