### ISSUE TITLE
[Rewrite] Refactoring web3-provider-base web3-core-requestmanager

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4176]
#### 4.x Improvement

web3-provider-base will always be used in web3-core-requestmanager so (Web3ProviderBase, SubscriptionResponse and IWeb3Provider) should be moved to web3-core-requestmanager module.

**Comment by Spacesai1or** [comment]
`web3-providers-http`, and eventually `web3-providers-ws` and `web3-providers-ipc`, currently don't rely on `web3-core-requestmanager`. Keeping `web3-provider-base` as a separate package allows for the smallest/least bloated packages, making sure we only include what we need for each package to work, and allows us to build up packages instead of them being all inclusive

We could add the class as a separate export of `web3-core-requestmanager`, allowing us to do:

```javascript
import {Web3ProviderBase} from 'web3-core-requestmanager`
```

but I don't think this accomplishes much, and you can have a provider without using the request manager, so I don't think bundling them makes sense
