### ISSUE TITLE
web3.eth.ens doesnt' seem to be consistent

### ISSUE THREAD

**Issue by chovyprognos** [ethereum/web3.js#4276]
https://stackoverflow.com/questions/68936422/getting-inconsistent-responses-with-web3-eth

The code runs but says "food.eth" is available (it isn't):

```
var Web3 = require("web3")
let web3 = new Web3(Web3.givenProvider || "ws://localhost:8546");
var ens = web3.eth.ens;
const words = [
	'beer',
	'food',
	'chovy',
];

(async () => {
	for (let word of words) {
		console.log('checking: '+ word);
		const addr = await getDomain(word);
		console.log(word+': '+ addr);
	}
})();

async function getDomain(word) {
	try {
		const addr = await ens.getAddress(`${word}.eth`)
		console.log(addr);
		return addr;
	} catch(err) {
		console.error(err);
		return;
	}
}

```

I'm running geth with the following command on Ubuntu 20.04:

`geth --syncmode "light" --ws --mainnet`

**Comment by chovyprognos** [comment]
If I call `ens.recordExists(name)` i get valid true/false returned for domains, but there doesn't seem to be a way to get the address of a domain name consistently

**Comment by jdevcs** [comment]
@chovyprognos Its not returning address because resolver is not set by owner. [ENS doc: Resolving a name in ENS is a two-step process: First, ask the registry what resolver is responsible for the name, and second, ask that resolver for the answer to your query. ](https://docs.ens.domains/#ens-architecture) 

 [ double checking ](https://app.ens.domains/name/food.eth/details )

so web3 is also telling same `Could not verify interface of resolver contract at "0x0000000000000000000000000000000000000000".`

**Comment by chovyprognos** [comment]
how do i get the resolver?

**Comment by jdevcs** [comment]
You cannot get resolver because its not there.

As mentioned earlier owner need to set it before usage: https://docs.ens.domains/dapp-developer-guide/managing-names#setting-a-resolver

Its not problem in web3 so closing issue.

**Comment by ralyodio** [comment]
Isn't the resolver specific to the domain?  Seems I would have to look up that first

**Comment by chovyprognos** [comment]
it seems the docs should reflect this: https://github.com/ChainSafe/web3.js/blob/v1.2.11/docs/web3-eth-ens.rst
