### ISSUE TITLE
About the token transfer process with Web3 and MetaMask

### ISSUE THREAD

**Issue by 0xBeycan** [ethereum/web3.js#4334]
Hello, I am creating a transfer request by javascript with web3 and the MetaMask confirmation screen opens. There is an edit button at the top of the confirmation screen, I don't want this to happen, and I just want it to be able to confirm the transfer confirmation with the token I initiated.

Also, after confirmation, the transaction can be canceled from the activity section, but I do not want this to happen because it makes a payment, so after approval, it cannot be canceled like a credit card, but the site owner can request a refund.

So I want the transfer process I started to be non-cancellable, how can I do that? I couldn't find anything in neither MetaMask nor Web3 documents, please help.

Version: 0.20.7 / MetaMask/legacy-web3

**Comment by Spacesai1or** [comment]
So this is a feature request for Metamask, as Web3.js has not control over the extension

Additionally, if the user is signing the transaction with their own private key, there is no way to keep them from cancelling the transaction, because they could always send another transaction using the same `nonce` with higher gas to get it prioritized over the original transaction. This is partly why most sites wait for X number of transactions confirmations before deeming the transaction as irreversible

Maybe you could try opening the same issue in MetaMask repo for some additional guidance, but I don't think they give you programmatic control over the extension
