### ISSUE TITLE
web3 not firing events on app Metamask

### ISSUE THREAD

**Issue by xale76** [ethereum/web3.js#4438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While performing operation using App Metamask on iOs (and Android) phone, the call on website remains pending waiting for confirmation of operation even after that the operation is confimed on network. Tried with Rinkeby and infura node.
I use web3modal on React site. On my website I choose WalletConnect option and QR code reader on my metamask app to connect my website.

ATTENTION: If I use the browser inside Metamask app everything is ok

### Expected Behavior

The await procedure called on my REACT app should resolve and show alert after network confirmation shown on metamask app

### Steps to Reproduce

 await mytoken.methods.approve(dest_address,quantity).send({from:address,type:type,gasPrice:gprice});
 alert('await resolved');

### Web3.js Version

1.6.0

### Environment

- Operating System: iOs

**Comment by nazarhussain** [comment]
@xale76  That issue was fixed in #3891 which is included in `1.6.1-rc.0` release. In the issue you mentioned version `1.6.0` which should not include that fix. Please try using `1.6.1-rc.0` and see if it fixes for you.

If it still not work, then share some reproducible code that will be helpful for us to investigate further.

**Comment by xale76** [comment]
@nazarhussain with 1.6.1-rc.0 the problem seems to be fixed!
