### ISSUE TITLE
eth.Contract objects are never garbage collected

### ISSUE THREAD

**Issue by zviadm** [ethereum/web3.js#4580]
Looking at the code here:
https://github.com/ChainSafe/web3.js/blob/a1c7d71973ec17f9287fbea8939e64a80e589fc6/packages/web3-eth/src/index.js#L332

It looks like all eth.Contract objects reference each other in a chain of setProvider calls. This means eth.Contract objects can not be garbage collected and will just cause a slow memory leak if you have a code that creates them over time. 

Here is an example from a heapdump that shows how setProvider references nest:
![image](https://user-images.githubusercontent.com/517937/143490223-034fbb6e-d97f-4adf-80f3-c073ba2c9b99.png)

Also, I suspect if you create lots of eth.Contract objects (maybe 100k, maybe 1million), setProvider call will probably just cause a stack overflow error.

**Comment by nazarhussain** [comment]
After investigation it's confirmed that the scenario what is described in the issue is correct. It was introduced in https://github.com/ChainSafe/web3.js/pull/1726/ as a feature, so I am not sure if we call it a bug or desired side effect of a feature. 

That feature requires following: 

1. When someone update provider from upper package all the children should have updated provider. 
2. e.g. If `web3.eth.setProvider` is called to change the provider 
3. **All the instances** of contracts created with `web3.eth.Contract` should also have updated provider 
4. For that purpose `web3.eth` have to keep the reference of all contract instances created 
5. And due to those references the contract objects are not garbage collected. 

The straight forward fix would be to change this behaviour and end-user should update the provider for each instance b himself, that will be a breaking change by itself with respect to end user developer experience. 

If we want to preserve that feature and still want to fix that memory-leak, that requires good chunk of refactoring across different packages. Not sure we intended this at the moment when we are focussed on 4.x rewrite.

**Comment by nazarhussain** [comment]
As discussed with @spacesailor24 @jdevcs @luu-alex 

Due to feature requirements implemented in #1726 we can't change the behavior in the 1.x. If we have to update the provider for all the created instances of the contracts then we have to keep reference of those instances. Yet it's not a memory leak, but necessary evil for the feature. Based on experience it's also common to not create so many instances of a contract that tend to create performance issue. Also in current 1.x implementation it's not possible to refactor the design of the library to avoid it. 

Closing this issue for now, after 4.x release we may think of some big refactors to provide similar behavior without it's side effects.

**Comment by zviadm** [comment]
> As discussed with @spacesailor24 @jdevcs @luu-alex
> 
> Due to feature requirements implemented in #1726 we can't change the behavior in the 1.x. If we have to update the provider for all the created instances of the contracts then we have to keep reference of those instances. Yet it's not a memory leak, but necessary evil for the feature. Based on experience it's also common to not create so many instances of a contract that tend to create performance issue. Also in current 1.x implementation it's not possible to refactor the design of the library to avoid it.
> 
> Closing this issue for now, after 4.x release we may think of some big refactors to provide similar behavior without it's side effects.

Not fixing it is reasonable, but it is definitely a "reference leak" (i.e. memory leak). Since no Contract object will ever get garbage collected even if there are no references left for it.

I would recommend at least adding this information inside documentation, somewhere here: https://web3js.readthedocs.io/en/v1.7.0/web3-eth-contract.html

Example note: 'web3.eth.Contract' objects will never be garbage collected, thus users should avoid creating them dynamically to avoid memory leaks. 


Also I think there are at least some fairly easy backwards compatible workarounds here. For example:
* Instead of having this weird chain of objects, just create a global list where you put all web3.eth.Contract objects in. (That would also lead to sensible stack traces and overall a more clear setup of what is going on). 
* Add 'close' (or 'delete', or 'disconnect', whatever name you prefer) method on web3.eth.Contract object that will remove the object from that global list of all web3.eth.Contract objects, thus allowing it to be garbage collected. 

That way at least there would be a way to have a manual clean up. This would be useful for users who need to dynamically create web3.eth.Contract objects.

**Comment by nazarhussain** [comment]
@zviadm Yes I agree that a workaround can be established but for 4.x rewrite we are working on. Easiest work around is to just use a static property as current provider, this way whenever we change the property, it will reflect to all objects and we don't have to keep the reference of each object anywhere just for that purpose. 

For updating documentation for 1.x would definitely be a good step.

**Comment by nazarhussain** [comment]
Reopening the issue to target the 4.x rewrite.

**Comment by nazarhussain** [comment]
I reviewed the `4.x` implementation. Currently there are no memory leak in the Contract module, but it also does not update the provider for the all instances of the contract in single attempt. 

- If there are multiple instances of same contract or multiple contracts user has to update provider for each contract independently. 
- If we try to update all instances together then we have to keep reference of all instances, which will be memory leak 
- If we use some static reference of provider, that requires a lot of change in `web3_context` and will effect all other components. 

I personally believe as long as memory leak is fixed, we should not change further, though it will be a behavior change from 1.x. 

There is another way to wrap this behavior only with `web3` package and not make it part of the `web3-eth-contract` package. 

Please share your thoughts on it. @jdevcs @spacesailor24 @luu-alex

**Comment by nazarhussain** [comment]
@jdevcs @spacesailor24 @luu-alex I opened a PR, which is providing a solution. This will be consistent to 1.x behavior.

**Comment by janeklb** [comment]
Hi @nazarhussain 
Can we expect a fix / workaround for the 1.x releases?

**Comment by hjhjdev** [comment]
+1 for a fix / workaround for the 1.x release

**Comment by jdevcs** [comment]
@hjhjdev pls check 4.x , 4.0.1-alpha.1

**Comment by hjhjdev** [comment]
@jdevcs are there any backports for 1.x? I've looked into 4.x and it looks decent.
I'm using web3.js in production and it's hard to use alpha stage version
