### ISSUE TITLE
Web3 package -  include tracking of build size 4.x

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#4682]
## Description:
We want to be able to track build size of the whole project, this was inspired from #1178 we want the build size to be as minimal as possible.

We can use functionality from webpack 5 for analyzing the build size

## Acceptance Criteria:
- Be able to track and analyze build size within the Web3 pack

**Comment by hems** [comment]
I reckon one thing that should be aimed for is tree shaking.

If users just need to call a small function they should be able to only import such small function and use it as opposed to have to call a "global web3 object" that will pull each and every dependency on the bundle.

i mean that should not aimed for, that's what i reckon should be done, otherwise the problem will persist.

**Comment by hems** [comment]
any updates on this? i'm just commenting here so this issue hopefully is removed from "stale" as this is quite important?

**Comment by mconnelly8** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/web3js-553a980ab285bae538012a40/issues/ChainSafe/web3.js/4682?planning-poker) with ZenHub @avkos @jdevcs @luu-alex @nikoulai @spacesailor24 @nazarhussain

**Comment by hems** [comment]
not stale

**Comment by mpetrunic** [comment]
resolved by https://github.com/web3/web3.js/pull/5787
