### ISSUE TITLE
Discuss/Implement Migration Away From Lerna [4.x]

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#5006]
[Lerna](https://github.com/lerna/lerna) seems to no longer be maintained, so for `4.x` we could probably rely solely on Yarn Workspaces

**Comment by jdevcs** [comment]
As discussed in last sprint meeting, we will continue using `lerna` https://github.com/lerna/lerna/issues/3121 and will wait for new road-map announcement.

**Comment by Muhammad-Altabba** [comment]
Hello @web3/web3-js 
Since [May 2022, there is active development on lerna ](https://github.com/lerna/lerna/graphs/contributors). And there is continuous publishing of [new versions lerna on NPM](https://www.npmjs.com/package/lerna?activeTab=versions).
So, should we now close this issue? (and close the [related draft MR ](https://github.com/web3/web3.js/pull/5701) done by @mpetrunic , thanks to him)

**Comment by mpetrunic** [comment]
> Hello @web3/web3-js 
> Since [May 2022, there is active development on lerna ](https://github.com/lerna/lerna/graphs/contributors). And there is continuous publishing of [new versions lerna on NPM](https://www.npmjs.com/package/lerna?activeTab=versions).
> So, should we now close this issue? (and close the [related draft MR ](https://github.com/web3/web3.js/pull/5701) done by @mpetrunic , thanks to him)

It's now nx under the hood and it has ton of dependencies. They are dev dependencies but they still provide great surface for different malwares/attack vectors. It also has same problem with independent versioning^^

I think I have a draft pr for switching to yarn workspaces that needs a bit of love


P.s. you are also still on old version of Lerna

**Comment by mconnelly8** [comment]
Will be tracking this with #7326
