### ISSUE TITLE
web3 event watch gives wrong result object

### ISSUE THREAD

**Issue by aberaud** [ethereum/web3.js#509]
After sending a transaction, my nodejs server retrieves the transactionHash and watches for an event to be emitted by the contract method.

However if there are multiple transactions pending to be mined, their respective callback is called, but the result object is allays the same (it's the result object corresponding to the first sent transaction), even if the configured filter doesn't match !

Here is a simple code to reproduce the issue :
```js
function doSomething(some_args) {
    someContract.someMethod.sendTransaction(some_args, function(trans_error, trans_hash){
        if (trans_error) return;
        var watcher = someContract.SomeEvent({"transactionHash": trans_hash}, function(error, result) {
            watcher.stopWatching();
            // called 3 times, with the same transactionHash and result object
            print(result);
        }
    });
}
doSomething(args1);
doSomething(args2);
doSomething(args3);
```

If it's not a bug how to wait for multiple transactions/events at the same time ? Thanks.

**Comment by hitchcott** [comment]
I'm also running into a similar issue; it seems like a larger bug because it's also breaking the behaviour of `stopWatching`. If you can reproduce this bug, it means that `stopWatching` will not work properly; it won't uninstall the filter, `eth_uninstallFilter` is never received by server, and it won't callback.

Here's my [reproduction](https://github.com/hitchcott/testrpc-filter-issue/blob/master/test/index.js), which works fine with a geth node, but fails with testrpc. However, I think this still could be a bug with web3; it seems like a race condition due to TestRPC responding too quickly. If I add a timeout before initiating a transaction, everything works as expected.

I tried debugging with `testrpc -v` (with `<` showing outgoing, `>` incoming reuqests) to see what's happening. (See full output [here](https://github.com/hitchcott/testrpc-filter-issue/blob/master/json-interface.log)). Basically, what's happening:

**WITH the timeout -- works as expected**
```
[8 IN] eth_newFilter
[8 OUT] 0x02
[9 IN] eth_getFilterChanges + eth_getFilterLogs
...
[11 IN] eth_sendTransaction
TX MINED
[11 OUT] 0x....
[12 IN] eth_getFilterChanges 0x02
[12 OUT] { type: 'mined' } (correct event object, only once)
...
[22 IN] eth_uninstallFilter 0x02
```

**WITHOUT the timeout -- broken**
```
[24 IN] eth_newFilter
[25 IN] eth_sendTransaction
[24 OUT] 0x03
[27 IN] eth_getFilterChanges 0x03
[26 IN] eth_getFilterLogs 0x03
TX MINED
[25 OUT] 0x...
[26 OUT] { type: 'mined' } (correct event object)
[28 IN] eth_getFilterChanges 0x03
[27 OUT] { type: 'mined' } (correct event object)
[29 IN] eth_getFilterChanges 0x03
...
Never receives eth_uninstallFilter 0x03
```

So it looks like web3 is crapping out if a transaction is initiated immediately after web3 filter is started (when using testrpc). I think it might be solvable by adding a callback to `filter` (which doesn't immediately start watching, but instead calls back once the server server has confirmed the filter is installed), so the client knows when to start the transaction.

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
