### ISSUE TITLE
Error: Invalid JSON RPC response: ""

### ISSUE THREAD

**Issue by Ciao-2** [ethereum/web3.js#5138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error: Invalid JSON RPC response: ""

web3.eth.getTransactionReceipt(hash).then(req => {

}).catch(e => {
                Logger.error(e.message)
})

### Expected Behavior

web3.eth.getTransactionReceipt(hash).then(req => {

}).catch(e => {
                Logger.error(e.message)
})

### Steps to Reproduce

random occurrence

### Web3.js Version

1.7.3

### Environment

- Operating System: Linux RHAJ10-2802 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Browser: Chrome 102.0.5005.115
- Node.js Version: v14.15.0
- NPM Version: 6.14.8

**Comment by jdevcs** [comment]
@Ciao-2 are you using reliable provider, may be check provider directly?
`curl --data '{"jsonrpc":"2.0","method": "eth_getTransactionReceipt", "params": ["YOUR_TX_HASH"], "id": 0}' -H "Content-Type: application/json" localhostOR_YOUR_PROVIDER:8545`

**Comment by SaulMoonves** [comment]
This is happening to me as well on 1.7.4. I can do the curl request and it works fine but i get the error above when i try it from web3.js. This is tested on a production server where another application on web3.js 0.xx is working perfectly so it is definitely not the server or the connectivity.

 I added some logging statements to "web3-providers-http" and I have tracked down the problem. The xmlhttprequest upload content type is set to: "text/plain;charset=UTF-8" instead of "application/json". I reproduced the error in curl by setting the accept header to that.

specifically here is what i added:

```
console.debug("CONTENT-TYPE", request.upload._contentType);
```

and I can see it's: "text/plain;charset=UTF-8"

I don't know where that value is coming from and I haven't figured out how to fix it but maybe someone with more familiarity with the code will know.

node.js: v18.4.0
