### ISSUE TITLE
Invalid JSON RPC Error in web3

### ISSUE THREAD

**Issue by Neoblock8** [ethereum/web3.js#5271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,
  I just wanted to try multi send transactions in web3js using for loop. And i tried different web3 js versions. None can be supported. Mentioned the error in below image. 

![photo1658237390](https://user-images.githubusercontent.com/81068101/180210472-f71db33a-5636-4955-b36a-39054f44f8d2.jpeg)

### Expected Behavior

Output of more than 100 transactions

### Steps to Reproduce

let addr = [""]

function transferTest(){
    web3js.eth.getTransactionCount("<address>", "pending").then((txnCount) => {
        console.log("txnCount", txnCount)
        for(let i=0; i<length;i++){
    
        let txObj = {
            "nonce":txnCount++,
            "gas": 30000,
            "to": addr[i], //to_address
            "value": 1000000000000 
        }
        console.log("txObj", txObj)
    
        web3js.eth.accounts.signTransaction(txObj, <privatekey>, (err, signedTx) => {
            if (err) {
                console.log("err1", err)
            } 
            else {
                web3js.eth.sendSignedTransaction(signedTx.rawTransaction)
                .on('transactionHash',(hash) => {
                    console.log('txHash:', hash)
                }).on('receipt',(receipt) => {
                    console.log('receipt', receipt)
                }).on('error', console.error)
            }
        })
    }
    })
    }

### Web3.js Version

^1.0.0-beta.55, ^1.0.0-beta.31, 1.5.1, 1.2.0, 1.2.1

### Environment

- Operating System:  Ubuntu 18.04
- Browser: Chrome
- Node.js Version: 16.0.0
- NPM Version: 7.10.0

**Comment by ghost** [comment]
Looks like the error is coming from the node and it is likely to happen since

1. You create the array of promises which would send transactions with the same nonce without bumping fees, which results in node sending you a transaction error.

2. Previous version of web3.js is not capable of debugging node-generated errors very well, I recommend doing `npm i --save web3.js@v1.7.5-rc.1` so that web3.js would be able to show you the error you want.
