### ISSUE TITLE
How use web3.js with "Read as Proxy" and "Write as Proxy" 

### ISSUE THREAD

**Issue by max1404** [ethereum/web3.js#5313]
hello developers,

i check the issues and the [documentation](https://web3js.readthedocs.io/en/v1.7.5/) - but but I couldn't find any information on how to use web3.js as "_Read as Proxy_" and "_Write as Proxy_" ([EIP-1967](https://eips.ethereum.org/EIPS/eip-1967)) with a smartcontract on ethereum.

Am I just missing a buzzword for the search? Is it possible with Web3.js? If so, can someone drop a few lines of code?

Can I use the proxy contract including abi directly? without reference to the actual contract?

Thanks

**Comment by TurboTu** [comment]
I got the same problem too, have u solved it?

**Comment by TurboTu** [comment]
I got some tips @max1404 https://ethereum.stackexchange.com/questions/103143/how-do-i-get-the-implementation-contract-address-from-the-proxy-contract-address

**Comment by max1404** [comment]
@TurboTu Were you able to solve our problem? Do you have some code snippets for me? I couldn't do it. Thanks

**Comment by Spacesai1or** [comment]
Hi there, please let us know if this is still an issue for you. As far as I'm aware, there's nothing in our documentation related to ERC-1967. With that said, if you're interested in interacting with the contract the proxy is pointing to, you'd need to get the address and the ABI of the `implementation` contract (the [link](https://ethereum.stackexchange.com/questions/103143/how-do-i-get-the-implementation-contract-address-from-the-proxy-contract-address) shared above mentions how to get the address. Alternatively you could try looking up the proxy contract on a block explorer and see if the implementation contract address is available) in order to interact with it using web3.js

**Comment by mconnelly8** [comment]
Hey @max1404, we are closing this issue and recommend upgrading to v4 production released a couple weeks ago.  

https://docs.web3js.org/
https://docs.web3js.org/guides/web3_upgrade_guide/x/
https://www.npmjs.com/package/web3/v/4.0.1
https://github.com/web3/web3.js/releases/tag/v4.0.1
