### ISSUE TITLE
web3-eth-abi@1.4.0 `decodeLog` returns confusing error message when false inputs are given

### ISSUE THREAD

**Issue by TimDaub** [ethereum/web3.js#5350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm attempting to parse EIP721 event logs using `decodeLog` using `web3-eth-abi@1.4.0`. I've not added `indexed: true` to the event's parameters, the entire code is here: https://github.com/neume-network/strategies/compare/bug/web3-decode-log

And I think that the following error message isn't descriptive as decodeLog I think, doesn't even use gas.

```
Error {
    message: 'Returned values aren\'t valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.',
  }
```

### Expected Behavior

The error message should be "decodeLog failed to parse message" or something that identifies that decodeLog failed.

### Steps to Reproduce

see here: https://github.com/neume-network/strategies/compare/bug/web3-decode-log

### Web3.js Version

web3-eth-abi@1.4.0

### Environment

- Operating System: mac os x
- Browser: 
- Node.js Version: v14.20.0
- NPM Version: 6.14.17

**Comment by Muhammad-Altabba** [comment]
Hello @TimDaub 
Sorry, as you are using `import { decodeLog } from "eth-fun";` this means you need to open the found issue at `fun-eth`. They are the only ones who can show something like what you are asking for: `"decodeLog failed to parse message"`.

**Comment by TimDaub** [comment]
I'm the maintainer of eth-fun and I just proxy web's method

**Comment by TimDaub** [comment]
https://github.com/rugpullindex/eth-fun/blob/399a0cf36dfa3fc341be6098154c8d1295481f61/src/call.js#L23

**Comment by Muhammad-Altabba** [comment]
Ok, sorry, I see now. Let us check more on this...

**Comment by TimDaub** [comment]
:) happy to send a pr if u point me to the code

**Comment by Muhammad-Altabba** [comment]
Sorry @TimDaub that changing an error message would break some applications that check for that specific message. And for that we would need to upgrade the version. But we are currently avoiding this in version 1.x as we try to include only minor or patch PRs ( major.minor.patch ). And our focus now is on version 4.x. And its Alpha version is very close....

However, for your case, I would suggest that you catch the error message from Web3 and then raise it with a different error message.

**Comment by TimDaub** [comment]
it seems you're using semversioning wrong. I know this buggy error message since 2019 and it has always been terrible. I guess eventually people will just migrate further to ethers and other places. I wish you'd bravely fix bugs rationally and upgrade the major version number as semver is supposed to work.

**Comment by Spacesai1or** [comment]
@TimDaub If we were to include the change you're requesting and bump the major version of Web3.js, we would then have three separate versions to maintain: 1.x, 4.x, and the 5.x you're requesting. If we were to implement every breaking change suggested by users, then we'd have many more versions to maintain and it becomes unwieldy

Web3.js is an old code base (released in 2015), there's a lot that has changed in both Ethereum and JavaScript since and there are many improvements to be made, including better error messages. We as a team have decided to try to include as many of these suggested improvements into the 4.x rewrite, so that users only have to make the switch from version 1.x to 4.x, and maintainers only need to maintain two different releases (1.x and 4.x)
