### ISSUE TITLE
Publish 4.x doc on tag push

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#5397]
- [ ] Publish doc on tag push only

**Comment by mconnelly8** [comment]
Hey @luu-alex, can you provide some input on level of effort and impact for this?

**Comment by luu-alex** [comment]
We wont be able to publish docs on tag push, this is one of the limited features with using render and discussed this with Junaid already. We will need a discussion on how to move forward because this can be solved in different ways. This can be solved with creating a branch just to update documentation, but requires discussion as this moves in the territory of having a dev branch.

**Comment by jdevcs** [comment]
docs are updated auto with every merge.
