### ISSUE TITLE
Add proxy support for web3 WebsocketProvider

### ISSUE THREAD

**Issue by yasmineSidhom** [ethereum/web3.js#5468]
Since Web3 **HttpProvider** is now **deprecated** I switched to **WebsocketProvider**.
In the past I used to have:

**const web3Provider = new Web3.providers.HttpProvider(PROVIDER_URL);
web3Provider.httpAgent = new HttpsProxyAgent(PROXY_URL);**

But I can’t figure out **how to use WebsocketProvider behind a proxy** and I  can't find any documentation about that.
My instance is in a private subnet and I need to configure the proxy at the application level.

#### Environment
Node, web3.js, ubuntu

**Comment by Spacesai1or** [comment]
Hi there, what made you believe `web3-providers-http` is deprecated? It's still being maintained and the latest version is `1.9.0`

If you had a working setup before attempting to make a switch to `web3-providers-ws`, please try reverting back to that setup with the latest version of `web3-providers-http` and let us know if you're running into any issues

**Comment by mconnelly8** [comment]
@yasmineSidhom, since we didn't hear back with more information, we are closing this issue and recommend upgrading to the recently released v4 production version.

https://docs.web3js.org/
https://docs.web3js.org/guides/web3_upgrade_guide/x/
https://www.npmjs.com/package/web3/v/4.0.1
https://github.com/web3/web3.js/releases/tag/v4.0.1
