### ISSUE TITLE
Fix validator for overloaded solidity functions

### ISSUE THREAD

**Issue by avkos** [ethereum/web3.js#5486]
Fix validator to understand overloaded solidity functions. For example contract ERC721 has the method `safeTransferFrom` with constructors:

```solidity 
safeTransferFrom(address from, address to, uint256 tokenId)
safeTransferFrom(address from, address to, uint256 tokenId, bytes _data)
```

So, the validator should understand which of the following constructs it needs to validate.

#### Expected behavior

- Should be possible to call (and validate) function with the 4th param:
`contract.methods.safeTransferFrom(address, toAddress, tokenId, utf8ToHex('1'))`

- Should be possible to call (and validate) the function without the 4th param:
`contract.methods.safeTransferFrom(address, toAddress, tokenId)`

#### Actual behavior
- Should be possible to call (and validate) function with the 4th param:
`contract.methods.safeTransferFrom(address, toAddress, tokenId, utf8ToHex('1'))` - works

- Should be possible to call (and validate) the function without the 4th param:
`contract.methods.safeTransferFrom(address, toAddress, tokenId)` - throw error

**Comment by jdevcs** [comment]
Related: 
https://github.com/web3/web3.js/issues/5438
https://github.com/web3/web3.js/issues/5207

**Comment by nikoulai** [comment]
The problem seems to break down to this line: 

https://github.com/web3/web3.js/blob/40b00ffa640c584afdbf6f55e5589b6c68090e47/packages/web3-eth-contract/src/contract.ts#L922

We process the abi fragments in a for loop, and we keep the property/function of `abi.name` in `_methods` only for the last processed abi fragment. 

One solution could be to group fragments by their name and create corresponding functions, which could run each of the possible overloads. 
I see a problem in that, when there are `abi`s withe the same name but different type(function, error, event). But, I think, this mix is not possible in solidity.
