### ISSUE TITLE
Some default properties cannot be set from `Contract` class

### ISSUE THREAD

**Issue by nikoulai** [ethereum/web3.js#5603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

During writing some tests for contract `defaults`, noticed that `defaultCommon` and `defaultHardfork` didn't set properly from the `Contract` class and updated to the instance of the class.

### Expected Behavior

The values setted in the `Contract` class should be present in the instance, too.

### Steps to Reproduce

Run the two commented tests in `packages/web3-eth-contract/test/integration/contract_defaults_extra.test.ts`

### Web3.js Version

4.0.1-alpha.1

### Environment

- Operating System:  macOs
- Browser: 
- Node.js Version: v16.14.2
- NPM Version: 8.5.0

**Comment by Muhammad-Altabba** [comment]
This could be because of the same root problem of https://github.com/web3/web3.js/issues/5433

**Comment by Muhammad-Altabba** [comment]
Hello all,
I was trying to do simple modifications to make things works for the `defaultCommon`. But it seems to need more refactoring. So, I am closing my MR (https://github.com/web3/web3.js/pull/5688) and I think we need to do it some other way. (Additionally, I am unassigning this issue from me since I will be on vacation. But, I think the one who will take it would treat it as a fresh task but with some insights)

I think the configurations are better to be totally refactored to have:
- The default values are to be provided for example from .env file (instead of the current situation where there are some hardcoded strings inside `_config` object.
- Clean all the subclasses that inherit from `Web3Config` from  duplicated properties (see an example at: https://github.com/web3/web3.js/pull/5688/files#diff-7fa8f782e68ce845dbb6e8446b86041697fa427db5485b9c63bf689d0b32ed81L455 and https://github.com/web3/web3.js/pull/5688/files#diff-5e56e7b4c4229c78c1bea8ddfb8baaa68f22a7f07d5efcd78d2e5c56eb014410R455) As in the referenced lines we can read from the base class the value of a static property from the subclass.
- We may need to have a way to determine if the value set is the non-changed default, or if it is later assigned. Because, if it is later assigned to have the exact same value on the instance level, we need to persist this assignment if there was another value assigned on the class static properties level.

The above are just some thoughts. The one who works on this would probably need to do it this was or totally another :smile:.

**Comment by Spacesai1or** [comment]
Maybe [this](https://github.com/web3/web3.js/issues/5492#issuecomment-1341973425) comment could also be addressed during this refactor
