### ISSUE TITLE
"error" PromiEvent does not catch the error from send()

### ISSUE THREAD

**Issue by yanikitat** [ethereum/web3.js#5670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a such code snippet where I'm getting the EVM exception:
```Typescript
  await liquidityStorager.methods
    .redeem(sender, 100, "0x00")
    .send({from: sender, gas: 70000})
    .on("error", (e: Error) => console.log("on.error-->", e));
```
When I'm getting EVM exception, I'm getting this as JavaScript exception, not in the `.on("error")` function (I have removed a lot of not important info from logs):
```
.../node_modules/web3-core-helpers/lib/errors.js:80
        var error = new Error('Transaction has been reverted by the EVM:\n' + JSON.stringify(receipt, null, 2));
                    ^

Error: Transaction has been reverted by the EVM:
{
 "Correct transaction receipt here"
}
    at Object.TransactionRevertInstructionError (.../node_modules/web3-core-helpers/lib/errors.js:80:21)
    at .../node_modules/web3-core-method/lib/index.js:384:65 {
  reason: 'LS001',
  signature: 'Error(String)',
  receipt: {
 "Correct transaction receipt again"
  }
}
```
But! When I'm adding the `.catch()` to the my snippet:
```Typescript
  await liquidityStorager.methods
    .redeem(sender, 100, "0x00")
    .send({from: sender, gas: 70000})
    .on("error", (e: Error) => console.log("on.error-->", e))
    .catch((e: Error) => console.log("catch -->", e));
```
I'm not getting the exception anymore, but my error is written twice: from `.on("error", ...)` and `.catch(...)`:
```
catch --> Error: Transaction has been reverted by the EVM:
{
 "Correct transaction receipt here"
}
    at Object.TransactionRevertInstructionError (.../node_modules/web3-core-helpers/lib/errors.js:80:21)
    at .../node_modules/web3-core-method/lib/index.js:384:65 {
  reason: 'LS001',
  signature: 'Error(String)',
  receipt: {
 "Correct transaction receipt again"
  }
}
on.error--> Error: Transaction has been reverted by the EVM:
{
 "Correct transaction receipt here"
}
    at Object.TransactionRevertInstructionError (.../node_modules/web3-core-helpers/lib/errors.js:80:21)
    at .../node_modules/web3-core-method/lib/index.js:384:65 {
  reason: 'LS001',
  signature: 'Error(String)',
  receipt: {
 "Correct transaction receipt again"
  }
}
```

### Expected Behavior

Maybe I didn't catch how PromiEvent "error" works but I expect that I will get the error message from `.on("error", ...)` function and not as the JavaScript exception. Something like this:
```Typescript
  await liquidityStorager.methods
    .redeem(sender, 100, "0x00")
    .send({from: sender, gas: 70000})
    .on("error", (e: Error) => console.log("on.error-->", e));
```
```
on.error--> Error: Transaction has been reverted by the EVM:
{
 "Correct transaction receipt here"
}
    at Object.TransactionRevertInstructionError (.../node_modules/web3-core-helpers/lib/errors.js:80:21)
    at .../node_modules/web3-core-method/lib/index.js:384:65 {
  reason: 'LS001',
  signature: 'Error(String)',
  receipt: {
 "Correct transaction receipt again"
  }
}
```

### Steps to Reproduce

I have attached snippet codes below

### Web3.js Version

1.8.0

### Environment

- Operating System: Linux Mint 21 Cinnamon
- Browser: --
- Node.js Version: v16.18.0
- NPM Version: 8.19.2

### Anything Else?

Also In the docs I found this: https://web3js.readthedocs.io/en/v1.8.0/web3-eth-contract.html#methods-mymethod-send
```
.on('error', function(error, receipt) { // If the transaction was rejected by the network with a receipt, the second parameter will be the receipt.
    ...
})
```
But I'm getting TS error when I'm trying to add `receipt: TransactionReceipt` as the second callback arg:
```Typescript
  await liquidityStorager.methods
    .redeem(sender, 100, "0x00")
    .send({from: sender, gas: 70000})
    .on("error", (e: Error, receipt: TransactionReceipt) => console.log("on.error", e));
```
```
  The last overload gave the following error.
    Argument of type '(e: Error, receipt: TransactionReceipt) => void' is not assignable to parameter of type '(error: string | object | Error | TransactionReceipt) => void'.

93     .on("error", (e: Error, receipt: TransactionReceipt) => console.log("on.error", e));
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
It seems like types doesn't have a correct overload for "error" PromiEvent with `receipt: TransactionReceipt`

**Comment by Spacesai1or** [comment]
Hi there, thank you for bringing this to our attention!

I think you're correct in how you expect `.on('error')` to work, and this definitely seems like a bug

Regarding the TypeScript issue, the type declaration files were generated manually (as the library is written in JS) a while ago, and haven't been updated because doing so would break the code of pretty much every Web3js user using TypeScript. So, unfortunately, we've refrained from making changes to the type declaration files for `1.x` and have instead been working on a complete rewrite of the library that's written in TypeScript so errors like what you've reported can't exist. Currently the rewrite (`v4.x`) of the library is an alpha and we're looking to get out the production release Soon™

**Comment by yanikitat** [comment]
Thanks a lot for feedback! @spacesailor24 
Should I do anything else regarding the `.on('error')` issue? If you need any additional info you can ping me in the future:)

Regarding the TypeScript issue, I thought that we can just add another one type for `.on("error")`, something like this:
```
    on(type: 'error', handler: (error: Error) => void): PromiEvent<T>; // <-- this is existing type

    on(type: 'error', handler: (error: Error, receipt: TransactionReceipt) => void): PromiEvent<T>; // <-- this is the new type
```
So I think that it should not to break the code.
But, If you are saying that you are planning to rewrite the whole library to the typeScript, so then it's not relevant:D

**Comment by mconnelly8** [comment]
From 5/30/23 meeting, need to investigate in 4.x to confirm valid alternative.

**Comment by Spacesai1or** [comment]
Hi there, apologies it's been so long since you've heard back from any of us. Since the last update, we've officially released version 4.x of the library, and we've tested that `.on('error' ...)` works as expected

`receipt` is also available for the `error` event, however, depending on the client software running for your provider, the transaction may be reverted before actually being submitted to the network. In my testing, Geth seems to "simulate" the transaction before submitting it to the network. So, when calling a contract method that reverts, I received the revert error without a transaction receipt, because Geth ran the transaction against its instance of the EVM and returned the revert message without sending it to the network. However, some client software doesn't do this, including testing software such as Hardhat and Ganache. With Hardhat I received a transaction hash, and with Ganache and Nethermind the receipt was returned as expected

I'll check with the team, but since we've officially released version 4.x, I don't think we're going to fix this bug in 1.x, and will instead recommend you migrate to 4.x
