### ISSUE TITLE
Remove swarm and bzz 

### ISSUE THREAD

**Issue by sambacha** [ethereum/web3.js#5720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Request

If we look at swarm dependency we find:

> This library isn't (sic) activelly maintained as I moved on to other things. If you'd like to maintain it, please let me know. For > now, I think I can point to Erebos: https://erebos.js.org/
[swarm-js](https://www.npmjs.com/package/swarm-js) or repo: https://github.com/VictorTaelin/swarm-js 

many thanks to @VictorTaelin for maintaining this for all this time. Swarm is migrating to waku, and such this should be removed.  

### Use Cases

This currently poses a security risk

### Implementation Ideas

rm -rf web3-swarm

### Are you willing to implement this feature?

- [X] Yes

**Comment by VictorTaelin** [comment]
As far as I know, that swarm-js repo isn't maintained since I left the Ethereum Foundation (about 4 years ago now?) and should never be depended on.

**Comment by sambacha** [comment]
> As far as I know, that swarm-js repo isn't maintained since I left the Ethereum Foundation (about 4 years ago now?) and should never be depended on.

Thanks for the additional information, even more of a reason to remove it entirely: it has gone unnoticed through all this time, meaning no one is using it in all likelihood. 

This should make maintaining web3js easier, perhaps @luu-alex or another maintainer can help expedite this. 

Cheers,

Sam

**Comment by luu-alex** [comment]
Hi there @sambacha i'd completely agree that removing swarm and bzz would be the way forward. Due to semver and how were still using the 1.x version for web3js we cant have any breaking changes or at the very least only break changes when its neccesary. Fortunately we have an updated [4.0.2 alpha version of web3js](https://github.com/web3/web3.js/tree/4.x) that does not include bzz or swarm.  I'll bring this up with the team and see how we can move forward and if you have anymore suggestions feel free to let me know. As well for my knowledge, how does swarm migrating to waku pose a security risk
