### ISSUE TITLE
Race condition in filter.watch()

### ISSUE THREAD

**Issue by mkalinin** [ethereum/web3.js#573]
It reproduces from time to time, more frequent on a slow network. The problem is in these [two lines](https://github.com/ethereum/web3.js/blob/develop/lib/web3/filter.js#L185-L186). Some times `pollFilter` request is processed before `getLogsAtStart` which turns with double passing of same log entries to `watch` callback. Looks like `pollFilter` should run inside a callback to `getLogsAtStart`.

**Comment by frozeman** [comment]
Thats a good point, and its the same behaviour in the 1.0 branch.
The reasoning is that you want to receive logs immediately after you call filter.watch().
Otherwise it would have to wait for the return of past logs, which can take up to a few seconds before watching for incoming ones.

Concerning the double returning, that might be an issue with geth, which actually could be seen as a feature, that it returns you up to the latest, even when you call was made a few seconds before.

I will think about reversing this logic and nesting it in the 1.0 branch

**Comment by mkalinin** [comment]
I forgot to mention that this behavior can be recreated when filter's `fromBlock` is set to `earliest` or `0`. That is not quite clear what data should be returned by [eth_getFilterChanges](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getfilterchanges) during the first poll. If we assume that first poll should return all logs then we get a duplication if `eth_getFilterChanges` was responded first. But if first poll should return an empty array of logs then there will be no duplicates with our conditions.

**Comment by robertmagier** [comment]
Is there any update on this issue ? I am experiencing exactly this problem not sure what to do.

**Comment by frozeman** [comment]
Could you use the 1.0 branch and see if it’s a problem there? If so PRs are welcome :) I’m on holidays the next two weeks so I won’t be able to take a look soon.

**Comment by nionis** [comment]
I am not sure if I understand the issue correctly, here is what I discovered:

my server uses 2 ways of receiving events, which are running in parallel:
1. `contract.events.allEvents().on("data", ..);`
2. `contract.getPastEvents("allEvents", { fromBlock: x, toBlock: "latest" })` (loops every 10 seconds)

sometimes the log id received from method 2 is different from what was received from method 1, this happens when method 2 is running at the same time when method 1 is sending the event

web3: 1.0.0-beta.29
geth: 1.7.3

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
