### ISSUE TITLE
Invalid `from`/`to` when sending transaction results in incorrect error

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#5831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```typescript
const transaction: Transaction = {
	from: tempAcc.address,
	to: '0x00000000000000000000000000000000000000000',
	value: BigInt(99999999999999999999999999999999999999999999999999999999999999),
}
try {
	await web3Eth.sendTransaction(transaction);
} catch (error) {
	console.log(error)
}
```

The submitted transaction has an invalid `to` address (one extra `0`, so the address is too long) that should cause web3.js to throw a validation error, but instead the following error is thrown:

```
LocalWalletNotAvailableError: Invalid value given "LocalWalletNotAvailableError". Error: Attempted to index account in local wallet, but no wallet is available.
      {
        innerError: undefined,
        code: 429
      }
```

### Expected Behavior

A validation error should be thrown saying `to` is an invalid address

### Steps to Reproduce

```typescript
const transaction: Transaction = {
	from: tempAcc.address,
	to: '0x00000000000000000000000000000000000000000',
	value: BigInt(99999999999999999999999999999999999999999999999999999999999999),
}
try {
	await web3Eth.sendTransaction(transaction);
} catch (error) {
	console.log(error)
}
```

### Web3.js Version

4.x

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version: 

### Anything Else?

Incorrect error is reported for `from` field as well

**Comment by nikoulai** [comment]
The issue seems to be in [getTransactionFromOrToAttr](https://github.com/web3/web3.js/blob/e17258561d0cb16efa6822334a984054acc56665/packages/web3-eth/src/utils/transaction_builder.ts#L60). Actually, a [validation takes place](https://github.com/web3/web3.js/blob/e17258561d0cb16efa6822334a984054acc56665/packages/web3-eth/src/utils/transaction_builder.ts#L71) and fails, so it is assumed that a number (index of wallet) is passed. 
The argument is a `hex string` so the validation passes (if number is passed) and during look-up, no such index is found and `LocalWalletNotAvailableError` is thrown.

Some possible solutions would be:
- Don't allow `hex strings` for indexing wallet (change [condition](https://github.com/web3/web3.js/blob/e17258561d0cb16efa6822334a984054acc56665/packages/web3-eth/src/utils/transaction_builder.ts#L74)
- Declare an arbitrary max size of wallet ( not so good IMO)
- merge `InvalidTransactionWithSender`/ `InvalidTransactionWithReceiver` with `LocalWalletNotAvailableError` into another error for this case.

What do you think?

**Comment by Spacesai1or** [comment]
@nikoulai I think disallowing hex strings as wallet indexes is the best solution, I don't think that intended functionality anyways

**Comment by Spacesai1or** [comment]
Or if the passed hex string is 42 characters long and starts with `0x`, we can assume it's intended to be an address, otherwise treat it as an index

**Comment by nikoulai** [comment]
> Or if the passed hex string is 42 characters long and starts with `0x`, we can assume it's intended to be an address, otherwise treat it as an index

I think that's the case now, it's a 43-length string, `isAddress` returns `false` and `isNumber` `true` and there is no such index in the local wallet.


The reason I made the second proposal, is because I had in mind that strings with lengths around 42 chars are not meant to be used as indexes, but are falsy addresses.

Or you meant something else?

**Comment by Spacesai1or** [comment]
@nikoulai Whoops didn't re-read this part

>The submitted transaction has an invalid to address (one extra 0, so the address is too long) that should cause web3.js to throw a validation error

I revert back to disallowing hex strings as numerical wallet indexes, if `isHexString && !isAddress` then thrown invalid address error, but this is of course what I think - need feedback from others

**Comment by Spacesai1or** [comment]
I think your third proposal using `LocalWalletNotAvailableError` is a good idea too, but I don't think it makes sense to allow users to index the wallet with a hex string, like logically I don't know why any average user would want to do such a thing

**Comment by nikoulai** [comment]
> I think your third proposal using `LocalWalletNotAvailableError` is a good idea too, but I don't think it makes sense to allow users to index the wallet with a hex string, like logically I don't know why any average user would want to do such a thing

yep I agree with you, it doesn't make a lot of sense to pass a hex string for indexing.
