### ISSUE TITLE
WebsocketProvider keeps important error messages back.

### ISSUE THREAD

**Issue by nivida** [ethereum/web3.js#5835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It would be great if we would get the errors with their description from the underlying ``websocket`` package shown to us. 

### Expected Behavior

I do get the underlying errors displayed.

### Steps to Reproduce

Try to connect to a WS endpoint where the upgrade is failing. Basically, all error cases where [this](https://github.com/theturtle32/WebSocket-Node/blob/master/lib/WebSocketClient.js#L335) method is used would provide helpful details. Same for [this case](https://github.com/theturtle32/WebSocket-Node/blob/master/lib/WebSocketClient.js#L225).

### Web3.js Version

<=1.8.x

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version:

**Comment by nikoulai** [comment]
In `web3.js` [W3CWebSocket](https://github.com/theturtle32/WebSocket-Node/blob/master/lib/W3CWebSocket.js) is [used](https://github.com/web3/web3.js/blob/e4b25bfdcd7fc7b6b2baf800d7812ff6769dcbaa/packages/web3-providers-ws/src/index.js#L28) instead of the `WebsocketClient`. Although `WebSocketClient` is used under the hood, whenever it receives a connection error, it [throws an error](https://github.com/theturtle32/WebSocket-Node/blob/master/lib/W3CWebSocket.js#L216) without passing any additional information the user. 

Inside `WebsocketProvider`, we cat directly listen to `connectFailed` events using the `_client`, like 
`this.connection._client.on('connectFailed', (event)=>{...});`
However, this would lead to duplicate events (`error` + `connectFailed`) triggered. 

Please share your opinions on the topic.
