### ISSUE TITLE
Bacth Request add guide missing in v4.0.1-rc.0

### ISSUE THREAD

**Issue by p14041999** [ethereum/web3.js#5975]
#### Expected behavior
Getting `.request` not a function error while adding request to batch request

`batch.add(web3rpc.eth.getTransactionReceipt.request(el.hash,console.log))`

Output
```bash
/Users/pralay/Projects/Explorer/src/packages/transaction/index.ts:8
    txs.forEach((el,i)=>{
        ^
TypeError: web3rpc.eth.getTransactionReceipt.request is not a function

```

#### Actual behavior
In older version(i.e. 1.x), there was no issue adding such request

#### Steps to reproduce the behavior

1. Change version to 4.0.1-rc.0
2. Add a batch request for and quantity.
3. Try running it

I have'nt find any related article on how to do it in 4.x ....

**Comment by nikoulai** [comment]
Hey @p14041999 , thanks for reaching out! We'll look into this and let you know soon!

**Comment by nikoulai** [comment]
Generally the `request` functionality is missing from the `eth` methods. The request function returns a `payload` object with the parameters passed and the rpc method to be called. 
For example
```js
{
  method: 'eth_sendTransaction',
  params: [
    {
      from: '0xc81e13ee8c58bceb43b2688d23f69e9bd847121c',
      to: '0xc81e13ee8c58bceb43b2688d23f69e9bd847121c',
      value: '0x16345785d8a0000'
    }
  ],
  callback: undefined,
  format: [Function: bound ]
}
```

In `1.x` every eth method is [Method](https://github.com/web3/web3.js/blob/1.x/packages/web3-core-method/src/index.js#L34) and `request` is a property of `Method`. Also, `method` (web3apimethod) is a  property of `Method`,too.

In `4.x` which `method` is to be executed is not known until the processing has arrived at [eth_rpc_methods](https://github.com/web3/web3.js/blob/8caf927443893c41d80ae365c309856ce4632bff/packages/web3-rpc-methods/src/eth_rpc_methods.ts#L46-L45). So the implementation can't be so straight forward.

One downside of `1.x` implementation is that the parameters passed are not processed and just returned. This could be an issue, for example, when a user passes an index of the local wallet for the `sendTransaction` method. (Would expect to return the payload with the address not the index).

My first thought, is to implement the `request` property on the `eth` functions and add an optional parameter on the `eth_rpc_methods` methods and when passed, they would return the request instead of sending it. 

Your feedback would be helpful (@web3/web3-js ) :)

**Comment by jdevcs** [comment]
Thanks @nikoulai for your findings. Currently `.request` is missing in 4.x and users can send batch like:
```
const request1 = {
			id: 1,
			method: 'eth_getBalance',
			params: ['0x0000000000000000000000000000000000000000', 'latest'],
		};
		const request2 = {
			id: 2,
			method: 'eth_getBalance',
			params: ['0x2424000000000000000000000000000000000000', 'latest'],
		};

		const batch = new web3.BatchRequest();
		const request1Promise = batch.add(request1);
		const request2Promise = batch.add(request2);

		const executePromise = batch.execute();
		const response = await Promise.all([request1Promise, request2Promise, executePromise]);
```
But its not good way for end users, and we should have `.request` in 4.x for returning raw JSON RPC data so users can use it in batch.

**Comment by Muhammad-Altabba** [comment]
Hello @nikoulai 
What is the related PR for this?
Thanks,

**Comment by nikoulai** [comment]
> Hello @nikoulai What is the related PR for this? Thanks,

There is no PR for this. Only the investigation. I think we need a new issue for the actual implementation of the feature.

**Comment by Muhammad-Altabba** [comment]
> > Hello @nikoulai What is the related PR for this? Thanks,
> 
> There is no PR for this. Only the investigation. I think we need a new issue for the actual implementation of the feature.

Thanks @nikoulai , I saw it in the "Review" column and you are the assignee :smile:

**Comment by jdevcs** [comment]
@p14041999 There is migration guide section in 4.x for batch requests, https://docs.web3js.org/docs/guides/web3_migration_guide#web3-batchrequest

Currently its different from 1.x and is breaking change, but after full 4.x release we will plan to add more features for multicall.

**Comment by jdevcs** [comment]
So for now users can use above mentioned way for batch requests or for multiple function calls can use `Promise.all()`, 
let us know if there are any specific scenarios that above mentioned are not useful for.
