### ISSUE TITLE
4.x - min.js build error 

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#5994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1746" alt="Screenshot 2023-04-06 at 1 36 12 AM" src="https://user-images.githubusercontent.com/29740020/230281361-8c54c197-af06-46be-b1b6-72dbd25f8f8a.png">
running into a build error with CRA. browser build issue that needs to be investigated

### Expected Behavior

Should work fine

### Steps to Reproduce

create CRA project with 4.x

### Web3.js Version

4

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version:

**Comment by jdevcs** [comment]
Seems create react app doesn't fully support ESM out of box. https://github.com/facebook/create-react-app/issues/10933 
@luu-alex can you force via config to load CJS from 4.x lib or try https://www.npmjs.com/package/react-app-rewired-esm 

Its due to ESM, fully qualified names are required in our lib code and we can hint node for that using  `--experimental-specifier-resolution=node` https://github.com/web3/web3.js/pull/5904#issuecomment-1470199054 , but in case of CRA its not considering this flag.

**Comment by luu-alex** [comment]
<img width="1055" alt="Screenshot 2023-05-31 at 4 45 47 PM" src="https://github.com/web3/web3.js/assets/29740020/efea9660-5c9d-49c3-938e-be6451825aeb">
Now we stopped running into esm issues, its back being polyfill errors like in 1.x, i think we could get rid of the polyfills after the release and work on that. not sure how hard that would be, i think marin said it might take some work. 

I dont think forcing cjs will work since its a polyfill issue, I think if people want to use web3js in CRA or angular we can provide them a cdn min.js build. thoughts?

**Comment by luu-alex** [comment]
esm issue is now fixed, Created new issue to remove the polyfills
