### ISSUE TITLE
Error: "n.data.substring is not a function", when setting web.eth.handleRevert = true

### ISSUE THREAD

**Issue by mconnelly8** [ethereum/web3.js#6007]

**Comment by mconnelly8** [comment]
#5999

**Comment by Muhammad-Altabba** [comment]
Turned out that MetaMask sometimes returns the `data` inside `originalError`. As mentioned here: https://github.com/web3/web3.js/issues/4454#issuecomment-1485953455 

So, this issue would be about implementing the same as https://github.com/web3/web3.js/pull/5962 but for [version 4.x](https://github.com/web3/web3.js/tree/4.x)

And here is the place where the modifications are needed:
https://github.com/web3/web3.js/blob/137542aefef58d472da2a9fdf1c5bbebcd9c5752/packages/web3-eth-abi/src/decode_contract_error_data.ts#L41
