### ISSUE TITLE
Migrate Truffle project to 4.x for testing purposes

### ISSUE THREAD

**Issue by mconnelly8** [ethereum/web3.js#6011]

**Comment by nikoulai** [comment]
The PR in the truffle repo: https://github.com/trufflesuite/truffle/pull/6013

**Comment by nikoulai** [comment]
In a couple of instances `dom` [ had to be added](https://github.com/trufflesuite/truffle/pull/6013/files#diff-ca466f27a03b5389fa8175a306645989215a52ac35e0030732491cb11050e634R13) as a required lib at the package, because the type `RequestInit` couldn't be found. This solution was proposed [here](https://github.com/jasonkuhrt/graphql-request/issues/26#issuecomment-354482903).  (Also see [this](https://github.com/jasonkuhrt/graphql-request/issues/26#issuecomment-364379794))
IMO users should just get `web3js` without having to make any changes in their `libs` and this case should be handled by our side.

**Comment by jdevcs** [comment]
This issue was created for older 4.x testing with truffle, and next RC/Full release should be tested and tracked under https://github.com/web3/web3.js/issues/6144
