### ISSUE TITLE
Errors in `web3.js-plugin-chainlink`

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#6135]
- [Black box tests](https://github.com/ChainSafe/web3.js-plugin-chainlink/actions/runs/5135585359/jobs/9241245341?pr=19#step:4:113) failing with `ContractExecutionError: Error happened while trying to execute a function inside a smart contract`
- [Browser tests](https://github.com/ChainSafe/web3.js-plugin-chainlink/actions/runs/5135585359/jobs/9241244581?pr=19#step:7:17) failing with `The cypress npm package is installed, but the Cypress binary is missing.`

**Comment by Muhammad-Altabba** [comment]
I noticed that the black box test does not always show up.

And the cypress error does not show locally and it is present only in GitHub actions. And it could be because of a configuration issue that happens because Cypress is not able to locate its cashing directory (this is according to a fast investigation).

**Comment by Muhammad-Altabba** [comment]
[UPDATED]

The Cypress issue has been fixed: https://github.com/ChainSafe/web3.js-plugin-chainlink/pull/20#issuecomment-1575477408

And the other error has been fixed in: https://github.com/ChainSafe/web3.js-plugin-chainlink/pull/24
