### ISSUE TITLE
Web3 4.x Testing with Truffle

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#6144]
- [ ] Migrate Truffle to the latest 4.x release and share any bugs discovered.

**Comment by Muhammad-Altabba** [comment]
Related MR: https://github.com/trufflesuite/truffle/pull/5393

**Comment by Muhammad-Altabba** [comment]
As communicated with the team, I am closing this issue. However, the Truffle upgrade to 4.x is still in progress...

For reference, the following 10 issues were created during this task:
- [The returned value of .request(...) method at the providers does not comply with EIP-1193](https://github.com/web3/web3.js/issues/6345#top)
#6345
- [When formatting a transaction in 4.x, it it not more set to null if not provided or invalid](https://github.com/web3/web3.js/issues/6332#top)
#6332 
- [Update documentation according to #6294](https://github.com/web3/web3.js/issues/6330#top)
#6330 
- [soliditySha3 behaves differently on 4.x when one of the values is BN or a string that contains a number](https://github.com/web3/web3.js/issues/6327#top)
#6327
- [When an error is thrown during a transaction the object error.receipt is undefined.](https://github.com/web3/web3.js/issues/6320#top)
#6320 
- [contract.address has the checksum in version 4.x but was not in 1.x](https://github.com/web3/web3.js/issues/6318#top)
#6318 
- [Passing {gas: some_value} to smart contract function call causes it to never return](https://github.com/web3/web3.js/issues/6317#top)
#6317 
- [Not calling provider.disconnect() causes the execution to never end](https://github.com/web3/web3.js/issues/6316#top)
#6316 
- [The returned logs of a contract event are not of an event object](https://github.com/web3/web3.js/issues/6312#top)
#6312 
- [Getting a transaction confirmation seems to take longer than it is supposed to](https://github.com/web3/web3.js/issues/6311#top)
#6311 

And during the work on this task, multiple commits were pushed to the MR https://github.com/trufflesuite/truffle/pull/5393. Those commits were mainly:
- Fix Quorum overrides according to 4.x and fix the Quorum decodeParameters tests
- Updated some codes for the breaking changes of stuff like: 
  - The callbacks has been replaced with promises.
  - Closing a provider after finishing.
  - The tx.to field will be `undefined` if not provided instead of being `null` in 1.x.
  - The response object of an RPC call will contain the result inside `response.result`.
- Restores some needed files that has been deleted by mistake (restored in [commit](https://github.com/trufflesuite/truffle/pull/5393/commits/abfd7eeecb743f5114bc0b85bfd47966cb1b8491))
- Increase many tests' timeouts (also an issue was created to investigate).
- Handle addresses differences related to checksum
- Update web3.js from 4.0.1-rc.1 to 4.0.3 and unskip some tests that are now running with 4.0.3.
- Added a TODO comment for every related issue of the above 10 mentioned issues.

Another follow-up task will be created to continue working on the upgrade.

**Comment by Muhammad-Altabba** [comment]
Here are the issues rearranged according to their priorities.

Blockers:

- #6327
- #6312 

- #6320 
  - Related: #6440 (Thanks for @jdevcs for discovering this)

High priority:

-  #6345

Low priority:
-  #6317 
-  #6316
-  #6311 

Just need a Documentation update:
-  #6332 
-  #6330 
-  #6318

**Comment by Muhammad-Altabba** [comment]
It turns out that https://github.com/web3/web3.js/issues/6317 is also a blocke as setting the gas is needed to create some of the scenarios at the tests.
