### ISSUE TITLE
Batch. Request invalid request 

### ISSUE THREAD

**Issue by ppegu** [ethereum/web3.js#6164]
const batch = new web3.BatchRequest();

    const request1 = {
      jsonrpc: "2.0",
      id: 10,
      method: "eth_getBalance",
      params: ["0x*****", "latest"],
    };

    batch.add(request1);

    const responses = await batch.execute();

    console.log(responses);

 innerError: { code: -32600, message: 'invalid request' },

**Comment by Muhammad-Altabba** [comment]
Hello @ppegu ,
Thanks for opening an issue. However, could you please let us know what is the version you are using? And the exact value for the request1 params. And the full error message with its stack trace.
Thanks,

**Comment by jdevcs** [comment]
In 4.x if there is 1 request added in batch, the bug is [here](https://github.com/web3/web3.js/blob/6192d6f19ade5b1a0183aa1d01fc07135108202c/packages/web3-core/src/web3_request_manager.ts#L192) as` jsonRpc.isBatchRequest(request) `returns false and its processed request output is : 
```
{
  jsonrpc: "2.0",
  id: "2902cc2e-7be0-46cd-bb55-e53c607e29fb",
  method: undefined,
  params: undefined,
}
```

in case if there are > 1 requests added, it works fine,

**Comment by ppegu** [comment]
Oo okay Thanks

**Comment by jdevcs** [comment]
@ppegu Thanks for testing 4.x,
If you have time you may open a PR for it or one of our team member will fix it.

**Comment by ppegu** [comment]
Sure i will. Thanks Again

**Comment by luu-alex** [comment]
PR created, thank you for finding this! #6166
