### ISSUE TITLE
input parameter added when calling estimateGas for a specific contract call in v4.0.1

### ISSUE THREAD

**Issue by eshaben** [ethereum/web3.js#6183]
#### Expected behavior

When calling `estimateGas` for a contract deployment it should use the `data` parameter only to estimate gas and should not use an `input` parameter. Take the following [example on the docs site](https://docs.web3js.org/guides/basics/eth#step-3-interact-with-the-ethereum-blockchain-using-web3js):

```js
    // Example from wbe3.js docs site
    let contract = new web3.eth.Contract(abi, undefined);
    const deployment = contract.deploy({
        data: '0x...', // Insert bytecode
        // @ts-expect-error
        arguments: [1],
    });
    const estimatedGas = await deployment.estimateGas(
        {
            from: acc, 
        },
        DEFAULT_RETURN_FORMAT, // the returned data will be formatted as a bigint
    );
```

This example results in the following JSON RPC call:

```
{
    jsonrpc: '2.0',
    id: '4691de88-3948-47fc-b7fe-e8bfaef6e9ba',
    method: 'eth_estimateGas',
    params: [
      {
       // Removed actual bytecode as its quite long, but its the same for both `input` and `data`
        input: '0x...',
        data: '0x...' 
      },
      'latest'
    ]
  }
```

`eth_call` and `eth_estimateGas` accept a `data` parameter, but not an `input` parameter per the [JSON-RPC API]( https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_call).

Although this doesn't cause any issue on Ethereuem, it does cause issues on Moonbeam and i'm not sure why an `input` field is automatically added, but I don't think that this should be the default behavior. 

This issue is also new as of v4.0.1, this was not an issue in v1.x

#### Steps to reproduce the behavior

To reproduce the issue, you can use the above example from your docs site and set the Web3 provider to Moonbeam or the Moonbeam TestNet, Moonbase Alpha:

```
  const web3 = new Web3('https://rpc.api.moonbase.moonbeam.network'); // Moonbase Alpha
```

#### Logs

The error is as follows:

```
InvalidResponseError: Returned error: unknown field `input`, expected one of `from`, `to`, `gasPrice`, `maxFeePerGas`, `maxPriorityFeePerGas`, `gas`, `value`, `data`, `nonce`, `accessList`, `type` at line 1 column 8
    at Web3RequestManager._processJsonRpcResponse (file:///Users/es/Documents/work/moonbeam-docs-test-suite/node_modules/web3-core/lib/esm/web3_request_manager.js:252:23)
    at Web3RequestManager.<anonymous> (file:///Users/es/Documents/work/moonbeam-docs-test-suite/node_modules/web3-core/lib/esm/web3_request_manager.js:150:29)
    at Generator.next (<anonymous>)
    at fulfilled (file:///Users/es/Documents/work/moonbeam-docs-test-suite/node_modules/web3-core/lib/esm/web3_request_manager.js:20:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  innerError: {
    code: -32602,
    message: 'unknown field `input`, expected one of `from`, `to`, `gasPrice`, `maxFeePerGas`, `maxPriorityFeePerGas`, `gas`, `value`, `data`, `nonce`, `accessList`, `type` at line 1 column 8'
  },
  code: 101,
  data: undefined,
  request: {
    jsonrpc: '2.0',
    id: '4691de88-3948-47fc-b7fe-e8bfaef6e9ba',
    method: 'eth_estimateGas',
    params: [
      {
        input: '0x...',
        data: '0x...'
      },
      'latest'
    ]
  }
}
```

#### Environment

npm v8.19.2
node v18.12.1
web3.js v4.0.1

**Comment by eshaben** [comment]
I just wanted to add that when calling `web3.eth.estimateGas(deployment)` it works without errors, so its specific to estimating gas via `contract.deploy().estimateGas()`

**Comment by Muhammad-Altabba** [comment]
Thanks @eshaben for telling us about this issue.
Feel free to open an MR, if you like to. And if not, we will take care of it :smile: .

**Comment by vlad-blana** [comment]
I have the same issue on moonbeam, with eth_call. I don't know if it uses the same code or not. I just wanted to let you know

**Comment by vlad-blana** [comment]
I got the same error but when using eth_call, on v4.0.1 and moonbeam network.

The issue seems to be located in the same place @eshaben reported.

All moonbeam rpcs seem to be stricter than any other evm chain. I wonder why the other networks don't have this issue.

Here is the error with the call stack when reading the symbol of an erc20 contract

```
node_modules/web3-core/lib/esm/web3_request_manager.js:252
                throw new InvalidResponseError(response, payload);
                      ^

InvalidResponseError: Returned error: unknown field `input`, expected one of `from`, `to`, `gasPrice`, `maxFeePerGas`, `maxPriorityFeePerGas`, `gas`, `value`, `data`, `nonce`, `accessList`, `type` at line 1 column 58
    at Web3RequestManager._processJsonRpcResponse (file:///I:/work/trading-tools-js/portfolio-tracker/node_modules/web3-core/lib/esm/web3_request_manager.js:252:23)
    at Web3RequestManager.<anonymous> (file:///I:/work/trading-tools-js/portfolio-tracker/node_modules/web3-core/lib/esm/web3_request_manager.js:150:29)
    at Generator.next (<anonymous>)
    at fulfilled (file:///I:/work/trading-tools-js/portfolio-tracker/node_modules/web3-core/lib/esm/web3_request_manager.js:20:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  innerError: {
    code: -32602,
    message: 'unknown field `input`, expected one of `from`, `to`, `gasPrice`, `maxFeePerGas`, `maxPriorityFeePerGas`, `gas`, `value`, `data`, `nonce`, `accessList`, `type` at line 1 column 58'  },
  code: 101,
  data: undefined,
  request: {
    jsonrpc: '2.0',
    id: 'b42d8661-13b8-4f96-a746-47f7dfe99371',
    method: 'eth_call',
    params: [
      {
        to: '0x94d9E02D115646DFC407ABDE75Fa45256D66E043',
        input: '0x95d89b41',
        data: '0x95d89b41'
      },
      'latest'
    ]
  }
}
```

**Comment by raxhvl** [comment]
Can confirm that an additional input parameter gets added to `eth_sendRawTransaction` rpc call as well. This is causing issue with local [Anvil](https://github.com/foundry-rs/foundry/blob/master/anvil/README.md) node.  Unsure why 'input' is copied over from data in the payload, since the rpc call does not have any such parameter.

https://github.com/web3/web3.js/blob/d12dc7e3c7d5ed56c38a5a300e769a9c205f3ddc/packages/web3-eth/src/utils/transaction_builder.ts#L175

Im happy to help fix this with a PR but not sure what the correct plan of action is :)

**Comment by luu-alex** [comment]
Hi there! Sorry for all the issues that this has been causing for your rpc calls, we'll be coming out with a fix from someone on the team expected for next release version

**Comment by Spacesai1or** [comment]
In `4.x`, if the user was providing `data` we were formatting it to `input` (removing `data`) and were expecting the RPC client to return `input` in the response. This worked for Geth and Ganache, but Nethermind accepts `input` or `data`, but returns only `data` in it's responses which was causing `data` to be dropped when formatting the responses since we were only expecting `input`. We tested submitting `data` and `input` to Geth, Ganache, and Nethermind and all worked without issue, so the idea became lets just submit `data` and `input` and format the response to contain both so we cover all the bases

As far as I'm aware, [this](https://ethereum.github.io/execution-apis/api-documentation/) is the current spec for RPC API and `eth_call`, `eth_estimateGas`, and `eth_sendTransaction` state it's `input`. I believe `data` is the legacy parameter name, but you can see how it's not an easy decision to make on which to use

We discussed on a call today to just allow either `input` or `data` to be sent (and we'll only use what the user provided, we won't submit both), and to just return whatever the RPC response contains (we also won't return both like we do right now) - this applies to all RPC calls that submit a transaction object and when web3 builds transaction objects as such with `eth_sendRawTransaction`

Hopefully this clear everything up and provides a solution that should work for all the edge cases. Apologies for the issues this has caused y'all, just a symptom of decentralization and not everyone following spec

**Comment by eshaben** [comment]
@spacesailor24 thanks for the detailed response! I was under the impression that `input` wasn't part of the spec, which is why I had raised the issue, but I'll share internally with our engineering team and we'll make the changes we need to be fully Etheruem compatible! 🙂

**Comment by Spacesai1or** [comment]
Sounds good! We're likely to still make the change (or something similar to) I've discussed above, so maybe we'll beat y'all to implementing change and your current implementation will start working 😉 

Either way, if anything else pops up, please let us know! We're also interested to hear how your experience with `4.x` is going, and we'd love feedback on any pain points, especially with migrating from `1.x` if y'all had to do that

**Comment by raxhvl** [comment]
I migrated from `1.x` to `4.x` and the experience was quite smooth. The upgrade guide was very helpful. Thanks again folks for the work you do!

**Comment by rickbeeloo** [comment]
@alex Is there a temporary fix for this (a branch?) cause it did not make it in the last release it seems, thanks!

**Comment by luu-alex** [comment]
@rickbeeloo  hi there, we'll have a dev work on it and have branch available hopefully sometime this week. thank you :)

**Comment by Spacesai1or** [comment]
@rickbeeloo #6294 is a PR to address this issue, as soon as it's merged a canary version will be released with this fix. An official release containing the fix will be released sometime after

**Comment by Spacesai1or** [comment]
As an update for everyone following this, the team has decided to revise our solution strategy. web3.js will still only submit which ever field(s) are given by the user, but we'll always return both `input` and `data` in the response, regardless of what the responding RPC response contains. This decision was made to refrain from making a breaking change for `4.x`

**Comment by eshaben** [comment]
@spacesailor24 hey! thanks for all the work on coming up with and implementing a solution for this issue! 🤗 

We are still running into some issues using the `sendSignedTransaction` function. The pre-check that you guys do calls `eth_call` with the transaction info, including the `v`, `r`, and `s` fields. So the transaction automatically fails unless we add the `{ checkRevertBeforeSending: false }` option as a parameter. You had pointed out the current spec in your previous comment:

> As far as I'm aware, [this](https://ethereum.github.io/execution-apis/api-documentation/) is the current spec for RPC API...

So I looked back at the spec, and `v`, `r`, and `s` are not a part of it. We at Moonbeam are discussing changing our node behavior to allow any parameter, like Ganache does. However, I was wondering if you guys would consider making updates so that the current spec is being used for the pre-check?

**Comment by jdevcs** [comment]
@eshaben we can skip signature part ( v, r, s ) in case of `eth_call` before sending signed transaction.
 [creating new issue](https://github.com/web3/web3.js/issues/6436) for tracking it.

**Comment by eshaben** [comment]
@jdevcs awesome. thanks!
