### ISSUE TITLE
maxFeePerGas requirement in 4.x

### ISSUE THREAD

**Issue by t-vila** [ethereum/web3.js#6215]
### Discussed in https://github.com/web3/web3.js/discussions/6188

<div type='discussions-op-text'>

<sup>Originally posted by **t-vila** June 12, 2023</sup>
Hey all,

As far as I remember `maxFeePerGas` was optional in 1.x and calculated from the `baseFee` - in 4.x I get `MissingGasError` if I don't specify it. It looks like it's expected https://github.com/web3/web3.js/blob/f8a2533c2b09ce0a62f8414f2f6eed83ab78ca1f/packages/web3-errors/src/errors/transaction_errors.ts#L315

For instance this:

```
const tx = {
    from: signer.address,
    to: "...",
    value: web3.utils.toWei('0.0001', 'ether'),
    gas: limit,
    nonce: await web3.eth.getTransactionCount(signer.address),
    maxPriorityFeePerGas: web3.utils.toWei('3', 'gwei'),
    //maxFeePerGas: web3.utils.toWei('3', 'gwei'),
    chainId: 11155111,
    type: 0x2
  };
```
Will throw:

`MissingGasError: Invalid value given "gas: 0x5208, gasPrice: undefined, maxPriorityFeePerGas: 0xb2d05e00, maxFeePerGas: undefined". Error: "gas" is missing.`</div>

**Comment by luu-alex** [comment]
Thank you for submitting this! 4.x is slightly different on validating transactions and the error message isn't clear, when we validate a transaction this is the [conditional](https://github.com/web3/web3.js/blob/4.x/packages/web3-eth/src/validation.ts#L253)
Since you are using `maxPriorityFeePerGas` and specified a type 2 transaction its expected that you define `maxFeePerGas` as well. 

If you wanted to submit a legacy transaction you would need to specify `gas && gasPrice`

I'll create a PR to make the error message more clear. thank you

For more clarity as well, what code/methods were u running
