### ISSUE TITLE
1.x "Error: Number can only safely store up to 53 bits" on batch getTransaction

### ISSUE THREAD

**Issue by nickbar86b** [ethereum/web3.js#6241]
Hello,
we are using web3 eth.getTransaction function to batch fetch transaction data using eth.BatchRequest();. 
However, in web3-core-helpers the outputTransactionFormatter is throwing "Error: Number can only safely store up to 53 bits" when is trying to parse gas value for BNB chain.
Here is a tx example: 0x3e005e4ef863873682e028a3f500ee575474ded431edc09ee70e7e3c4e981c6a
and the gas that is passed is 
gas: '0x7fffffffffffffff'

#### Expected behavior
to properly parse the value

#### Actual behavior
throws Error: Number can only safely store up to 53 bits

#### Environment
Web3 version 1.7.5

**Comment by nickbar86b** [comment]
FYI the error persists even when we upgrade to v1.10

**Comment by Spacesai1or** [comment]
Hi there, thank you for reporting this issue - it's actually a longstanding known issue with `1.x`. #5845 was merged to address this issue, but I don't see how you'd be able to pass `hexFormat` to the formatter [here](https://github.com/web3/web3.js/blob/6bde558b543693afd57ed04f7c7c45f5749e086c/packages/web3-core-helpers/src/formatters.js#L238)

We did completely fix this issue in the latest version of web3, version `4.x` though. Numbers are now formatted as `BitInt`s unless otherwise specified by the user

**Comment by nickbar86b** [comment]
I understand that in version 4 is resolved and we do plan to migrate ASAP but it is not straight forward and ideally we would like to have enough time to do it properly. A fix on this would give us that time. I wonder if gas can be moved into the if(hex) block or even if we treat the gas as a <string | number> instead; when the number is too big would temporarily fix the issue 🤷

**Comment by Spacesai1or** [comment]
#5845 is supposed to keep `gas` as a hex string if `hexFormat` is `true`, I just don't think you have access to that parameter as a user of the lib - We'll be working on fixing that if that's the case

A little off topic, but when you guys do decide to migrate to `4.x`, if you could share how it went, the good, bad, and ugly, we'd really appreciate it. We tried to limit the breaking changes, so it'll be nice to know what can still be improved upon and how we might be able to make the experience of migrating more straightforward
