### ISSUE TITLE
i get console error unkown account while trying to click any function 

### ISSUE THREAD

**Issue by Rickshanelorie** [ethereum/web3.js#6250]

**Comment by Muhammad-Altabba** [comment]
Hello @Rickshanelorie,
To be able to help you we need the full scenario and the exact full error. You need to provide the exact full detailed steps that we need to follow to get that error. web3.js does not have something to click on. So, you need to dig deep and isolate the scenario where you have an issue and get to know at which exact function call it happens and with which exact parameters... And then you would be able to fix it.

I recommend checking the docs https://docs.web3js.org/ and implementing some basic scenarios to know how things are supposed to be done. 

I will close this issue as it has no description, no steps to reproduce, and no mention of the used versions. However, after following the above-mentioned, if you still face an issue. Feel free to open it again with the full and very detailed steps  (as mentioned above). So that we can replicate the scenario on our machines and be able to help you.
