### ISSUE TITLE
4.x Web3 main package tutorial

### ISSUE THREAD

**Issue by mconnelly8** [ethereum/web3.js#6255]
Add a tutorial with the following:
- [ ] Executable examples
  - [x] Deploy contract
  - [x] Send transaction to contract method
  - [x] eth_call contract method
- [x] Reference links to API doc
- [x] Importing specific package

**Comment by Muhammad-Altabba** [comment]
This tutorial https://docs.web3js.org/guides/smart_contracts/deploying_and_interacting_with_smart_contracts  has:

-  Deploy contract
-  Send transaction to contract method
-  eth_call contract method

**Comment by jdevcs** [comment]
> This tutorial https://docs.web3js.org/guides/smart_contracts/deploying_and_interacting_with_smart_contracts has:
> 
> * Deploy contract
> * Send transaction to contract method
> * eth_call contract method

Thanks for bringing this in discussion, Existing tutorials should be reused:

so we discussed in call , for handwriting doc:
- [ ] re arrange menus by package names
- [ ] move tutorials / doc under that ( for some packages that has tutorials added )
- [ ] use refering back links to API section in tutorials / new doc
- [ ] all new doc should have TS code examples instead of JS

**Comment by Muhammad-Altabba** [comment]
This would be worked one after: https://github.com/web3/web3.js/issues/6548
