### ISSUE TITLE
getting error when trying to deploy a contract InvalidResponseError: Returned error: unknown field `input` .......

### ISSUE THREAD

**Issue by 0x0OZ** [ethereum/web3.js#6425]
#### Expected behavior
A successful transaction for contract creation.
#### Actual behavior

![image](https://github.com/web3/web3.js/assets/52073989/4a6f47a1-2184-44d9-a0db-c344f518f2a8)

#### Steps to reproduce the behavior
Use this code with any contract
```js
main = async () => {
    const W3 = require('web3');
    const Web3 = W3.Web3;
    const web3 = new Web3(new Web3.providers.HttpProvider('http://127.0.0.1:8545'));
    const contractABI = [{ "inputs": [], "name": "state", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" }]
    const contractBytecode = '6080604052348015600e575f80fd5b5060ac8061001b5f395ff3fe6080604052348015600e575f80fd5b50600436106026575f3560e01c8063c19d93fb14602a575b5f80fd5b60306044565b604051603b9190605f565b60405180910390f35b5f5481565b5f819050919050565b6059816049565b82525050565b5f60208201905060705f8301846052565b9291505056fea26469706673582212205caaf029a79ef4493aff4b19cbc6a8d2b1c29f882a6e13e4f2bd8d5e8182531f64736f6c63430008150033'
    const accounts = await web3.eth.getAccounts();
    const contract = new web3.eth.Contract(contractABI);
    const deployedContract = await contract
        .deploy({ data: contractBytecode })
        .send({ from: accounts[0] });
    console.log('Contract deployed to address:', deployedContract.address);
}

main();
```
adding `data` to `send()` will not change the error but will add the `data` attribute to the object
removing the `data` from `deploy()` will result in a different error (no creation code given)

#### Logs
![image](https://github.com/web3/web3.js/assets/52073989/b940ee30-0d22-4e84-8f87-9d041d9ee31d)
![image](https://github.com/web3/web3.js/assets/52073989/595bd83e-2f26-4969-b3ce-798895db8468)

#### Environment
node: Node.js v18.17.1
yarn: 1.22.19
OS: linux
kernel: 6.4.12-arch1-1
web3 tested versions: 4.1.1 and 4.1.0

**Comment by luu-alex** [comment]
Hi there, sorry that you are getting this error. This issue is fixed in the latest merges and will be available next release. You can use the dev branches right now until then. The latest dev branch is web3@4.1.2-dev.e4ba45c.0 as well you can check out the latest [active versions](https://www.npmjs.com/package/web3?activeTab=versions). 
With the latest version here are [docs ](https://docs.web3js.org/guides/smart_contracts/deploying_and_interacting_with_smart_contracts#troubleshooting-and-errors) to help with using data in your contracts if needed

Will be closing this unless there is any other issues. I hope this helps
