### ISSUE TITLE
tests are very slow

### ISSUE THREAD

**Issue by hexpaydaydev** [ethereum/web3.js#6445]
#### Expected behavior
unit tests are fast / moderately quick

#### Actual behavior
unit tests are slow

#### Steps to reproduce the behavior

1. clone repo
2. run `yarn` with node 18.17.0
3. run `yarn test`

#### Logs
```
web3-packagetemplate:  PASS  test/unit/constructor.test.ts (178.056 s)
web3-packagetemplate: Test Suites: 1 passed, 1 total
```

sometimes this test takes only 20 seconds, but i have never gotten past the first test within 5 mins

#### Environment

➜  web3.js git:(4.x) ✗ node -v
v18.17.0
➜  web3.js git:(4.x) ✗ yarn -v
1.22.15
➜  web3.js git:(4.x) ✗ uname -a
Darwin ....local 22.6.0 Darwin Kernel Version 22.6.0: ...; root:xnu-8796.141.3~6/RELEASE_ARM64_T8103 x86_64 i386 Darwin

**Comment by Muhammad-Altabba** [comment]
Hi @hexpaydaydev 
Thanks for sharing this. Actually, it does not take this long if you run only one of the tests. But, it takes longer for 1 test and less overall, when running all tests together. Because it runs the tests for all packages concurrently.

So, if you like to run the unit test for only one package, do like this:
```sh
cd tools/web3-packagetemplate/
yarn test
```

And the output would be something like:
```
yarn run v1.22.19
$ jest --config=./test/unit/jest.config.js
 PASS  test/unit/constructor.test.ts

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.392 s, estimated 62 s
Ran all test suites.
Done in 0.90s.
```

I hope this will resolve your issue, and I will close it.
However, in case you still have concerns, please reopen the issue and provide more about it.

All the best,
