### ISSUE TITLE
Metamask site suggested and value issue 

### ISSUE THREAD

**Issue by luu-alex** [ethereum/web3.js#6455]
Users on discord reported gas estimates that range from 0 to insanely high. investigate whether estimategas function needs improvement. 
![zsedx](https://github.com/web3/web3.js/assets/29740020/2ec56d94-5b94-4766-ac9f-42f10e8b73e6)
![zsed](https://github.com/web3/web3.js/assets/29740020/0b01acfc-b3e6-4d59-9b13-d96ae55818b4)

#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

**Comment by rafafortes** [comment]
I'm having a similar issue. Everything looks good when interacting with the contract using the Remix Editor however it doesn't work at all from my UI
![image](https://github.com/web3/web3.js/assets/20464782/04c51ebe-89be-4fc3-81e3-8738875561a8)

**Comment by ThomasCode92** [comment]
I had an issue (and the same error as @rafafortes) with the following code.

```javascript
await lottery.methods.enter().send({
  from: accounts[0],
  value: web3.utils.toWei(value, 'ether'),
});
```

I found [this](https://docs.web3js.org/guides/smart_contracts/deploying_and_interacting_with_smart_contracts/#troubleshooting-and-errors) in the doc, and after adding `data: lottery.methods.enter().encodeABI()` to the send object it worked

**Comment by Muhammad-Altabba** [comment]
[UPDATED]
Thanks @ThomasCode92, It seems your issue was different from this issue (number 6455).
And your issues I think is the one that has been now fixed with https://github.com/web3/web3.js/issues/6534 and available with web3.js version 4.2.2. And we are also communicating with MetaMask to follow the standard (https://github.com/MetaMask/metamask-extension/issues/21467). However, **updating your web3.js to version 4.2.2 or above should resolve that issue**. Also for web3.js versions older than 4.2.2, https://github.com/web3/web3.js/issues/6455#issuecomment-1763143376 workaround is supposed to work (thanks @ThomasCode92).

Thanks @luu-alex

**Comment by luu-alex** [comment]
https://github.com/web3/web3.js/issues/7081#issuecomment-2194827240 you can add options to use suggested gas price
