### ISSUE TITLE
web3.js is running without provider. You need to pass a provider in order to interact with the network!

### ISSUE THREAD

**Issue by liompei** [ethereum/web3.js#6726]
When I use webstorm to debug programs locally

`export default function Home() {

    const [account, setAccount] = useState('')

    const login = async () => {

        try {
            const ethereum = window.ethereum
            if (ethereum) {
                const web3 = new Web3(window.ethereum);
                
                }
}
`

As long as I call
`Const web3=new Web3 (window.ethereum);`
He will throw an error

page.js:9 NOTE: web3.js is running without provider. You need to pass a provider in order to interact with the network!

nodejs: 21.5.0
webjs:4.3.0

**Comment by SantiagoDevRel** [comment]
Hi @liompei this issue is not related to the library itself, this is related to the injected provider (in this case Metamask) and/or local runtime environment, so that's why `window.ethereum` is just returning an `undefined` value.

Maybe this can be helpful:
1. [MetaMask does not inject window.ethereum: Uncaught (in promise) TypeError: Cannot read property 'request' of undefined](https://stackoverflow.com/questions/65802366/metamask-does-not-inject-window-ethereum-uncaught-in-promise-typeerror-canno)

2. Have you tried running your code on a simple HTML file with an http server to see if it works?
2.1 install `npm i http-server`
2.2 run `http-server` (it might be available on localhost:8080/)

Here is a simple code sample:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>web3 cdn example</title>
    <script src="https://cdn.jsdelivr.net/npm/web3@latest/dist/web3.min.js"></script>
  </head>

  <body>
    <button id="getBlockButton">Get Block in console</button>
    <script>
      //with other provider
      //const web3 = new Web3("https://eth.llamarpc.com");

      //with metamask
      const web3 = new Web3(window.ethereum);

      const getBlockButton = document.getElementById("getBlockButton");

      getBlockButton.addEventListener("click", async () => {
        const block = await web3.eth.getBlockNumber();
        //print in console
        console.log("BLOCK # ", block);
      });
    </script>
  </body>
</html>
```

I hope it helps!

**Comment by mconnelly8** [comment]
Hey @liompei, I'm closing this issue since we provided a solution for you.  If that solution doesn't work for some reason, please open this back up for us to review your code example.
