### ISSUE TITLE
Transaction Guide

### ISSUE THREAD

**Issue by mconnelly8** [ethereum/web3.js#6745]
2024 H1 Action Items: Expand web3.js documentation with 5 guides explaining common usage and/or best practices

**Comment by SantiagoDevRel** [comment]
Hi @mconnelly8 , that guide is actually [here](https://docs.web3js.org/guides/wallet/transactions#sending-a-raw-transaction), I added it when I edited the docs 1 month ago, also here is a video that I did for it last week https://www.youtube.com/watch?v=szYBBuyUEWk&list=PLPn3rQCo3XrNf__8irs4-MjMt4fJqW2I_&index=4

We can close this issue since in the docs we have these examples: 
- 'sending tx with local wallet'
- 'sending a raw transaction' 
- 'sending a transaction with browser injection(metamask)'
