### ISSUE TITLE
Create a function `revokeAccess` that disconnects any previously connected wallets

### ISSUE THREAD

**Issue by AnumQ** [ethereum/web3.js#7037]
#### Create function named `revokeAccess` to disconnect previously connected wallet 

Create a function `revokeAccess` that implements the following RPC call in order to disconnect any previously connected accounts:

```
await window.ethereum.request({
    method: "wallet_revokePermissions",
    params: [
      {
        eth_accounts: {},
      },
    ],
  });
``` 
See more details [here](https://docs.metamask.io/wallet/reference/wallet_revokepermissions/)

**Comment by SantiagoDevRel** [comment]
good point @AnumQ !
@mconnelly8 she is one of the web3.js ambassadors :)

**Comment by jdevcs** [comment]
We discussed this in team meeting, and agreed on : instead of supporting `wallet_revokePermissions` only, we should add support of list of common wallet rpc functions like: `wallet_addEthereumChain` , `wallet_switchEthereumChain`, `wallet_getPermissions`, `wallet_requestPermissions`, `wallet_revokePermissions`, ..etc so scope of above task is :

- create list of RPC functions supported by major 3 wallets
- add these either in web3 core lib or create a plugin for generic wallet supported RPCs ( functionality, documentation, unit and e2e testing )

**Comment by AnumQ** [comment]
Thanks for the feedback @jdevcs! Do you already have somebody on the task? If not, I can look into implementation of the additional RPC functions once I am done with the Ambassador tasks 😊

**Comment by jdevcs** [comment]
@AnumQ , sure you can start working on this. Thanks for your contributions.

**Comment by mconnelly8** [comment]
Hey @AnumQ, are you working on this?

**Comment by Allen-Muhani** [comment]
Hello @mconnelly8 I would like to add this. I  will need some guidance on where to start as I nearly know the codebase and how it works.

**Comment by AnumQ** [comment]
No I am not working on it. Feel free to solve it😊

Mvh
*Anum*

**Comment by Allen-Muhani** [comment]
@mconnelly8 @SantiagoDevRel  @AnumQ Can I have access to the repo? I can't push my code/attempt for review. 

remote: Permission to web3/web3.js.git denied to Allen-Muhani.
fatal: unable to access 'https://github.com/web3/web3.js.git/': The requested URL returned error: 403

**Comment by jdevcs** [comment]
@Allen-Muhani directly pushing changes to main branch is not allowed, for contributions in web3.js lib create a feature branch and create PR.

For above issue, requirement is to create a web3.js plugin in new repo under your user in github, instead of adding in web3.js repo. 
https://docs.web3js.org/guides/web3_plugin_guide/#create-a-plugin

**Comment by Allen-Muhani** [comment]
Hello @jdevcs  I believe thats what I have been trying to do all along.
![Screenshot from 2024-09-18 11-26-21](https://github.com/user-attachments/assets/3eefa93a-05e9-498f-b7cc-5cb9c99c7f22)
![Screenshot from 2024-09-18 11-26-44](https://github.com/user-attachments/assets/d2061b28-6361-4faf-99b5-f4e4bcc152ee)

Kindly advice

**Comment by Allen-Muhani** [comment]
@AnumQ @SantiagoDevRel  I think this [script](https://docs.web3js.org/guides/web3_plugin_guide/#web3-requestmanager-custom-rpc) should resolve the issue with a lot of flexibility as suggested by @jdevcs . I believe the issue should be closed, however, if need be I can still push the code after my access privileges to push my code are sorted. 

It should be something like web3js.eth.revokeAccess() when done.

Kindly let me know.

**Comment by krzysu** [comment]
Hey, we recently released a Web3.js plugin that supports all popular wallet RPC methods, so we’re closing this issue as resolved.
You can find more details about the plugin here: [web3-plugin-wallet-rpc.](https://github.com/web3/web3-plugin-wallet-rpc)
