### ISSUE TITLE
Format schema with oneOf doesn't work correctly

### ISSUE THREAD

**Issue by avkos** [ethereum/web3.js#7055]
```ts
const schema = {
  type: 'object',
  properties: {
    from: {
      format: 'address',
    },
    to: {
      oneOf: [{ format: 'string' }, { type: 'null' }],
    },
  },
};

const data = {
  from: '0x7ed0e85b8e1e925600b4373e6d108f34ab38a401',
  to: 123,
};

const res = format(schema, data);

// res { from: '0x7ed0e85b8e1e925600b4373e6d108f34ab38a401', to: 123 }
```

**Actual Behaviour:**
`to` is not formatted

**Expected Behaviour:**
`to` should be formatted to a string

**Comment by Franklin-Osede** [comment]
Hello, I would like to contribute to resolve this issue. Thanks

**Comment by mmyyrroonn** [comment]
@Franklin-Osede Hi, are you working on this issue? I want to take over it if you're not yet. 😄

**Comment by mconnelly8** [comment]
Hey @mmyyrroonn, it doesn't look like @Franklin-Osede is working on this.  Please go ahead and work on this one.  We appreciate you wanting to help out.

**Comment by mmyyrroonn** [comment]
@avkos  @mconnelly8  Hi, after debugging the code, I found the root cause. 

The `schemaProp` would be `{"oneOf":[{"format":"string"},{"type":"null"}]}` during parsing the `to` property, which does not have `format` property. The `covertScalarValue` would throw an error and skip this property. The code path for this situation is missing in the current codebase.
https://github.com/web3/web3.js/blob/89711ab7f6a63d910848807ee77f0a91497aa897/packages/web3-utils/src/formatter.ts#L325

Here are three ways to fix this bug in my mind.
- fix it in the `convertScalarValue` function
- fix it in the `findSchemaByDataPath` function
- fix it in the `convert` function by adding extra logic, targeting this bug

I would like to know more about this bug and its background before I start my PR. Is there any guideline we should follow for the `oneOf` keyword? For example, if the schema is `to: {oneOf: [{ format: 'string' }, { format: 'number' }],},`, what should we do?

**Comment by luu-alex** [comment]
Hey there @mmyyrroonn  thanks for taking a look into this :) `to: {oneOf: [{ format: 'string' }, { format: 'number' }],}` I haven't dived into the formatter too much, but i dont believe this should be possible, maybe im not understanding why it would have these two different types of format?

**Comment by mmyyrroonn** [comment]
> Hey there @mmyyrroonn thanks for taking a look into this :) `to: {oneOf: [{ format: 'string' }, { format: 'number' }],}` I haven't dived into the formatter too much, but i dont believe this should be possible, maybe im not understanding why it would have these two different types of format?

Hi, I'm glad to hear your response. I'm not familiar with the schema. what is the definition of the keyword `oneOf`? The above example may be a wrong or invalid schema according to my personal understanding of the word `oneOf`. It's much better if there is a doc I can check to follow. Right now, I understand why the situation happened this way. However, I’m unsure about the correct code logic for this keyword. I don't want to fix a bug by creating a new one 😄

**Comment by luu-alex** [comment]
You bring up a really good point, docs would definitely be helpful in this and its something we probably want in the future :) 
In this [example](https://github.com/web3/web3.js/blob/9afaa613ee8792690032c6321acf74c32917732a/packages/web3-eth/src/schemas.ts#L98) 
```
to: {
			oneOf: [{ format: 'address' }, { type: 'null' }],
		},
```
oneOf allows the formatter match multiple types.
if `to` is defined, it must be formatted to an address
type describes it that it can also be null. 



In this [example](https://github.com/web3/web3.js/blob/9afaa613ee8792690032c6321acf74c32917732a/packages/web3-eth/src/schemas.ts#L324), 
```
transactions: {
			oneOf: [
				{
					type: 'array',
					items: {
						...transactionInfoSchema,
					},
				},
				{
					type: 'array',
					items: {
						format: 'bytes32',
					},
				},
			],
		},
```

oneOf allows a schema to be matched by either an array with objects of `transactionInfoSchema` and will be formatted what is being defined by [transactionInfoSchema](https://github.com/web3/web3.js/blob/9afaa613ee8792690032c6321acf74c32917732a/packages/web3-eth/src/schemas.ts#L92)  OR an array of items and must be formatted as `bytes32`.

Honestly you are being a really big help because this has been an issue thats persisted for quite a while 😅  and being able to identify that this is occuring because `format` isnt being defined is great. 

I think targetting 
`findSchemaByDataPath` or the `convert` would make most sense to me

**Comment by mmyyrroonn** [comment]
@luu-alex 

Thank you for the examples you provided. After reading them, I would like to confirm a few points:

1. Are the schemas within oneOf mutually exclusive? In other words, if there is a value, it should only match one of the schemas. Is this a precondition I can rely on when writing code?
2. If they are not mutually exclusive, what are the matching principles? For example, does it match the first one that appears? This is why I proposed to: {oneOf: [{ format: 'string' }, { format: 'number' }] }, although after looking at `schema.ts`, it seems unlikely in practical cases.
3. Will all scenarios be covered in the examples from schema.ts? Do we need to handle more general cases?

**Comment by luu-alex** [comment]
@mmyyrroonn Yes it should only match only one, and I believe that part is written already so you wouldn't need to worry. I think in this case 
```
to: {
      oneOf: [{ format: 'string' }, { type: 'null' }],
    },
```
 if i understand the error, `covertScalarValue` will fail because the object `{type: 'null'}` does not have format. In this scenario if before going into `covertScalarValue` check `type == "null"` and `isNullish(value) === true`  don't go into convertScalarValue and just have that property undefined.  
Id have to look at this more but I think that makes most sense to me, let me know what you think

**Comment by mmyyrroonn** [comment]
@luu-alex Let me share more details here for our discussion.
Because 'to' is already a top-level property, there is no recursive call above 'to'. Therefore, before executing the next line of code, dataPath is exactly 'to'.
https://github.com/web3/web3.js/blob/5ad7e5bad7c7d2e1794f0ff5024897f3eaddff4c/packages/web3-utils/src/formatter.ts#L290-L293
The output of `findSchemaByDataPath` is `{"oneOf":[{"format":"string"},{"type":"null"}]} instead of {"format":"string"}`, which, in my view, is incorrect. I am unsure if this result aligns with the original intent of the function or if `oneOf` should be handled correctly here. I will explain the specific logic of this function below.

https://github.com/web3/web3.js/blob/5ad7e5bad7c7d2e1794f0ff5024897f3eaddff4c/packages/web3-utils/src/formatter.ts#L295-L311
Since `schemaProp` is not `null` and the `value` is 123, which is not `object` or `array`, the above logic would be skipped and go into the `convertScalarValue` function.
https://github.com/web3/web3.js/blob/5ad7e5bad7c7d2e1794f0ff5024897f3eaddff4c/packages/web3-utils/src/formatter.ts#L325
The `schemaProp.format` is `undefined` and the `convertScalarValue` function would go into the error catch path.
https://github.com/web3/web3.js/blob/5ad7e5bad7c7d2e1794f0ff5024897f3eaddff4c/packages/web3-utils/src/formatter.ts#L134

Returning to this function, dataPath consists of only one item, so the loop will iterate only once and not twice. In this iteration, previousDataPath is empty, so the logic related to oneOf at line 59 is skipped, and lines 71 and 83 are executed directly. After the loop ends, the function returns. At this point, the `result` is `{"oneOf":[{"format":"string"},{"type":"null"}]}`.
https://github.com/web3/web3.js/blob/5ad7e5bad7c7d2e1794f0ff5024897f3eaddff4c/packages/web3-utils/src/formatter.ts#L50-L86
I'm unsure if the `findSchemaByDataPath` function should handle this scenario because in this case, the `oneOfPath` is also empty.
In my view, the handling logic for this example has been overlooked. Perhaps we should modify this logic to include additional handling.
https://github.com/web3/web3.js/blob/5ad7e5bad7c7d2e1794f0ff5024897f3eaddff4c/packages/web3-utils/src/formatter.ts#L303-L306
let me know what you think 😄

**Comment by luu-alex** [comment]
Ah I understand it a bit more, sure It makes sense to include this additional handling. Feel free to start on the PR

**Comment by mmyyrroonn** [comment]
> Ah I understand it a bit more, sure It makes sense to include this additional handling. Feel free to start on the PR

working on it

**Comment by mmyyrroonn** [comment]
@luu-alex Hi, I created a PR to demonstrate the fix. Actually, there are two issues: one is the problem I described above. The other is that `string` is not processed in the original logic; I’m not sure if this is an issue or if the issue itself is not actually a problem.

**Comment by luu-alex** [comment]
@mmyyrroonn Thanks for the PR! Ill take a look
