### ISSUE TITLE
Br: Unexpected error - Metamask Option not displaying

### ISSUE THREAD

**Issue by ryandavern** [ethereum/web3.js#7278]
evmAsk.js:7 Br: Unexpected error
    at Zh.request (chrome-extension://bfnaelmomeimhlpmgjnjophhpkkoljpa/evmAsk.js:7:4129)
    at async r.selectExtension

I'm connecting MetaMask with web3.js with a modal selector. Wallet Connect works, however, Metamask when clicked does nothing. I can provide the code I used if need be.

**Comment by danforbes** [comment]
Hi, @ryandavern - yes a link to a GitHub repo would be great 🙏🏻

**Comment by ryandavern** [comment]
https://github.com/ryandavern/RhythmWebApp/blob/main/premium2.php

**Comment by ryandavern** [comment]
Also included Web3Modal example which does the same no popup error - https://github.com/ryandavern/RhythmWebApp/blob/main/premium.php

**Comment by danforbes** [comment]
Hi, @ryandavern - I only looked at the first link you shared (`premium2.php`) because the second link is for a webpage that is using Ethers.js as opposed to Web3.js. I am really only familiar with Web3.js so unfortunately I won't be able to offer any help for Ethers.js. However, when I opened the `premium2.php` website in my browser (I did rename it to `index.html`) everything seemed to work as I would expect, although I didn't use the form to "Send BNB". Can you clarify what you mean when you say "Metamask when clicked does nothing"? What behavior are you expecting versus the actual behavior you're experiencing? [This code block](https://github.com/ryandavern/RhythmWebApp/blob/main/premium2.php#L110-L124) does look a little funny to me, though, so I will add some thoughts below.

```js
if (window.ethereum) {
  web3 = new Web3(window.ethereum);
  try {
    // Request account access if needed
    // use https://docs.web3js.org/libdocs/Web3Eth#requestaccounts
    web3.eth.requestAccounts().then((accounts) => {
      console.log("DApp connected to MetaMask");
      console.log(accounts);
    });
    // window.ethereum.enable().then(() => {
    //   console.log("DApp connected to MetaMask");
    // });
  } catch (error) {
    console.error("User denied account access");
  }
} else if (window.web3) {
  // I don't think you should do this
  // web3 = new Web3(window.web3.currentProvider);
  alert("Please install MetaMask to use this DApp.");
} else {
  alert("Please install MetaMask to use this DApp.");
}
```

![image](https://github.com/user-attachments/assets/2c924a2f-4cba-481a-9767-079e42f5debd)

**Comment by ryandavern** [comment]
![image](https://github.com/user-attachments/assets/205cbca8-74aa-437d-89bf-64ae48e61d19)
I get the following error when clicking on Send BNB, on all browsers

**Comment by danforbes** [comment]
It looks like the error you're getting may be coming from an extension. Maybe try turning off all your extensions except MetaMask and see if that makes a difference. What chain is the dApp supposed to be run against?

**Comment by ryandavern** [comment]
Opening in a clean browser worked, so it was an extension :).

Thank you for the help!
