### ISSUE TITLE
 [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.

### ISSUE THREAD

**Issue by mcwebdev** [ethereum/web3.js#7355]
[DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead. 

 at node_modules/whatwg-url/lib/url-state-machine.js (web3.js:540:20)

**Comment by mconnelly8** [comment]
Hey @mcwebdev, thanks, we will look into this.

**Comment by danforbes** [comment]
@mcwebdev - can you elaborate on the problem you're reporting? Is this a warning you see on the command line?

**Comment by mcwebdev** [comment]
Yes, I used the node trace when running my server to isolate the root of the error. url-state-machine.js (web3.js:540:20). It seems web3 relies on an external pkg? whatwg-url

**Comment by danforbes** [comment]
When does the warning appear?

**Comment by whitemoshui** [comment]
I think this issue is not caused by web3.js. I found several issues about this warning in `yarn` or `nodemon`
https://github.com/remy/nodemon/issues/2156
https://stackoverflow.com/questions/78516645/warning-deprecationwarning-the-punycode-module-is-deprecated-please-use-a-u
https://dev.to/asim_khan_cbe65e41bcbbc65/solving-the-punycode-module-is-deprecated-issue-in-nodejs-2e59

**Comment by krzysu** [comment]
This issue doesn’t appear to be directly related to Web3.js but rather to one of its dependencies. Please consider creating an issue in the relevant package repository, which in this case seems to be `whatwg-url`.
