### ISSUE TITLE
Support for proxy

### ISSUE THREAD

**Issue by Ochir** [ethereum/web3.js#887]
Hi,

my current company uses proxy and it is not possible now to use all features of Web3 while there is no setting for proxy. 
Please, add such feature to Web3.

**Comment by xuzhiping7** [comment]
I need this feature too ...

**Comment by kjsninja** [comment]
This is also our problem and come up with an `improvised` solution until they give full support.
We resolved it by modifying the `node_modules/xh2-cookies/dist/xml-http-request.js`.
I use `https-proxy-agent` to add a **proxy agent** inside `XMLHttpRequest`.
Source: [http://codingmiles.com/node-js-making-https-request-via-proxy/](url)

Step 1 : Import the proxy agent
```
....
....
Object.defineProperty(exports, "__esModule", { value: true });
var HttpsProxyAgent = require('https-proxy-agent'); //<-- added
var http = require("http");
....
....

```

Step 2 : Add the new proxy agent
```
....
....
var _a = this._url.protocol === 'http:' ? [http, this.nodejsHttpAgent] : [https, this.nodejsHttpsAgent], hxxp = _a[0], agent = _a[1];
var requestMethod = hxxp.request.bind(hxxp);
agent = new HttpsProxyAgent(process.env.SERVER_PROXY_URL); //<-- added
....
....
```
WARNING : **Not for production use.**

I'm hoping this will be fully supported in future release.

**Comment by fergarrui** [comment]
Any news about proxy support?

**Comment by 0xjjpa** [comment]
Hi @nivida, how's it going? A couple of questions regarding this feature request.

1. The latest pull request trying to tackle this issue #2980 seems to have going stale. Are you currently taking pull-requests on this feature in order to continue this issue?
1. Seems like #2979 which landed in `1.2.1` tackled this topic on web sockets. Would it be accurate to say that there's still no implementation for a HTTP proxy in web3.js as of `latest`?
1. Considering the `latest` version is `1.2.1` and the `next` version in [npm](https://www.npmjs.com/package/web3) as `2.0.0-alpha.1`, yet we have ongoing commits on the `1.x` branch, when would a incoming patch/minor release be able to be scheduled/requested to sneak features like this? 
1. There had been multiple [work arounds](https://github.com/ethereum/web3.js/issues/887#issuecomment-418061024) suggesting how to tackle this, but seem outdated. What would be the fastest way to land a proxy call using something like [https-proxy-agent](https://www.npmjs.com/package/https-proxy-agent)? I've noticed in #2980 you mention [nodejsSet](https://github.com/ethereum/web3.js/blob/v1.2.1/packages/web3-providers-http/src/index.js#L54-L57) allows to update the `http` and `https` Agent, yet it's not being read in `options`. Would you agree that expanding the `options` object passed to the HTTP provider and then doing something like `this.httpAgent = options.httpProxy || this.httpAgent` around line 49 would be the easiest? This is related to 1. as most likely would be the code for my PR.
1. Finally, I can't find anything related to enhancing the providers or even passing options like `transactionConfirmationBlocks` to web3 in the [documentation](https://web3js.readthedocs.io/en/v1.2.1/web3.html). Adding those features on creation has been more of a read-the-source-code like process. Am I looking at the wrong place when trying to answer these questions?

My current use case is having a server reaching infura via proxy. In development, the server has a free pass to reach infura, but in production we set a proxy for anonymity. I do not believe there's an easy way right now to do this over HTTP/HTTPS, but I might be wrong.

Any help here to clarify this is appreciated. Pinging @benzumbrunn who helped me with all web3 proxy topics before leaving the Swiss Alps 😢, maybe he'll find these questions interesting 👀 .

**Comment by 0xjjpa** [comment]
All the requested PR's had been merged and a successful usage of an `httpProxy` was implemented. For googlers, this was achieved passing a [tunnel](https://www.npmjs.com/package/tunnel) and a `httpsOverhttp` proxy to now the available `httpAgent` option of the constructor. This issue can now be closed.

**Comment by ryanio** [comment]
thanks @jjperezaguinaga!
