### ISSUE TITLE
1.0 : confirmTransaction does not work on InstantSealEngine

### ISSUE THREAD

**Issue by simon-jentzsch** [ethereum/web3.js#935]
since parity --chain dev is using its InstantSealEngine and creating Block as soon as a new Transaction is send, the subscribed event for the new BlockHeader will come too late. This results in a waiting forever for a new Block, which never comes. So we must first check whether the transaction has already been mined before subscribing for new Blocks.

**Comment by frozeman** [comment]
So the event in the InstantSealEngine is fired right away?
So we need to subscribe, before we even send the TX? Which we can't as we don't have the tx hash at this time yet.

If you use the HTTP provider, it will use and interval, rather than a subscription.
I don't know what solution is good in this case :(

**Comment by simon-jentzsch** [comment]
currently I simply called getTransactionReceipt before subscribing. If the transaction is already confirmed then we can simply trigger the events. If not we start subscribing or set the interval to wait for. (See https://github.com/ethereum/web3.js/pull/936/files ) This seems to work for me.

**Comment by simon-jentzsch** [comment]
pull-request is merged, it is working now.

**Comment by enriquefynn** [comment]
I'm still having issues after the fix.
Using InstantSealEngine and web3.eth.sendSignedTransaction
