### ISSUE TITLE
web3.eth.filter not exist

### ISSUE THREAD

**Issue by facelinker** [ethereum/web3.js#983]
When i call web3.eth.filter() 
compiler throw error "TypeError: web3.eth.filter is not a function".

**Comment by frozeman** [comment]
In 1.0 you use web3.eth.subscribe.  But this will only work on websocket. And IPC connections. 

If there is a case for we adding the old filter, we can discuss it here

**Comment by morelazers** [comment]
Docs don't mention `subscribe` here: https://github.com/ethereum/wiki/wiki/JavaScript-API

Is it still safe to use filter on an older version of web3.js? What's the reason it's being deprecated?

**Comment by cmditch** [comment]
web3 version 0.20 is `web3.eth.filter()`, version 1.0 (in beta) is `web3.eth.subscribe`. You'll want to check your web3 version.

As @frozeman said, `subscribe` will not work with an HTTP Provider, only websocket and IPC. Web3 1.0 uses pub/sub listening for logs/events, while web3 0.20 used polling.

**Comment by doronaviguy** [comment]
Correct docs link [here](https://web3js.readthedocs.io/en/1.0/web3-eth-subscribe.html)

**Comment by szerintedmi** [comment]
So what is our option with web3@1.0 when we want to listen to events using http provider?

**Comment by atomixxx2** [comment]
Hi, what is the option in 1.0 to fetch old log/events from the blockchain??, because im using "subscribe" with fromblock:0 and im getting only new transactions after subscription... in 0.2 version I was able to get old logs just with fromBlock and toBlock very easily, Im using websocket.

**Comment by chiro-hiro** [comment]
@szerintedmi @frozeman Might be we need to implement HTTP/2. It will be awesome to use `subscribe` with HTTP provider.

https://tools.ietf.org/html/rfc7540#section-8.2

**Comment by jamesmorgan** [comment]
Does the subscription function support start and end block like the filter method?

**Comment by nivida** [comment]
@jamesmorgan Yes, it does. Hopefully, we can soon implement the Http 2.0 subscriptions.

**Comment by coderNeos** [comment]
I would like to share my experience working with the new subscribe feature. We have 4 different microservices, which use web3.eth.subscribe method and major problem is that after a day or few, a subscription is dropped (it seems it is Geth's fault), but we don't get any errors or anything. It just stops listening for new contract events. The temporary solution we found is to restart our applications regularly (once a day), but sometimes it doesn't help because subscription can be lost only after a few hours.

So to sum, it would be really nice to implement pulling algorithm using HTTP interface in web3 v1.
Also, JSON-RPC2.0 Geth feature was marked as experimental not so long ago. For short-lived subscriptions, we haven't yet encountered any problems
